'use strict';(function(exports){var _id=0;var AppChrome=function AppChrome(app){this.app=app;this.instanceID=_id++;this.containerElement=app.element;this._recentTitle=false;this._titleTimeout=null;this.scrollable=app.browserContainer;this.render();if(this.app.themeColor){this.setThemeColor(this.app.themeColor);}
var chrome=this.app.config.chrome;if(!this.app.isBrowser()&&chrome&&!chrome.scrollable){this._fixedTitle=true;this.title.dataset.l10nId='search-the-web';}else if(!this.app.isBrowser()&&this.app.name){this._gotName=true;this.setFreshTitle(this.app.name);}
this.reConfig();};AppChrome.prototype=Object.create(window.BaseUI.prototype);AppChrome.prototype.CLASS_NAME='AppChrome';AppChrome.prototype.EVENT_PREFIX='chrome';AppChrome.prototype.FRESH_TITLE=500;AppChrome.prototype.LOCATION_COALESCE=250;AppChrome.prototype._DEBUG=false;AppChrome.prototype.destroy=function(){if(this.browserWindowNavigator){this.browserWindowNavigator.destroy();this.browserWindowNavigator=undefined;}
BaseUI.prototype.destroy.call(this);}
AppChrome.prototype.reConfig=function(){var chrome=this.app.config.chrome;if(!chrome){return;}
if(this.isSearchApp()){this.app.element.classList.add('search-app');this.title.setAttribute('data-l10n-id','search-or-enter-url');}else{this.app.element.classList.remove('search-app');}
if(chrome.bar){this.app.element.classList.add('bar');this.bar.classList.add('visible');}
if(chrome.scrollable){this.app.element.classList.add('collapsible');this.scrollable.scrollgrab=true;}
if(chrome.maximized){this.element.classList.add('maximized');if(!this.app.isBrowser()){this.app.element.classList.add('scrollable');}}
if(!this.app.isPopupWindow()&&(this.app.isBrowserOrSearch()||this.app.isCursorEnabled())){if(this.browserWindowNavigator){this.browserWindowNavigator.destroy();}
this.browserWindowNavigator=new BrowserWindowNavigator(this);}};AppChrome.prototype.combinedView=function an_combinedView(){var className=this.CLASS_NAME+this.instanceID;return`<div class="chrome chrome-combined" id="${className}">
              <gaia-progress class="hidden"></gaia-progress>
              <div class="controls">
                <div class="urlbar js-chrome-ssl-information">
                  <div class="chrome-ssl-indicator chrome-title-container">
                    <span data-icon="lock" class="hide"></span>
                    <span class="title p-pri" dir="auto"></span>
                  </div>
                </div>
              </div>
            </div>`;};AppChrome.prototype.view=function an_view(){var className=this.CLASS_NAME+this.instanceID;return`<div class="chrome chrome-plain" id="${className}">
            <gaia-progress class="hidden"></gaia-progress>
            <section role="region" class="bar">
              <gaia-header action="close" class='js-chrome-ssl-information'>
                <div class="chrome-ssl-indicator chrome-ssl-indicator-ltr">
                  <span data-icon="lock" class="hide"></span>
                </div>
                <h1 class="chrome-title-container">
                  <bdi dir="auto" class="title p-pri"></bdi>
                </h1>
                <div class="chrome-ssl-indicator chrome-ssl-indicator-rtl">
                </div>
              </gaia-header>
            </section>
          </div>`;};AppChrome.prototype.__defineGetter__('height',function ac_getHeight(){if(this._height){return this._height;}
this._height=this.element.getBoundingClientRect().height;return this._height;});AppChrome.prototype._fetchElements=function ac__fetchElements(){this.element=this.containerElement.querySelector('.chrome');this.progress=this.element.querySelector('gaia-progress');this.title=this.element.querySelector('.chrome-title-container > .title');this.sslIndicator=this.element.querySelector('.js-chrome-ssl-information');this.sslDataIcon=this.element.querySelector('.js-chrome-ssl-information  > span[data-icon]');this.bar=this.element.querySelector('.bar');if(this.bar){this.header=this.element.querySelector('gaia-header');}};AppChrome.prototype.handleEvent=function ac_handleEvent(evt){switch(evt.type){case'rocketbar-overlayclosed':this.collapse();break;case'action':this.handleActionEvent(evt);break;case'scroll':this.handleScrollEvent(evt);break;case'_loading':this.show(this.progress);this.progress.classList.remove('hidden');let currentURL=(evt.detail&&evt.detail.url)?evt.detail.url:this._currentURL;this.updateLoadingLocation(currentURL);break;case'_loaded':this.hide(this.progress);this.progress.classList.add('hidden');break;case'mozbrowserloadstart':this.handleLoadStart(evt);break;case'mozbrowserloadend':this.handleLoadEnd(evt);break;case'mozbrowsererror':this.handleError(evt);break;case'mozbrowserlocationchange':this.handleLocationChanged(evt);break;case'mozbrowserscrollareachanged':this.handleScrollAreaChanged(evt);break;case'_securitychange':this.handleSecurityChanged(evt);break;case'mozbrowsertitlechange':this.handleTitleChanged(evt);break;case'mozbrowsermetachange':this.handleMetaChange(evt);break;case'_namechanged':this.handleNameChanged(evt);break;}};AppChrome.prototype.handleKey=function(key){if(!this.app.isPopupWindow()&&(this.app.isBrowserOrSearch()||this.app.isCursorEnabled())){return this.browserWindowNavigator.handleKey(key);}
return false;};AppChrome.prototype.handleActionEvent=function ac_handleActionEvent(evt){if(evt.detail.type==='close'){if(!this.app.isHomescreen){this.app.kill();}}};AppChrome.prototype.handleScrollEvent=function ac_handleScrollEvent(){if(!this.containerElement.classList.contains('scrollable')){return;}
var element=this.element;if(this.scrollable.scrollTop>=this.scrollable.scrollTopMax-1){element.classList.remove('maximized');}else{element.classList.add('maximized');}
if(this.app.isActive()){this.app.publish('titlestatechanged');}};AppChrome.prototype._registerEvents=function ac__registerEvents(){if(this.useCombinedChrome()){LazyLoader.load('shared/js/bookmarks_database.js');this.scrollable.addEventListener('scroll',this);}else{this.header.addEventListener('action',this);}
this.app.element.addEventListener('mozbrowserloadstart',this);this.app.element.addEventListener('mozbrowserloadend',this);this.app.element.addEventListener('mozbrowsererror',this);this.app.element.addEventListener('mozbrowserlocationchange',this);this.app.element.addEventListener('mozbrowsertitlechange',this);this.app.element.addEventListener('mozbrowsermetachange',this);this.app.element.addEventListener('mozbrowserscrollareachanged',this);this.app.element.addEventListener('_securitychange',this);this.app.element.addEventListener('_loading',this);this.app.element.addEventListener('_loaded',this);this.app.element.addEventListener('_namechanged',this);var element=this.element;var animEnd=function(evt){if(evt&&evt.target!==element){return;}
var publishEvent=this.isMaximized()?'expanded':'collapsed';this.app.publish('chrome'+publishEvent);}.bind(this);element.addEventListener('transitionend',animEnd);};AppChrome.prototype._unregisterEvents=function ac__unregisterEvents(){if(this.useCombinedChrome()){this.scrollable.removeEventListener('scroll',this);}else{this.header.removeEventListener('action',this);}
if(!this.app){return;}
this.app.element.removeEventListener('mozbrowserloadstart',this);this.app.element.removeEventListener('mozbrowserloadend',this);this.app.element.removeEventListener('mozbrowsererror',this);this.app.element.removeEventListener('mozbrowserlocationchange',this);this.app.element.removeEventListener('mozbrowsertitlechange',this);this.app.element.removeEventListener('mozbrowsermetachange',this);this.app.element.removeEventListener('mozbrowserscrollareachanged',this);this.app.element.removeEventListener('_securitychange',this);this.app.element.removeEventListener('_loading',this);this.app.element.removeEventListener('_loaded',this);this.app.element.removeEventListener('_namechanged',this);this.app=null;};AppChrome.prototype.handleNameChanged=function ac_handleNameChanged(){this._title=this.app.name;this._gotName=true;};AppChrome.prototype.setFreshTitle=function ac_setFreshTitle(title){if(this.isSearchApp()){return;}
this._title=this.title.textContent=title;clearTimeout(this._titleTimeout);this._recentTitle=true;this._titleTimeout=setTimeout((function(){this._recentTitle=false;}).bind(this),this.FRESH_TITLE);};AppChrome.prototype.handleScrollAreaChanged=function(evt){if(this.containerElement.classList.contains('scrollable')){return;}
if(evt.detail.height>=this.containerElement.clientHeight){this.containerElement.classList.add('scrollable');}};AppChrome.prototype.handleSecurityChanged=function(){var sslState=this.app.getSSLState();this.sslIndicator.dataset.ssl=sslState;this.sslIndicator.classList.toggle('chrome-has-ssl-indicator',sslState==='broken'||sslState==='secure');if(!this.sslDataIcon){return;}
if(sslState==='broken'){this.sslDataIcon.setAttribute('data-icon','lock-broken');}else if(sslState==='secure'){this.sslDataIcon.setAttribute('data-icon','lock');}else{this.sslDataIcon.setAttribute('data-icon','');}};AppChrome.prototype.handleTitleChanged=function(evt){if(this._gotName||this._fixedTitle){return;}
this.setFreshTitle(evt.detail||this._currentURL);this._titleChanged=true;};AppChrome.prototype.handleMetaChange=function ac__handleMetaChange(evt){var detail=evt.detail;if(detail.name!=='theme-color'||!detail.type){return;}
var color='';if(detail.type!=='removed'){color=detail.content;}
this.setThemeColor(color);};AppChrome.prototype.setThemeColor=function ac_setThemColor(color){if(this.app.isBrowser()){return;}
var bottomApp=this.app.getBottomMostWindow();if(this.app.CLASS_NAME==='PopupWindow'&&bottomApp&&bottomApp.themeColor){color=bottomApp.themeColor;}
this.app.themeColor=color;this.element.style.backgroundColor=color;if(!this.app.isHomescreen&&!this.app.getPlaceholderColor()&&!this.app.config.isActivity){this.scrollable.style.backgroundColor=color;}
if(color==='transparent'||color===''){this.app.element.classList.remove('light');this.app.publish('titlestatechanged');return;}
if(this.app.isHostedApp()){this.app.element.classList.add('hosted');if(this.app.isProgressBarEnabled()){this.element.classList.add('progress-bar-enabled');}}
var self=this;var finishedFade=false;var endBackgroundFade=(evt)=>{if(evt&&evt.propertyName!='background-color'){return;}
finishedFade=true;if(this.element){this.element.removeEventListener('transitionend',endBackgroundFade);}};eventSafety(this.element,'transitionend',endBackgroundFade,1000);window.requestAnimationFrame(function updateAppColor(){if(finishedFade||!self.element){return;}
var computedColor=self.app.themeColor;var colorCodes=/rgb\((\d+), (\d+), (\d+)\)/.exec(computedColor);if(!colorCodes||colorCodes.length===0){return;}
var r=parseInt(colorCodes[1]);var g=parseInt(colorCodes[2]);var b=parseInt(colorCodes[3]);var brightness=Math.sqrt((r*r)*0.241+(g*g)*0.691+(b*b)*0.068);var wasLight=self.app.element.classList.contains('light');var isLight=brightness>200;if(wasLight!=isLight){self.app.element.classList.toggle('light',isLight);self.app.publish('titlestatechanged');}
window.requestAnimationFrame(updateAppColor);});};AppChrome.prototype.render=function(){this.publish('willrender');var view=this.useCombinedChrome()?this.combinedView():this.view();this.app.element.insertAdjacentHTML('afterbegin',view);this._fetchElements();this._registerEvents();this.publish('rendered');};AppChrome.prototype.useLightTheming=function ac_useLightTheming(){if(this.app.CLASS_NAME=='PopupWindow'&&this.app.rearWindow&&this.app.rearWindow.appChrome){return this.app.rearWindow.appChrome.useLightTheming();}
return this.app.element.classList.contains('light');};AppChrome.prototype.useCombinedChrome=function ac_useCombinedChrome(evt){return this.app.config.chrome&&!this.app.config.chrome.bar;};AppChrome.prototype._updateLocation=function ac_updateTitle(title){if(this._titleChanged||this._gotName||this._recentTitle||this._fixedTitle){return;}
this._title=title;this.updateLoadingLocation(title);};AppChrome.prototype.handleLocationChanged=function ac_handleLocationChange(evt){if(!this.app){return;}
var anchorChange=false;if(this._currentURL&&evt.detail.url){anchorChange=this._currentURL.replace(/#.*/g,'')===evt.detail.url.replace(/#.*/g,'');}
setTimeout(this._updateLocation.bind(this,evt.detail.url),this.LOCATION_COALESCE);this._currentURL=evt.detail.url;if(!this.app.isBrowser()){return;}
this._gotName=false;if(!anchorChange){this.containerElement.classList.remove('scrollable');if(!this.isMaximized()){this.element.classList.add('maximized');}
this.scrollable.scrollTop=0;}};AppChrome.prototype.updateLoadingLocation=function(url){if(url&&this.app&&this.app.loading){this.title.textContent=url;}};AppChrome.prototype.handleLoadStart=function ac_handleLoadStart(){this.containerElement.classList.add('loading');this._titleChanged=false;};AppChrome.prototype.handleLoadEnd=function ac_handleLoadEnd(){this.containerElement.classList.remove('loading');};AppChrome.prototype.handleError=function ac_handleError(evt){if(evt.detail&&evt.detail.type==='fatal'){return;}
if(this.useCombinedChrome()&&this.app.config.chrome.scrollable){this.element.classList.add('maximized');this.containerElement.classList.remove('scrollable');}};AppChrome.prototype.maximize=function ac_maximize(callback){var element=this.element;element.classList.add('maximized');window.addEventListener('rocketbar-overlayclosed',this);if(!callback){return;}
eventSafety(element,'transitionend',callback,250);};AppChrome.prototype.collapse=function ac_collapse(){window.removeEventListener('rocketbar-overlayclosed',this);this.element.classList.remove('maximized');};AppChrome.prototype.isMaximized=function ac_isMaximized(){return this.element.classList.contains('maximized');};AppChrome.prototype.isSearch=function ac_isSearch(){var dataset=this.app.config;return dataset.searchURL&&this._currentURL===dataset.searchURL;};AppChrome.prototype.isSearchApp=function(){return this.app.config.manifest&&this.app.config.manifest.role==='search';};AppChrome.prototype.hasNavigation=function ac_hasNavigation(){return this.app.isBrowser()||(this.app.config.chrome&&this.app.config.chrome.navigation);};AppChrome.prototype.addBookmark=function ac_addBookmark(){var dataset=this.app.config;var favicons=this.app.favicons;var name;if(this.isSearch()){name=dataset.searchName;}else{name=this.title.textContent;}
var url=this._currentURL;return LazyLoader.load('shared/js/icons_helper.js').then(()=>{return IconsHelper.getIcon(url,null,{icons:favicons}).then(icon=>{return BookmarksDatabase.add({url:url,name:name,icon:icon}).then(()=>{return Promise.resolve();},()=>{return Promise.reject('hasPinned');});},(reason)=>{return Promise.reject(reason);});},(reason)=>{return Promise.reject(reason);});};exports.AppChrome=AppChrome;}(window));