'use strict';(function(exports){var DEBUG=false;var TRACE=false;var _id=0;var AppWindow=function AppWindow(configuration){this.reConfig(configuration);this.render();this.publish('created');if(DEBUG||this._DEBUG){this.constructor[this.instanceID]=this;}
this.launchTime=Date.now();return this;};AppWindow.prototype.CLASS_LIST='appWindow';AppWindow.prototype._DEBUG=false;AppWindow.prototype.HIERARCHY_MANAGER='AppWindowManager';AppWindow.prototype.generateID=function(){if(!this.instanceID){this.instanceID=this.CLASS_NAME+'_'+_id;_id++;}};AppWindow.prototype.reConfig=function aw_reConfig(configuration){for(var key in configuration){this[key]=configuration[key];}
this.browser_config=configuration;this.config=configuration;this.config.chrome=(this.manifest&&this.manifest.chrome)?this.manifest.chrome:this.config.chrome;if(!this.config.chrome){this.config.chrome={scrollable:this.isBrowser(),maximized:this.isBrowser()};}else if(this.config.chrome.navigation){this.config.chrome.scrollable=!this.isFullScreen();this.config.chrome.maximized=true;}
if(this.manifest){this.shortName=new ManifestHelper(this.manifest).short_name;}
if(!this.manifest&&this.config&&this.config.title){this.updateName(this.config.title);}else{this.name=new ManifestHelper(this.manifest).name;}
this.getIconForSplash();this.generateID();this.groupID=this.getRootWindow().instanceID;if(this.previousWindow){this.previousWindow.setNextWindow(this);}else if(this.rearWindow){this.rearWindow.setFrontWindow(this);}};AppWindow.prototype.updateName=function aw_updateName(name){if(this.config&&this.config.title){this.config.title=name;}
this.name=name;};AppWindow.prototype._visibilityState='foreground';AppWindow.prototype.rotatingDegree=0;AppWindow.prototype._dump=function aw__dump(){console.log('======================');try{throw new Error('e');}catch(e){this.debug(e.stack);}
console.log('======================');};AppWindow.prototype.setActive=function(enable){this.getTopMostWindow()._setActive(enable);};AppWindow.prototype.setVisible=function aw_setVisible(visible){this.debug('set visibility -> ',visible);this.setVisibleForScreenReader(visible);this._setActive(visible);if(visible){this._showFrame();}else{this._hideFrame();}
if(this.frontWindow){this.frontWindow.setVisible(visible);}};AppWindow.prototype.setVisibleForScreenReader=function aw_setVisibleForScreenReader(visible){if(!this.element){return;}
if(!this.browser){this.reviveBrowser();}
this.debug('setVisibleForScreenReader:',visible);this.element.setAttribute('aria-hidden',!visible);setBrowserProperty(this.browser.element,'canTakeFocus',visible);this.toggleSpatialNavigation();};AppWindow.prototype._showFrame=function aw__showFrame(){this.debug('before showing frame');this.reviveBrowser();if(!this.browser.element.classList.contains('hidden')){return;}
this.browser.element.classList.remove('hidden');this._setVisible(true);if(this.isHomescreen){return;}
if(this.screenshotOverlay&&this.screenshotOverlay.classList.contains('visible')){this.tryWaitForFullRepaint(this._hideScreenshotOverlay.bind(this));}};AppWindow.prototype._hideFrame=function aw__hideFrame(){this.debug('before hiding frame');if(!this.browser||this.browser.element.classList.contains('hidden')){return;}
this._setVisible(false);this.browser.element.classList.add('hidden');};AppWindow.prototype.isActive=function aw_isActive(){if(!this.element){return false;}
if(this.element.classList.contains('will-become-active')){return true;}
if(this.element.classList.contains('will-become-inactive')){return false;}
if(this.transitionController){return(this.transitionController._transitionState=='opened'||this.transitionController._transitionState=='opening');}else{return false;}};AppWindow.prototype.shouldResize=function aw_shouldResize(){if(this.element.classList.contains('will-become-inactive')){return true;}
return this.isActive();};AppWindow.prototype.isSheetTransitioning=function aw_isSheetTransitioning(){return this.element.classList.contains('inside-edges');};AppWindow.prototype.isTransitioning=function aw_isTransitioning(){if(this.transitionController){return(this.transitionController._transitionState=='opening'||this.transitionController._transitionState=='closing');}else{return(this.element.classList.contains('transition-opening')||this.element.classList.contains('transition-closing'));}};AppWindow.prototype.suspended=false;AppWindow.prototype.reviveBrowser=function(){if(this.browser){return;}
this.debug(' ...revived!');this.browser=new BrowserFrame(this.browser_config);this.browserContainer.appendChild(this.browser.element);this.iframe=this.browser.element;this.launchTime=Date.now();this.suspended=false;this.element.classList.remove('suspended');this.browser.element.classList.add('hidden');this._setVisible(false);this.publish('resumed');};AppWindow.prototype.destroyBrowser=function(){if(!this.browser){return;}
this.loading=false;this.loaded=false;this.suspended=true;this.element.classList.add('suspended');this.browserContainer.removeChild(this.browser.element);this.browser=null;this.iframe=null;this._sslState='';this.publish('suspended');};AppWindow.prototype.kill=function aw_kill(){if(this._killed){return;}
if(!this.isHomescreen){this._killed=true;}
if(DEBUG||this._DEBUG){this.constructor[this.instanceID]=null;}
if(this.callerWindow){this.callerWindow.calleeWindow=null;this.callerWindow=null;}
if(this.calleeWindow){this.calleeWindow.callerWindow=null;this.calleeWindow=null;}
if(this.frontWindow){this.frontWindow.kill();this.frontWindow=null;}
if(this.nextWindow){this.nextWindow.kill();this.nextWindow=null;}
if(this.attentionWindow){this.attentionWindow.kill();this.attentionWindow=null;}
if(this.isActive()&&this.getBottomMostWindow().isActive()&&!this.isHomescreen){var onClosed=function(){this.element.removeEventListener('_closed',onClosed);this.destroy();}.bind(this);this.element.addEventListener('_closed',onClosed);if(this.previousWindow){this.previousWindow.getBottomMostWindow().open('in-from-left');this.close('out-to-right');}else{if(this.transitionController){setTimeout(this.close.bind(this),this.transitionController.CLOSING_TRANSITION_TIMEOUT);}
this.requestClose();}}else{this.destroy();}
this.publish('terminated');};AppWindow.prototype.isDead=function aw_isDead(){return(this._killed||!this.element);};AppWindow.prototype.destroy=function aw_destroy(){if(this.previousWindow){this.previousWindow.unsetNextWindow();this.previousWindow=null;}
if(this.rearWindow){this.rearWindow.unsetFrontWindow();this.rearWindow=null;}
if(this.parentWindow){this.parentWindow.unsetAttentionWindow();this.parentWindow=null;}
this.publish('willdestroy');this.uninstallSubComponents();this._unregisterEvents();this.destroyBrowser();if(this.element){if(this.element.parentNode){this.element.parentNode.removeChild(this.element);}
this.element=null;}
this.publish('destroyed');};AppWindow.prototype.containerElement=document.getElementById('windows');AppWindow.prototype.view=function aw_view(){let placeholder='';if(this.getPlaceholderColor()){placeholder=`<div class="placeholder">
                <div class="statusbar-placeholder"></div>
                <div class="header-placeholder h1"></div>
                <div class="skbar visible softkey-placeholder"></div>
              </div>`;}
return`<div class="${this.CLASS_LIST}" id="${this.instanceID}"
              transition-state="closed">
              ${placeholder}
              <div class="touch-blocker"></div>
              <div class="browser-container">
               <div class="screenshot-overlay"></div>
              </div>
           </div>`;};var PLACEHOLDER_COLOR_TABLE={'communications':'#153A06','sms':'#153A06','clock':'#381e0d','calendar':'#381e0d','settings':'#20407b'};AppWindow.prototype.getPlaceholderColor=function(){let app=this.origin.replace('app://','').replace('.gaiamobile.org','').replace('.kaiostech.com','');return PLACEHOLDER_COLOR_TABLE[app];};AppWindow.prototype._render=function aw__render(){if(this.element){return;}
this.publish('willrender');var range=document.createRange();var fragment=range.createContextualFragment(this.view());this.browser=new BrowserFrame(this.browser_config,this.iframe);this.element=fragment.getElementById(this.instanceID);this.element.dataset.manifestName=this.manifest?this.manifest.name:'';this.frame=this.element;this.iframe=this.browser.element;this.iframe.dataset.frameType='window';this.iframe.dataset.frameOrigin=this.origin;this.iframe.dataset.url=this.config.url;if(this.config.pageURL){this.iframe.dataset.pageURL=this.config.pageURL;}
if(this.isFullScreen()){this.element.classList.add('fullscreen-app');}
if(this.isBrowser()){this.element.classList.add('browser');}
if(this.isOverlappingStatusbar()){this.element.classList.add('statusbar-overlapped');}else{var preWindowManifest=this.previousWindow&&this.previousWindow.manifest;if(!this.manifest&&preWindowManifest&&preWindowManifest.chrome&&preWindowManifest.chrome.statusbar==='overlap'){this.element.classList.add('statusbar-overlapped');}else{this.element.classList.remove('statusbar-overlapped');}}
this.browserContainer=this.element.querySelector('.browser-container');this.browserContainer.appendChild(this.browser.element);this.containerElement.appendChild(fragment);this.screenshotOverlay=this.element.querySelector('.screenshot-overlay');this.headerPlaceholder=this.element.querySelector('.header-placeholder');this.statusbarPlaceholder=this.element.querySelector('.statusbar-placeholder');if(this.getPlaceholderColor()){this.element.classList.add('placeholder-enabled');this.headerPlaceholder.style.backgroundColor=this.getPlaceholderColor();this.statusbarPlaceholder.style.backgroundColor=this.getPlaceholderColor();this.headerPlaceholder.textContent=this.name;this.browserContainer.classList.add('transparent');}
if(this.config.stayBackground||this.isHomescreen){this.setVisible(false);}
setBrowserProperty(this.browser.element,'canTakeFocus',false);this.publish('rendered');this._rendered=true;setTimeout(this.setFrameBackground.bind(this));};AppWindow.prototype.render=function aw_render(){this._render();this._registerEvents();this.installSubComponents();this.determineRotationDegree();};AppWindow.prototype.isOverlappingStatusbar=function(){return this.manifest&&this.manifest.chrome&&this.manifest.chrome.statusbar==='overlap';};AppWindow.prototype.isBrowser=function aw_isbrowser(){return!this.manifestURL;};AppWindow.prototype.isAtLandingPage=function aw_isatlandingpage(){return(this.config.url.indexOf(window.location.origin)>-1);};AppWindow.prototype.isCertified=function aw_iscertified(){return this.config.manifest&&'certified'===this.config.manifest.type;};AppWindow.prototype.isSearch=function(){return this.manifest&&this.manifest.role==='search';};AppWindow.prototype.isBrowserOrSearch=function(){return(this.isBrowser()||this.isSearch())&&this.config.chrome&&!this.config.chrome.bar;};AppWindow.prototype.isPopupWindow=function(){return(this.CLASS_NAME==='PopupWindow');};AppWindow.prototype.isCursorEnabled=function(){return(this.isBrowser()||(this.manifest&&this.manifest.cursor===true));};AppWindow.prototype.isHostedApp=function(){return this.manifestURL&&this.manifestURL.startsWith('http');};AppWindow.prototype.isProgressBarEnabled=function(){return this.manifest&&this.manifest.progress_bar===true;};AppWindow.prototype.navigate=function aw_isbrowser(url){var needToResetFocus=(document.activeElement===this.browser.element);var appIsSearch=this.manifest&&this.manifest.role==='search';if(!this.isBrowser()&&!appIsSearch){console.warn('Tried to navigate an illegal app window.');return;}
if(this.frontWindow){this.frontWindow.kill();this.frontWindow=null;}
if(!this.isBrowser()){this.manifestURL=null;this.manifest=null;this.element.classList.add('browser');this.reConfig({url:url,title:url,oop:true});this.browserContainer.removeChild(this.browser.element);this.browser=new BrowserFrame(this.browser_config);this.browserContainer.appendChild(this.browser.element);this.iframe=this.browser.element;this.launchTime=Date.now();this._unregisterAudioChannels();this._registerAudioChannels();if(!this.browserNavigationWidgets){this.browserNavigationWidgets=new BrowserNavigationWidgets(this);}
this.appChrome&&this.appChrome.reConfig();}
this.browser.element.src=url;if(needToResetFocus){this.browser.element.focus();}};AppWindow.REGISTERED_EVENTS=['mozbrowserclose','mozbrowsererror','mozbrowservisibilitychange','mozbrowserloadend','mozbrowseractivitydone','mozbrowserloadstart','mozbrowsertitlechange','mozbrowserlocationchange','mozbrowsermetachange','mozbrowsericonchange','mozbrowserasyncscroll','mozbrowsersecuritychange','softkeyregistered','_localized','_swipein','_swipeout','_kill_suspended','_orientationchange','_focus','_blur','_hidewindow','_sheetdisplayed','_sheetsgestureend','_closed'];AppWindow.SUB_COMPONENTS={'transitionController':window.AppTransitionController,'modalDialog':window.AppModalDialog,'valueSelector':window.ValueSelector,'authDialog':window.AppAuthenticationDialog,'contextmenu':window.BrowserContextMenu,'childWindowFactory':window.ChildWindowFactory,'statusbar':window.AppStatusbar};AppWindow.prototype.openAnimation='enlarge';AppWindow.prototype.closeAnimation='reduce';AppWindow.prototype.installSubComponents=function aw_installSubComponents(){this.debug('installing sub components...');for(var componentName in this.constructor.SUB_COMPONENTS){if(this.constructor.SUB_COMPONENTS[componentName]){this[componentName]=new this.constructor.SUB_COMPONENTS[componentName](this);this[componentName].start&&this[componentName].start();}}
var onloadstart=function(){this.browser.element.removeEventListener('mozbrowserloadstart',onloadstart);this._registerAudioChannels();}.bind(this);this.browser.element.addEventListener('mozbrowserloadstart',onloadstart);if(this.isInputMethod){return;}
if(this.manifest){var that=this;that.element.addEventListener('_opened',function onOpened(){that.debug('install appchrome');that.element.removeEventListener('_opened',onOpened);that.appChrome=new AppChrome(that);if(that.inError){that.appChrome.handleEvent({type:'mozbrowsererror'});}
if(that.loading){that.appChrome.handleEvent({type:'mozbrowserloadstart'});that.appChrome.handleEvent({type:'_loading'});}});}else{this.browserNavigationWidgets=new BrowserNavigationWidgets(this);this.appChrome=new AppChrome(this);}};AppWindow.prototype.uninstallSubComponents=function aw_uninstallSubComponents(){for(var componentName in this.constructor.SUB_COMPONENTS){if(this[componentName]&&this[componentName].destroy){this[componentName].destroy();}
this[componentName]=null;}
this._unregisterAudioChannels();if(this.appChrome){this.appChrome.destroy();this.appChrome=null;}
if(this.browserNavigationWidgets){this.browserNavigationWidgets.destroy();this.browserNavigationWidgets=null;}};AppWindow.prototype._registerAudioChannels=function aw_registerAudioChannels(){this.audioChannels=new Map();var audioChannels=this.browser.element.allowedAudioChannels;audioChannels&&audioChannels.forEach((audioChannel)=>{this.audioChannels.set(audioChannel.name,new AudioChannelController(this,audioChannel));this.debug(`Registered ${audioChannel.name} audio channel`);});};AppWindow.prototype._unregisterAudioChannels=function aw__unregisterAudioChannels(){if(this.audioChannels){this.audioChannels.forEach(function(audioChannel){audioChannel.destroy();});this.audioChannels=null;}};AppWindow.prototype._handle__localized=function aw__handle__localized(){if(!this.manifest){return;}
this.name=new ManifestHelper(this.manifest).name;this.shortName=new ManifestHelper(this.manifest).short_name;this.element.dataset.localizedName=this.name;this.publish('namechanged');};AppWindow.prototype._handle__orientationchange=function(evt){if(this.isActive()){this.frontWindow&&this.frontWindow.broadcast('orientationchange');if(!this.isHomescreen){this._resize(evt.detail);return;}else if(Service.currentApp&&Service.currentApp===this){this.lockOrientation();}}
var width=layoutManager.width;var height=layoutManager.getHeightFor(this);this.element.style.width=width+'px';this.element.style.height=height+'px';if(this.isHomescreen){return;}
if(this.width!=width){this.screenshotOverlay.style.visibility='hidden';}else{this.screenshotOverlay.style.visibility='';}};AppWindow.prototype._handle_mozbrowservisibilitychange=function aw__handle_mozbrowservisibilitychange(evt){var type=evt.detail.visible?'foreground':'background';this.publish(type);};AppWindow.prototype._handle_mozbrowseractivitydone=function aw__handle_mozbrowseractivitydone(evt){if(this.isActive()&&this.callerWindow){var caller=this.callerWindow;var callerBottom=caller.getBottomMostWindow();var calleeBottom=this.getBottomMostWindow();caller.calleeWindow=null;this.callerWindow=null;if(callerBottom!==calleeBottom){callerBottom.open('in-from-left');calleeBottom.close('out-to-right');}}};AppWindow.prototype._handle_softkeyregistered=function aw__handle_softkeyregistered(evt){this.setSoftKeys(evt);};AppWindow.prototype._handle_mozbrowserclose=function aw__handle_mozbrowserclose(evt){this.kill();};AppWindow.prototype._handle_mozbrowsererror=function aw__handle_mozbrowsererror(evt){if(evt.detail.type!=='fatal'){this.inError=true;return;}
if(this.origin===FtuLauncher.getFtuOrigin()){this.destroyBrowser();return;}
this.publish('crashed');this.kill(evt);};AppWindow.prototype._handle_mozbrowserloadstart=function aw__handle_mozbrowserloadstart(){this.loading=true;this.inError=false;this._changeState('loading',true);this.publish('loading');};AppWindow.prototype._handle_mozbrowsertitlechange=function aw__handle_handle_mozbrowsertitlechange(evt){this.title=evt.detail;this.publish('titlechange');};AppWindow.prototype._handle_mozbrowserloadend=function aw__handle_mozbrowserloadend(evt){if(!this.loaded){this.publish('loadtime',{time:parseInt(Date.now()-this.launchTime),timestamp:this.timestamp,type:'c',src:this.config.url});}
this.loading=false;this.loaded=true;this.element.classList.add('render');this.browserContainer.classList.add('render');this.element.style.backgroundImage='none';this._changeState('loading',false);this.publish('loaded');var backgroundColor=evt.detail.backgroundColor;this.debug('bgcolor= ',backgroundColor);if(backgroundColor&&backgroundColor.indexOf('rgb(')!=-1&&!this.isHomescreen){this.debug('setting background color..');}
if(this.getPlaceholderColor()){this.browserContainer.classList.add('fade-in');}};AppWindow.prototype._handle_mozbrowserlocationchange=function aw__handle_mozbrowserlocationchange(evt){this.favicons={};this.config.url=evt.detail.url;this.browser.element.dataset.url=evt.detail.url;this.publish('locationchange');this.toggleSpatialNavigation();};AppWindow.prototype._handle_mozbrowsericonchange=function aw__handle_mozbrowsericonchange(evt){var href=evt.detail.href;var sizes=evt.detail.sizes;if(!('favicons'in this)){this.favicons={};}
if(!(href in this.favicons)){this.favicons[href]={sizes:[]};}
if(sizes&&this.favicons[href].sizes.indexOf(sizes)===-1){this.favicons[href].sizes.push(sizes);}
this.publish('iconchange');};AppWindow.prototype._handle_mozbrowserasyncscroll=function aw__handle_mozbrowserasyncscroll(evt){if(this.manifest){return;}
this.scrollPosition=evt.detail.top;this.publish('scroll');};AppWindow.prototype._handle_mozbrowsermetachange=function aw__handle_mozbrowsermetachange(evt){var detail=evt.detail;switch(detail.name){case'theme-color':if(!detail.type){return;}
var color='';if(detail.type!=='removed'){color=detail.content;}
this.themeColor=color;this.publish('themecolorchange');break;case'application-name':if(!this.isBrowser()){return;}
this.updateName(detail.content);this.publish('namechanged');break;}};AppWindow.prototype._registerEvents=function aw__registerEvents(){if(this.element===null){this._dump();return;}
this.constructor.REGISTERED_EVENTS.forEach(function iterator(evt){this.debug('adding '+evt+' event handler ...');this.element.addEventListener(evt,this);},this);if(this.browser&&this.browser.element.getAttribute('remote')!=='true'){window.addEventListener('memorypressure',this);}};AppWindow.prototype._unregisterEvents=function aw__registerEvents(){if(this.element===null){this._dump();return;}
this.constructor.REGISTERED_EVENTS.forEach(function iterator(evt){this.debug('removing '+evt+' event handler ...');if(this.element!=undefined){this.element.removeEventListener(evt,this);}},this);if(this.browser&&this.browser.element.getAttribute('remote')!=='true'){window.removeEventListener('memorypressure',this);}};AppWindow.prototype.handleEvent=function aw_handleEvent(evt){if(this.rearWindow&&evt.type.startsWith('mozbrowser')){evt.stopPropagation();}
this.debug(' Handling '+evt.type+' event...');if(this['_handle_'+evt.type]){this['_handle_'+evt.type](evt);}};AppWindow.prototype._screenshotBlob=undefined;AppWindow.prototype.CLASS_NAME='AppWindow';AppWindow.prototype.debug=function aw_debug(msg){if(DEBUG||this._DEBUG){let m=Array.slice(arguments).concat();console.log('['+this.CLASS_NAME+']'+'['+(this.name||this.origin)+']'+'['+this.instanceID+']'+'['+Service.currentTime()+'] '+
m);if(TRACE){console.trace();}}else if(window.DUMP){DUMP('['+this.CLASS_NAME+']'+'['+(this.name||this.origin)+']'+'['+this.instanceID+']'+'['+Service.currentTime()+'] '+
Array.slice(arguments).concat());}};AppWindow.prototype.forceDebug=function aw_debug(msg){console.log('[Dump:'+this.CLASS_NAME+']'+'['+(this.name||this.origin)+']'+'['+Service.currentTime()+']'+
Array.slice(arguments).concat());};AppWindow.prototype.show=function aw_show(){if(!this.element||!this.element.classList.contains('hidden')){return;}
this.element.classList.remove('hidden');this.publish('shown');};AppWindow.prototype.hide=function aw_hide(){if(!this.element||this.element.classList.contains('hidden')){return;}
this.debug('hidden the entire app window.');this.element.classList.add('hidden');this.publish('hidden');};AppWindow.prototype.queueShow=function aw_queueShow(){this.element.classList.add('will-become-active');this.publish('will-become-active');};AppWindow.prototype.cancelQueuedShow=function aw_cancelQueuedShow(){this.element.classList.remove('will-become-active');};AppWindow.prototype.queueHide=function aw_queueHide(){this.element.classList.add('will-become-inactive');this.publish('will-become-inactive');};AppWindow.prototype.tryWaitForFullRepaint=function onTWFRepaint(callback){if(!callback){return;}
if(this.isHomescreen){setTimeout(callback);return;}
this.debug('trying wait for full repaint by screenshot enforcing..');this.getScreenshot(function(){setTimeout(callback);},1,1,400);};AppWindow.prototype.requestScreenshotURL=function aw__requestScreenshotURL(){if(this.frontWindow){return this.frontWindow.requestScreenshotURL();}
if(!this._screenshotBlob){this.debug('requestScreenshotURL, no _screenshotBlob');return null;}
var screenshotURL=URL.createObjectURL(this._screenshotBlob);setTimeout(function onTimeout(){if(screenshotURL){URL.revokeObjectURL(screenshotURL);screenshotURL=null;}},200);return screenshotURL;};AppWindow.prototype._showScreenshotOverlay=function aw__showScreenshotOverlay(){if(this.frontWindow&&this.frontWindow.isActive()){return this.frontWindow._showScreenshotOverlay();}
if(!this.screenshotOverlay||this.screenshotOverlay.classList.contains('visible')){return Promise.resolve();}
this.screenshotOverlay.classList.add('visible');var screenshotURL=this.requestScreenshotURL();var promise=new Promise((resolve)=>{var image=document.createElement('img');image.onload=function(){resolve();}.bind(this);image.src=screenshotURL;});this.screenshotOverlay.style.backgroundImage=screenshotURL?'url('+screenshotURL+')':'none';this.element.classList.toggle('no-screenshot',!screenshotURL);return promise;};AppWindow.prototype._hideScreenshotOverlay=function aw__hideScreenshotOverlay(){if(this.frontWindow&&this.frontWindow.isActive()){this.frontWindow._hideScreenshotOverlay();}
if(!this.screenshotOverlay||!this.screenshotOverlay.classList.contains('visible')){return;}
this.screenshotOverlay.classList.remove('visible');this.screenshotOverlay.style.backgroundImage='';this.element.classList.remove('no-screenshot');};AppWindow.prototype.getCachedScreenshotBlob=function aw_getCachedScreenshotBlob(){return this._screenshotBlob;};AppWindow.prototype.renewCachedScreenshotBlob=function aw_renewScreenshot(screenshotBlob){this._screenshotBlob=screenshotBlob;};AppWindow.prototype.eventPrefix='app';AppWindow.prototype.publish=function(event,detail){this.broadcast(event,detail);var evt=new CustomEvent(this.eventPrefix+event,{bubbles:true,detail:detail||this});this.debug('publishing external event: '+this.eventPrefix+event+
(detail?JSON.stringify(detail):''));if(this.rearWindow&&this.element){this.element.dispatchEvent(evt);}else{window.dispatchEvent(evt);}
window.dispatchEvent(new CustomEvent('window'+event,{bubbles:true,detail:this}));};AppWindow.prototype.broadcast=function aw_broadcast(event,detail){if(this.element){var internalEvent=new CustomEvent('_'+event,{bubbles:false,detail:detail||this});this.debug('publishing internal event: '+event);this.element.dispatchEvent(internalEvent);}};AppWindow.prototype._handle_memorypressure=function(){if(this.isInputMethod){return;}
if(this.getTopMostWindow()!==Service.query('getTopMostWindow')){this.destroyBrowser();if(this.frontWindow){this.frontWindow.kill();}
if(this.isCallscreenWindow){this.reviveBrowser();}}};AppWindow.prototype.handleHardwareKeyEvent=function(evt){if(this.element&&this['_handle__'+evt.type]){return this['_handle__'+evt.type](evt);}else{return false;}};var OrientationRotationArray=['portrait-primary','portrait-secondary','portrait','landscape-primary','landscape-secondary','landscape','default'];var OrientationRotationTable={'portrait-primary':[0,180,0,90,270,90,OrientationManager.isDefaultPortrait()?0:90],'landscape-primary':[270,90,270,0,180,0,OrientationManager.isDefaultPortrait()?270:0],'portrait-secondary':[180,0,180,270,90,270,OrientationManager.isDefaultPortrait()?180:270],'landscape-secondary':[90,270,90,180,0,180,OrientationManager.isDefaultPortrait()?180:90]};AppWindow.prototype.determineRotationDegree=function aw__determineRotationDegree(){if(!this.manifest){return 0;}
var appOrientation=this.manifest.orientation;var orientation=this.determineOrientation(appOrientation);var table=OrientationRotationTable[OrientationManager.defaultOrientation];var degree=table[OrientationRotationArray.indexOf(orientation)];this.rotatingDegree=degree;if(degree==90||degree==270){this.element.classList.add('perpendicular');}
return degree;};AppWindow.prototype.determineClosingRotationDegree=function aw__determineClosingRotationDegree(){if(!this.manifest){return 0;}
var homeOrientation=OrientationManager.defaultOrientation;var currentOrientation=OrientationManager.fetchCurrentOrientation();this.debug(currentOrientation);var table=OrientationRotationTable[homeOrientation];var degree=table[OrientationRotationArray.indexOf(currentOrientation)];return Math.abs(360-degree)%360;};AppWindow.prototype.isFullScreen=function aw_isFullScreen(){if(typeof(this._fullScreen)!=='undefined'){return this._fullScreen;}
this._fullScreen=!!(this.manifest&&('fullscreen'in this.manifest?this.manifest.fullscreen:false))||this.isFullScreenLayout();return this._fullScreen;};AppWindow.prototype.isFullScreenLayout=function aw_isFullScreenLayout(){if(typeof(this._fullScreenLayout)!=='undefined'){return this._fullScreenLayout;}
this._fullScreenLayout=!!(this.manifest&&('fullscreen_layout'in this.manifest?this.manifest.fullscreen_layout:false));return this._fullScreenLayout;};AppWindow.prototype._defaultOrientation=null;AppWindow.prototype.determineOrientation=function aw_determineOrientation(orientation){if(this._defaultOrientation){return this._defaultOrientation;}else if(!orientation){this._defaultOrientation='default';return this._defaultOrientation;}
if(!Array.isArray(orientation)){orientation=[orientation];}
this._defaultOrientation=orientation[0];return this._defaultOrientation;};AppWindow.prototype._resize=function aw__resize(ignoreKeyboard){var height,width;this.debug('force RESIZE...');if(!ignoreKeyboard&&layoutManager.keyboardEnabled){this.broadcast('withkeyboard');}else{this.broadcast('withoutkeyboard');}
height=layoutManager.getHeightFor(this,ignoreKeyboard);width=layoutManager.width;if(this.element.style.width===width+'px'&&this.element.style.height===height+'px'){return;}
this.width=width;this.height=height;this.element.style.width=width+'px';this.element.style.height=height+'px';this.reviveBrowser();this.resized=true;if(this.screenshotOverlay){this.screenshotOverlay.style.visibility='';}
this.publish('resize');this.debug('W:',width,'H:',height);};AppWindow.prototype.resize=function aw_resize(){if(this.isDead()){return;}
this.debug('request RESIZE...active? ',this.isActive());var bottom=this.getBottomMostWindow();if(!bottom.shouldResize()||this.isTransitioning()){return;}
if(this.frontWindow){this._resize();this.frontWindow.resize();}else{this.debug(' will resize... ');this._resize();}};AppWindow.prototype.getTopMostWindow=function(){var win=this;while(win.frontWindow&&win.frontWindow.isActive()){win=win.frontWindow;}
return win;};AppWindow.prototype.getBottomMostWindow=function(){var win=this;while(win.rearWindow){win=win.rearWindow;}
return win;};AppWindow.prototype.lockOrientation=function(){var manifest=this.manifest||this.config.manifest;var orientation=manifest?(manifest.orientation||OrientationManager.globalOrientation):OrientationManager.globalOrientation;if(orientation){var rv=screen.mozLockOrientation(orientation);if(rv===false){console.warn('screen.mozLockOrientation() returned false for',this.origin,'orientation',orientation);}else{this.debug(' locking screen orientation to '+orientation);}}else{screen.mozUnlockOrientation();this.debug(' Unlocking screen orientation..');}};AppWindow.prototype.setOrientation=function aw_setOrientation(){if(!this.getBottomMostWindow().isActive()){return;}
if(this.frontWindow&&this.frontWindow.isActive()){this.frontWindow.setOrientation();}else{this.lockOrientation();}};AppWindow.prototype.fadeOut=function aw__fadeout(){if(!this.isActive()&&this.element){this.element.classList.add('fadeout');this.debug(' fade out >>>> ');}};AppWindow.prototype.fadeIn=function aw__fadein(){if(this.isActive()){this.element.classList.remove('fadeout');this.debug(' fade in <<<<< ');}};AppWindow.prototype.setCalleeWindow=function aw_setCalleeWindow(callee){this.calleeWindow=callee;callee.callerWindow=this;};AppWindow.prototype.unsetCalleeWindow=function aw_unsetCalleeWindow(){if(this.calleeWindow.callerWindow){this.calleeWindow.callerWindow=null;}
this.calleeWindow=null;};AppWindow.prototype.unsetAttentionWindow=function aw_unsetAttentionWindow(){this.attentionWindow=null;};AppWindow.prototype._changeState=function aw__changeState(type,state){if(this.element){this.element.setAttribute(type+'-state',state.toString());}};AppWindow.prototype.setSoftKeys=function aw_setSoftKeys(evt){this.softkeys=evt.detail;};AppWindow.prototype.getSoftkeys=function aw_getSoftkeys(){return this.softkeys;};AppWindow.addMixin=function AW_addMixin(mixin){for(var prop in mixin){if(mixin.hasOwnProperty(prop)){if(!this.prototype.hasOwnProperty(prop)){this.prototype[prop]=mixin[prop];}}}};AppWindow.prototype.preloadSplash=function aw_preloadSplash(){if(this._splash||this.config.icon){if(this.config.icon){this._splash=this.config.icon;}else{var url=this.config.origin.split('/');var origin=url[0]+'//'+url[2];this._splash=origin+this._splash;}
var img=new Image();img.src=this._splash;}};AppWindow.prototype.SPLASH_ICON_SIZE_TINY=84;AppWindow.prototype.SPLASH_ICON_SIZE_NOT_TINY=90;AppWindow.prototype.getIconForSplash=function aw_getIconForSplash(){var icons=this.manifest?('icons'in this.manifest?this.manifest.icons:null):null;if(!icons){return null;}
var targetedPixelSize=(ScreenLayout.getCurrentLayout('tiny')?this.SPLASH_ICON_SIZE_TINY:this.SPLASH_ICON_SIZE_NOT_TINY)*Math.ceil(window.devicePixelRatio||1);var preferredSize=Number.MAX_VALUE;var max=0;for(var size in icons){size=parseInt(size,10);if(size>max){max=size;}
if(size>=targetedPixelSize&&size<preferredSize){preferredSize=size;}}
if(preferredSize===Number.MAX_VALUE){preferredSize=max;}
this._splash=icons[preferredSize];this.preloadSplash();return icons[preferredSize];};AppWindow.prototype.setFrameBackground=function aw_setFrameBackground(){if(!this.isHomescreen&&!this.loaded&&!this.splashed&&this.element){if(this._splash){this.splashed=true;this.element.style.backgroundImage='url("'+this._splash+'")';var iconCSSSize=(ScreenLayout.getCurrentLayout('tiny')?this.SPLASH_ICON_SIZE_TINY:this.SPLASH_ICON_SIZE_NOT_TINY);this.element.style.backgroundSize=iconCSSSize+'px '+iconCSSSize+'px';}}};AppWindow.prototype.requestOpen=function aw_requestOpen(){this.publish('requestopen');};AppWindow.prototype.requestClose=function aw_requestClose(){this.publish('requestclose');};AppWindow.prototype.modifyURLatBackground=function aw_changeURL(url){if(!this.isActive()){var iframe=this.browser.element;if(iframe.src!==url){iframe.src=url;}}};AppWindow.prototype.ready=function aw_ready(callback){if(!this.element){return;}
if(this._screenshotBlob){this._showScreenshotOverlay();}
this.debug('requesting to open');if(!this.loaded||(this.screenshotOverlay&&this.screenshotOverlay.classList.contains('visible'))){this.debug('loaded yet');setTimeout(callback);return;}else{var invoked=false;this.waitForNextPaint(function(){if(invoked){return;}
invoked=true;setTimeout(callback);});if(this.isHomescreen){if(!Service.query('AttentionWindowManager.hasActiveWindow')){this.setVisible(true);}
return;}
this.tryWaitForFullRepaint(function(){if(invoked){return;}
invoked=true;setTimeout(callback);});}};AppWindow.prototype.open=function aw_open(animation){if(this.transitionController){this.transitionController.requireOpen(animation);}};AppWindow.prototype.close=function aw_close(animation){if(this.transitionController){this.transitionController.requireClose(animation);}};AppWindow.prototype._handle__swipein=function aw_swipein(){this.reviveBrowser();if(this.transitionController){this.transitionController.switchTransitionState('opened');this.publish('opened');}};AppWindow.prototype._handle__swipeout=function aw_swipeout(){if(this.transitionController){this.transitionController.switchTransitionState('closed');this.publish('closed');}};AppWindow.prototype._handle__sheetdisplayed=function aw_sheetdisplayed(){if(this.isActive()){this.debug('no screenshot for active app during sheetdisplayed');return;}
this.debug('showing screenshot during sheetdisplayed');this._showScreenshotOverlay();};AppWindow.prototype._handle__sheetsgestureend=function aw_sgend(){this.debug('hiding screenshot on sheetsgestureend');this._hideScreenshotOverlay();};AppWindow.prototype._handle__closed=function aw_closed(){if(!this.loaded||(Service.isBusyLoading()&&this.getBottomMostWindow().isHomescreen)){return;}
this.getScreenshot();};AppWindow.prototype._handle__kill_suspended=function aw(){if(this.suspended){this.kill();}};AppWindow.prototype.setNextWindow=function aw_setNextWindow(nextWindow){if(this.nextWindow){console.warn('There is already alive child window, killing...',this.nextWindow.instanceID);this.nextWindow.kill();}
this.nextWindow=nextWindow;};AppWindow.prototype.unsetNextWindow=function aw_unsetNextWindow(){if(this.nextWindow){this.nextWindow=null;}};AppWindow.prototype.setFrontWindow=function aw_setFrontWindow(frontWindow){if(this.frontWindow){console.warn('There is already alive child window, killing...',this.frontWindow.instanceID);this.frontWindow.kill();}
this.frontWindow=frontWindow;};AppWindow.prototype.unsetFrontWindow=function aw_unsetFrontWindow(){if(this.frontWindow){this.frontWindow=null;}};AppWindow.prototype.getPrev=function(){var current=this.getActiveWindow();if(current){return current.previousWindow;}else{return null;}};AppWindow.prototype.getNext=function(){var current=this.getActiveWindow();if(current){return current.nextWindow;}else{return null;}};AppWindow.prototype.getActiveWindow=function(){var app=this;while(app){if(app.isActive()){return app;}
app=app.nextWindow;}
return null;};AppWindow.prototype.getRootWindow=function(){var app=this;while(app.previousWindow){app=app.previousWindow;}
return app;};AppWindow.prototype.getLeafWindow=function(){var app=this;while(app.nextWindow){app=app.nextWindow;}
return app;};AppWindow.prototype.getFrameForScreenshot=function(){var top=this.getTopMostWindow();return top.browser?top.browser.element:null;};AppWindow.prototype.isVisible=function(){var bottomMostWindow=this.getBottomMostWindow();return bottomMostWindow.isActive()&&this.isActive();};AppWindow.prototype.transform=function(nameValues){var strFunctions=Object.keys(nameValues).map(function(key){return key+'('+nameValues[key]+')';},this).join(' ');this.applyStyle({MozTransform:strFunctions});};AppWindow.prototype.applyStyle=function(nameValues){var dirty=this._dirtyStyleProperties||(this._dirtyStyleProperties={});var style=this.element.style;for(var property in nameValues){if(undefined===nameValues[property]){delete style[[property]];}else{style[property]=nameValues[property];}
dirty[property]=true;}};AppWindow.prototype.unapplyStyle=function(nameValues){var style=this.element.style;for(var pname in nameValues){style[pname]='';delete style[pname];}};AppWindow.prototype._handle__blur=function(){var win=this;while(win.frontWindow&&win.frontWindow.isActive()){win=win.frontWindow;}
win.blur();};AppWindow.prototype._handle__focus=function(){var win=this;while(win.frontWindow&&win.frontWindow.isActive()){win=win.frontWindow;}
win.focus();};AppWindow.prototype.requestForeground=function aw_requestForeground(){this.publish('requestforeground');};AppWindow.prototype.killable=function(){if(this.attentionWindow||this.isHomescreen){return false;}else{return true;}};AppWindow.prototype.hasPermission=function aw_hasPermission(name){if(typeof(this._hasPermission)!=='undefined'&&this._hasPermission[name]){return this._hasPermission[name];}
var mozPerms=navigator.mozPermissionSettings;if(!mozPerms||!this.manifestURL){return false;}
var value=mozPerms.get(name,this.manifestURL,this.origin,false);if(!this._hasPermission){this._hasPermission={};}
this._hasPermission[name]=(value==='allow');return this._hasPermission[name];};AppWindow.prototype.isHidden=function(){return!this.element||this.element.classList.contains('hidden');};AppWindow.prototype._handle__hidewindow=function(evt){var attention=evt.detail;if(attention.parentWindow&&attention.parentWindow.instanceID===this.instanceID){return;}
if(!this.isActive()){return;}
this.setVisible(false);};AppWindow.prototype._sslState='';AppWindow.prototype._handle_mozbrowsersecuritychange=function aw__handle_mozbrowsersecuritychange(evt){var state=this._sslState=evt.detail.state;this.publish('securitychange',state);};AppWindow.prototype.getSSLState=function(){return this._sslState;};AppWindow.prototype.handleStatusbarTouch=function(evt,barHeight){if(this.statusbar){this.statusbar.handleStatusbarTouch(evt,barHeight);}};AppWindow.prototype._handle__softleft=AppWindow.prototype._handle__softright=AppWindow.prototype._handle__enter=AppWindow.prototype._handle__back=AppWindow.prototype._handle__arrowup=AppWindow.prototype._handle__arrowdown=AppWindow.prototype._handle__1=AppWindow.prototype._handle__2=AppWindow.prototype._handle__3=AppWindow.prototype._handle__5=AppWindow.prototype._handle__8=AppWindow.prototype._handle__e=AppWindow.prototype._handle__i=AppWindow.prototype._handle__o=AppWindow.prototype._handle__r=AppWindow.prototype._handle__w=function(evt){return this.appChrome&&this.appChrome.handleKey(evt.type);};AppWindow.prototype.cacheSpatialNavigationIfNeeded=function(){if(this.hasPermission('spatialnavigation-app-manage')){this._cachedSpatialNavigation=getBrowserProperty(this.browser.element,'spatialNavigationEnabled');}};AppWindow.prototype.toggleSpatialNavigation=function(enabled){this.debug('toggleSpatialNavigation(): enabled = '+enabled);if(this.hasPermission('spatialnavigation-app-manage')){if(Service.query('InputWindowManager.isActivated')&&enabled===false){this.cacheSpatialNavigationIfNeeded();this.setSpatialNavigation(false);return;}
if(Service.query('getTopMostWindow')===this&&!Service.query('locked')){if(this._cachedSpatialNavigation!==undefined){this.setSpatialNavigation(this._cachedSpatialNavigation);this._cachedSpatialNavigation=undefined;}}else{if(this._cachedSpatialNavigation===undefined){this.cacheSpatialNavigationIfNeeded();}
this.setSpatialNavigation(false);}
return;}
if(!this.browser||!this.browser.element||(this.CLASS_NAME!=='AppWindow'&&this.CLASS_NAME!=='PopupWindow'&&this.CLASS_NAME!=='ActivityWindow')||getBrowserProperty(this.browser.element,'spatialNavigationEnabled')===undefined){this.debug('toggleSpatialNavigation(): early return, incorrect window');return;}
if((typeof enabled!=='undefined')&&!enabled){this.debug('toggleSpatialNavigation(): '+'set spatial navigation false immediately');this.setSpatialNavigation(false);return;}
var visibleForScreenReader=!((this.element&&this.element.getAttribute('aria-hidden')==='true')||this.browser.element.getAttribute('aria-hidden')==='true');var value;if(visibleForScreenReader&&this.isCursorEnabled()&&!(this._optionMenu&&this._optionMenu.isActive())&&!(this._permissionDialog&&this._permissionDialog.isActive())&&!(this.authDialog&&this.authDialog.isVisible())&&!Service.query('InputWindowManager.isActivated')&&!Service.query('SoundManager.isActivated')&&Service.query('getTopMostWindow')===this&&Service.query('getTopMostUI').name===this.HIERARCHY_MANAGER){value=true;this.debug('toggleSpatialNavigation(): set --> true');}else{value=false;this.debug('toggleSpatialNavigation(): set --> false');}
this.setSpatialNavigation(value);};AppWindow.prototype.toggleScrollNavigation=function(enabled){this.debug('toggleScrollNavigation(): enabled = '+enabled);if(!this.browser||!this.browser.element||(this.CLASS_NAME!=='AppWindow'&&this.CLASS_NAME!=='PopupWindow')||getBrowserProperty(this.browser.element,'spatialNavigationEnabled')===undefined||getBrowserProperty(this.browser.element,'touchPanningSimulationEnabled')===undefined){this.debug('toggleScrollNavigation(): early return, incorrect window');return;}
if((typeof enabled!=='undefined')&&!enabled){this.debug('toggleScrollNavigation(): '+'set scroll navigation false immediately');this.setScrollNavigation(false);return;}
var visibleForScreenReader=!((this.element&&this.element.getAttribute('aria-hidden')==='true')||this.browser.element.getAttribute('aria-hidden')==='true');var value;if(visibleForScreenReader&&this.isCursorEnabled()&&!(this._optionMenu&&this._optionMenu.isActive())&&!(this._permissionDialog&&this._permissionDialog.isActive())&&!(this.authDialog&&this.authDialog.isVisible())&&!Service.query('InputWindowManager.isActivated')&&!Service.query('SoundManager.isActivated')){value=true;this.debug('toggleScrollNavigation(): set --> true');}else{value=false;this.debug('toggleScrollNavigation(): set --> false');}
this.setScrollNavigation(value);};exports.AppWindow=AppWindow;}(window));