
(function(exports){'use strict';var _=navigator.mozL10n.get;var BrowserWindowNavigator=function BrowserWindowNavigator(appChrome){this.appChrome=appChrome;this.app=appChrome.app;this.app.browser.element.addEventListener('focus',this);this.app.browser.element.addEventListener('blur',this);this.app.browser.element.addEventListener('mozbrowserlocationchange',this);window.addEventListener('mozfullscreenchange',this);window.addEventListener('fullscreenchange',this);this.app.element.addEventListener('_opened',this);this.app.element.addEventListener('_closing',this);this.app.element.addEventListener('_loading',this);this.app.element.addEventListener('_loaded',this);this.app.element.addEventListener('_value-selector-hidden',this);this.app.element.addEventListener('_scrollerModeChanged',this);};BrowserWindowNavigator.prototype={backEnabled:false,forwardEnabled:false,_DEBUG:false,saveFocus:function bwm_saveFocus(){if(this.isFocusInScope()){this._lastFocus=document.activeElement;}},restoreFocus:function bwm_restoreFocus(){if(this._lastFocus){this._lastFocus.focus();this._lastFocus=undefined;}},_focusOnApp:function bwm_focusOnApp(){this.app.publish('focus');},handleEvent:function bwm_handleEvent(evt){switch(evt.type){case'mozfullscreenchange':case'fullscreenchange':this.handleFullScreenChange(evt);break;case'_value-selector-hidden':this.setSoftkey(document.mozFullScreen);break;case'_opened':this.restoreFocus();break;case'_closing':this.saveFocus();break;case'_loading':case'_loaded':this.updateOptionMenu();break;case'_scrollerModeChanged':this.setSoftkey(document.mozFullScreen);break;case'focus':case'blur':this.handleFocusOrBlur(evt);break;case'mozbrowserlocationchange':this.updateGoBackForwardOptions();break;}},handleFocusOrBlur:function bwm_handleFocusOrBlur(evt){var targetOnApp=evt.target===this.app.browser.element;if(!targetOnApp){return;}
if(evt.type==='focus'&&this.app.isBrowser()){this.setSoftkey(document.mozFullScreen);}},handleKey:function bwm_handleKey(key){var handled=false;switch(key){case'softleft':if(this.app&&this.app.isBrowser()){handled=true;if(this.isFocusOnApp()&&!document.mozFullScreen){window.dispatchEvent(new CustomEvent('global-search-request'));if(this.app&&this.app.browserNavigationWidgets){this.app.browserNavigationWidgets.setNavigationMode('spatial');}
if(this.app){this.app.publish('focusonurlbar');}}else{document.mozCancelFullScreen();}}
break;case'softright':if(this.app&&this.app.isBrowser()){if(this.isFocusInScope()){if(!document.mozFullScreen){this.showOptionMenu();handled=true;}else{if(!Service.query('hasVolumeKey')){this.requestVolume('show');handled=true;}}}}
break;case'1':case'i':case'w':if(this.app&&this.app.isBrowser()){this.app.browserNavigationWidgets&&this.app.browserNavigationWidgets.zoom('out');handled=true;}
break;case'3':case'o':case'r':if(this.app&&this.app.isBrowser()){this.app.browserNavigationWidgets&&this.app.browserNavigationWidgets.zoom('in');handled=true;}
break;case'2':case'e':if(this.app&&this.app.isBrowser()){this.app.browserNavigationWidgets&&this.app.browserNavigationWidgets.setNavigationMode('toggle');handled=true;}
break;case'5':if(this.app&&this.app.isBrowser()){this.app.browserNavigationWidgets&&this.app.browserNavigationWidgets.scroll('top');handled=true;}
break;case'8':if(this.app&&this.app.isBrowser()){this.app.browserNavigationWidgets&&this.app.browserNavigationWidgets.scroll('down');handled=true;}
break;case'arrowup':if(this.app&&this.app.isBrowser()){this.requestVolume('up');handled=true;}
break;case'arrowdown':if(this.app&&this.app.isBrowser()){this.requestVolume('down');handled=true;}
break;case'enter':if(this.app&&this.app.isBrowser()&&getBrowserProperty(this.app.browser.element,'touchPanningSimulationEnabled')){this.app.browserNavigationWidgets&&this.app.browserNavigationWidgets.setNavigationMode('spatial');handled=true;}
break;case'home':if(document.mozFullScreen){document.mozCancelFullScreen();handled=true;break;}
this.app.canGoBack((result)=>{if(this.app.isCursorEnabled()&&!this.app.isBrowser()){if(result){this.app.back();}else if(Service.query('isLowMemoryDevice')){this.app.kill();}else{appWindowManager.display(null,null,null,'home');}
return;}
if(result&&this.app.isBrowser()){this.app.back();this.hasLeaveAppToast=false;}else{let toastl10n='pressBackAgainToMinimizeBrowser';if(Service.query('isLowMemoryDevice')){toastl10n='pressBackAgainToQuitBrowser';}
if(!this.hasLeaveAppToast){Service.request('SystemToaster:show',{textL10n:toastl10n});this.hasLeaveAppToast=true;}else{if(Service.query('isFtuRunning')){let origin=FtuLauncher.getFtuOrigin();appWindowManager.display(appWindowManager.getApp(origin));}else if(Service.query('isLowMemoryDevice')){this.app.kill();}else if(!this.app.origin.includes('app://')){this.app.kill();}else{appWindowManager.display(null,null,null,'home');}}}});break;}
return handled;},goToBrowserTop:function(){var activityReq=new MozActivity({name:'browser-top',data:{}});activityReq.onerror=(e)=>{var msg='[BrowserWindowNavigator] open "browser-top" activity '+'error:'+activityReq.error.name;this.debug(msg);};activityReq.onsuccess=(e)=>{var msg='[BrowserWindowNavigator] open "browser-top" activity '+'onsuccess';this.debug(msg);setTimeout(()=>{this.app.kill();});};},requestVolume:function(option){switch(option){case'show':if(navigator.volumeManager){navigator.volumeManager.requestShow();}
break;case'up':if(Service.query('SoundManager.isActivated')&&!Service.query('hasVolumeKey')){if(navigator.volumeManager){navigator.volumeManager.requestUp();}}
break;case'down':if(Service.query('SoundManager.isActivated')&&!Service.query('hasVolumeKey')){if(navigator.volumeManager){navigator.volumeManager.requestDown();}}
break;default:return;}},buildOptionMenu:function(){var menu=[{id:this.app.loading?'stop':'refresh',label:this.app.loading?_('stop'):_('refresh'),callback:this.refresh.bind(this)},{id:'goToTopSites',label:_('goToTopSites'),callback:this.goToBrowserTop.bind(this)},{id:'minimizeBrowser',label:_('minimizeBrowser'),callback:function(){appWindowManager.display(null,null,null,'home');}}];if(!Service.query('hasVolumeKey')){menu.splice(0,0,{id:'volume',label:_('volume'),callback:this.requestVolume.bind(this,'show')});}
if(this.forwardEnabled){menu.splice(1,0,{id:'goForward',label:_('goForward'),callback:this.app.forward.bind(this.app)});}
if(this.backEnabled){menu.splice(1,0,{id:'goBack',label:_('goBack'),callback:this.app.back.bind(this.app)});}
if(this.app&&!this.app.loading){menu.splice(menu.findIndex((element)=>{return element.id==='goToTopSites';})+1,0,{id:'pinToTopSites',label:_('pinToTopSites'),callback:this.pinToTopSites.bind(this)},{id:'pinToAppsMenu',label:_('pinToAppsMenu'),callback:this.pinToAppsMenu.bind(this)});}
if(this.app&&this.app.contextmenu){if(this.app.contextmenu.hasAction('save-image')){menu.splice(menu.length-1,0,{id:'downloadImage',label:_('downloadImage'),callback:this.app.contextmenu.getActionCallback('save-image').bind(this.app.contextmenu)||function(){}});}}
return menu;},showOptionMenu:function(){Service.request('showOptionMenu',{options:this.buildOptionMenu()},this.app);},updateOptionMenu:function(){this.app._optionMenu&&this.app._optionMenu.setState({options:this.buildOptionMenu()});},updateGoBackForwardOptions:function(){this.app.canGoForward((result)=>{if(!this.appChrome.hasNavigation()){this.forwardEnabled=false;}else{this.forwardEnabled=(result)?true:false;}
this.updateOptionMenu();});this.app.canGoBack((result)=>{if(!this.appChrome.hasNavigation()){this.backEnabled=false;}else{this.backEnabled=(result)?true:false;}
this.updateOptionMenu();});},handleFullScreenChange:function(){if(this.isFocusOnApp()){this.setSoftkey(document.mozFullScreen);}},setSoftkey:function(isFullScreen){if(!this.app||!this.app.isBrowser()){return;}
var centerIcon=this.app.browser.element&&getBrowserProperty(this.app.browser.element,'touchPanningSimulationEnabled')?'icon=browser-softkey-cursor':'select';if(!isFullScreen){Service.request('SoftKeyStore:register',{left:'search',center:centerIcon,right:'options'},this.app.browser.element);}else{var rskText=Service.query('hasVolumeKey')?'':'volume';Service.request('SoftKeyStore:register',{left:'exit',center:centerIcon,right:rskText},this.app.browser.element);}},isFocusOnApp:function bwm_isFocusOnApp(){if(this.app&&this.app.browser&&this.app.browser.element){return document.activeElement===this.app.browser.element;}else{return false;}},isFocusInScope:function bwm_isFocusInScope(){return(this.isFocusOnApp()||(this.app&&this.app._modalDialog&&!this.app._modalDialog.element.hidden));},refresh:function(){this.app.loading?this.app.stop():this.app.reload();},pinToTopSites:function(){places.getPlace(this.app.config.url).then((place)=>{browserPinSitesDataStore.savePinSite({url:place.url,title:place.title,screenshot:place.screenshot,tile:place.tile,icons:place.icons}).then((result)=>{switch(result){case'pinCompleted':Service.request('SystemToaster:show',{textL10n:'pinSiteCompletely'});break;case'wasPinnedBefore':Service.request('SystemToaster:show',{textL10n:'siteWasPinnedBefore'});break;case'pinnedSitesOverLimit':Service.request('SystemToaster:show',{textL10n:'pinnedSitesOverLimit'});break;default:this.debug('pin site failed with other reason: '+result);break;}});});},pinToAppsMenu:function(){this.appChrome.addBookmark().then(()=>{Service.request('SystemToaster:show',{textL10n:'pinSiteToAppsMenuCompletely'});},(reason)=>{Service.request('SystemToaster:show',{textL10n:'siteWasPinnedToAppsMenuBefore'});});},destroy:function(){this.app.element.removeEventListener('_opened',this);this.app.element.removeEventListener('_closing',this);this.app.element.removeEventListener('_loading',this);this.app.element.removeEventListener('_loaded',this);this.app.element.removeEventListener('_value-selector-hidden',this);this.app.element.removeEventListener('_scrollerModeChanged',this);this.app.browser.element.removeEventListener('focus',this);this.app.browser.element.removeEventListener('blur',this);this.app.browser.element.removeEventListener('mozbrowserlocationchange',this);window.removeEventListener('mozfullscreenchange',this);window.removeEventListener('fullscreenchange',this);this.app=null;this.appChrome=null;this._lastFocus=null;},debug:function(msg){if(this._DEBUG){console.log('[BrowserWindowNavigator]: '+msg);}}};exports.BrowserWindowNavigator=BrowserWindowNavigator;}(window));