'use strict';(function(exports){var DialerAgent=function DialerAgent(){var telephony=navigator.mozTelephony;if(!telephony){return;}
this._telephony=telephony;this._callEndPromptTime=100;this._started=false;this._shouldVibrate=true;this._alerting=false;this._vibrateInterval=null;this._readOut=false;this._readOutData='';var player=new Audio();this._player=player;player.mozAudioChannelType='ringer';player.preload='metadata';player.loop=true;this.freeCallscreenWindow=this.freeCallscreenWindow.bind(this);this.makeFakeNotification=this.makeFakeNotification.bind(this);this._storage=navigator.getDeviceStorage('sdcard');var conn=window.navigator.mozMobileConnections&&window.navigator.mozMobileConnections[0];if(conn&&conn.voice&&conn.voice.network&&conn.voice.network.mcc){SimplePhoneMatcher.mcc=conn.voice.network.mcc;}};DialerAgent.prototype.name='DialerAgent';DialerAgent.prototype.freeCallscreenWindow=function(){var conCall=this._telephony.conferenceGroup;var numOpenLines=this._telephony.calls.length+
((conCall.state||conCall.calls.length)?1:0);if(this._callscreenWindow&&(numOpenLines===0)&&!this._callscreenWindow.isVisible()){this._callscreenWindow.free();}};DialerAgent.prototype.start=function da_start(){if(!this._telephony){return;}
if(this._started){throw'Instance should not be start()\'ed twice.';}
this._started=true;SettingsListener.observe('dialer.ringtone','',function(value){this.defaultRingtone=value;}.bind(this));VersionHelper.getVersionInfo().then(function(versionInfo){if(versionInfo.isUpgrade()){LazyLoader.load('js/tone_upgrader.js',function(){toneUpgrader.perform('ringtone');});}},function(err){console.error('VersionHelper failed to lookup version settings.');});SettingsListener.observe('vibration.enabled',true,function(value){this._shouldVibrate=!!value;if(!this._shouldVibrate&&this._vibrateInterval){window.clearInterval(this._vibrateInterval);}
else if(this._alerting){this._vibrateInterval=window.setInterval(function vibrate(){navigator.vibrate([1000]);},2000);navigator.vibrate([1000]);}}.bind(this));this._telephony.addEventListener('callschanged',this);if(this._telephony.conferenceGroup){this._telephony.conferenceGroup.addEventListener('callschanged',this);this._telephony.conferenceGroup.addEventListener('statechange',()=>{var conCall=this._telephony.conferenceGroup;if(conCall&&(conCall.calls.length||conCall.state)){return;}
var calls=this._telephony.calls;if(!calls.length){Service.request('cancelActivityMenu');setTimeout(()=>{if(!this._telephony.calls.length){this._callscreenWindow.closeWindow();}},this._callEndPromptTime);}});}
window.addEventListener('sleep',this);window.addEventListener('stop-alert',this);window.addEventListener('mute-alert',this);window.addEventListener('iac-callscreencomms',this);window.addEventListener('homescreenloaded',this);window.addEventListener('end-call',this);this._callscreenWindow=new CallscreenWindow();this._callscreenWindow.hide();if(applications&&applications.ready){this.makeFakeNotification();}else{window.addEventListener('applicationready',this.makeFakeNotification);}
Service.registerState('onCall',this);Service.registerState('isAlerting',this);Service.register('freeCallscreenWindow',this);return this;};DialerAgent.prototype.makeFakeNotification=function(){window.removeEventListener('applicationready',this.makeFakeNotification);this._callscreenWindow&&this._callscreenWindow.makeNotification();};DialerAgent.prototype.stop=function da_stop(){if(!this._started){return;}
this._started=false;this._telephony.removeEventListener('callschanged',this);if(this._telephony.conferenceGroup){this._telephony.conferenceGroup.removeEventListener('callschanged',this);}
window.removeEventListener('sleep',this);window.removeEventListener('end-call',this);};DialerAgent.prototype.onCall=function(){return this._telephony.calls.length||this._telephony.conferenceGroup.state;}
DialerAgent.prototype.handleEvent=function da_handleEvent(evt){if(evt.type==='homescreenloaded'){this._callscreenWindow&&this._callscreenWindow.ensure();return;}
var calls=this._telephony.calls;if(evt.type==='end-call'){if(calls.length!==0){if(calls[calls.length-1].state==='incoming'){calls[calls.length-1].hangUp();}}
return;}
if(evt.type==='mute-alert'){this._muteAlerting();return;}
if(evt.type==='stop-alert'||evt.type==='sleep'){this._stopAlerting();return;}
if(evt.type==='iac-callscreencomms'){this._handleIac(evt);return;}
if(evt.type!=='callschanged'){return;}
if(calls.length!==0){var index=calls.length-1;if(calls[index].state==='incoming'||calls[index].state==='connected'&&calls[index].secondId&&calls[index].secondId.number){var incomingCall=calls[index];var number=incomingCall.secondId?incomingCall.secondId.number:incomingCall.id.number;if(Service.query('remoteLockEnabled')){incomingCall.hangUp();return;}
var options={filterBy:['number'],filterValue:number,filterOp:'fuzzyMatch'};var request=navigator.mozContacts.findBlockedNumbers(options);request.onsuccess=()=>{if(request.result&&request.result.length){incomingCall.hangUp();}else{this.handleCallschanged();}};request.onerror=()=>{this.handleCallschanged();};}else{this.handleCallschanged();}}else{this.handleCallschanged();}};DialerAgent.prototype.handleCallschanged=function da_handleCallschanged(){Service.request('cancelActivityMenu');if(this._telephony.conferenceGroup&&(this._telephony.conferenceGroup.calls.length||this._telephony.conferenceGroup.state)){if(this._telephony.conferenceGroup.calls.length===0){let detail={connected:false};this._incall=false;let inCallEvt=new CustomEvent('incall',{detail:detail});window.ExternalScreenManager.send(inCallEvt);}
let index=navigator.mozTelephony.conferenceGroup.calls[0].serviceId;Service.request('updateWifiCallState',{onCall:'onCall',index:index});return;}
var calls=this._telephony.calls;var self=this;if(calls.length===0){let detail={connected:false};this._incall=false;let inCallEvt=new CustomEvent('incall',{detail:detail});window.ExternalScreenManager.send(inCallEvt);Service.request('updateWifiCallState',{onCall:''});setTimeout(function(){if(self._telephony.calls.length===0){if(self._callscreenWindow.isActive()){self._callscreenWindow.closeWindow();}else{window.addEventListener('attentionopened',function close(evt){if(evt.detail.isCallscreenWindow){if(self._telephony.calls.length===0){self._callscreenWindow.closeWindow();}
window.removeEventListener('attentionopened',close);}});}}},this._callEndPromptTime);return;}
Service.request('updateWifiCallState',{onCall:'onCall',index:calls[0].serviceId});if(!this._callscreenWindow.isVisible()||calls.length!==0){this.openCallscreen();}
if(calls[0].state=='alerting'||calls[0].state=='dialing'||calls[0].state=='connected')
{let number=calls[0].secondId?calls[0].secondId.number:calls[0].id.number;this._incall=true;dump('incall handle calls change number:'+number);Contacts.quickFindByNumber(number,(contact)=>{dump('incall handle calls change contact = '+JSON.stringify(contact));let detail={connected:this._incall,number:number};if(contact&&contact.name){detail.name=contact.name[0];}
let inCallEvt=new CustomEvent('incall',{detail:detail});window.ExternalScreenManager.send(inCallEvt);});}
let anyCall=calls[0];anyCall.addEventListener('statechange',function anyCallStateChange(){if(self._telephony.calls.length&&self._telephony.calls[0].state==='connected'){anyCall.removeEventListener('statechange',anyCallStateChange);let number=self._telephony.calls[0].secondId?self._telephony.calls[0].secondId.number:self._telephony.calls[0].id.number;self._incall=true;dump('incall handle calls state change number:'+number);Contacts.quickFindByNumber(number,function lookup(contact){dump('incall handle calls state change contact = '+JSON.stringify(contact));let detail={connected:self._incall,number:number};if(contact&&contact.name){detail.name=contact.name[0];}
let inCallEvt=new CustomEvent('incall',{detail:detail});window.ExternalScreenManager.send(inCallEvt);});}});if(this._alerting||calls[0].state!=='incoming'){return;}
var incomingCall=calls[0];var isTa4request=navigator.engmodeExtension.getPropertyValue('TA-4-request');var ta_sw=navigator.engmodeExtension.getPropertyValue('ro.product.sw_type');console.log('isTa4request='+isTa4request);console.log('ta_sw='+ta_sw);if(incomingCall){if(isTa4request==='true'&&ta_sw==='TA'){console.log('try to answer the call.');incomingCall.answer('voice');}}
var readoutEnable=Service.query('Accessibility.screenReaderEnabled');self._startAlerting(incomingCall);var number=incomingCall.secondId?incomingCall.secondId.number:incomingCall.id.number;var detail={alert:true,number:number};this._readOutData='';Contacts.quickFindByNumber(number,function lookup(contact){dump('ggg handle calls change contact = '+JSON.stringify(contact));if(contact&&contact.name){detail.name=contact.name[0];self._readOutData+=detail.name;}
else{self._readOutData+=detail.number;}
self._readOutData+=navigator.mozL10n.get('incoming');var incomingEvt=new CustomEvent('incomingcall',{detail:detail});window.ExternalScreenManager.send(incomingEvt);});if(calls.length===1&&calls[0].state==='incoming'&&readoutEnable){this.readOutInfo(true);}
incomingCall.addEventListener('statechange',function callStateChange(){if(self._telephony.calls.length&&self._telephony.calls[0].state==='incoming'){return;}
incomingCall.removeEventListener('statechange',callStateChange);self._stopAlerting();if(readoutEnable){self.readOutInfo(false);}
var incomingEvt=new CustomEvent('incomingcall',{detail:{alert:false}});window.ExternalScreenManager.send(incomingEvt);});};DialerAgent.prototype.readOutInfo=function da_readOutInfo(readorNot){if(this._readOut===readorNot){return;}
this._readOut=readorNot;if(this._readOut){setTimeout(()=>{Service.request('Accessibility:speak',this._readOutData,null,{repeat:true});},1200);}
else{Service.request('Accessibility:cancelSpeech');}};DialerAgent.prototype._startAlerting=function da_startAlerting(call){this._alerting=true;this._unmuteAlerting();if('vibrate'in navigator&&this._shouldVibrate){this._vibrateInterval=window.setInterval(function vibrate(){navigator.vibrate([1000]);},2000);navigator.vibrate([1000]);}
if(!this._player.pause){this._player.paused();}
var number=call.secondId?call.secondId.number:call.id.number;Contacts.quickFindByNumber(number,(contact)=>{if(contact&&contact.ringtone){this._getRingtone(contact.ringtone).then((blob)=>{this._player.src=URL.createObjectURL(blob);if(this._alerting){this._player.play();}}).catch(()=>{this._playDefault();});}else{this._playDefault();}});};DialerAgent.prototype._getRingtone=function da_getRingtone(ringtone){return new Promise((resolve,reject)=>{if(ringtone.indexOf('builtin:ringtone/')>-1){var base='/shared/resources/media/ringtones/';var url=base+ringtone.split('/')[1]+'.ogg';var xhr=new XMLHttpRequest();xhr.open('GET',url);xhr.overrideMimeType('audio/ogg');xhr.responseType='blob';xhr.send();xhr.onload=function(){resolve(xhr.response);};xhr.onerror=function(){var err=new Error('Could not read sound file: '+url+' (status: '+xhr.status+')');console.error(err);reject(err);};}else{var req=this._storage.get(ringtone);req.onsuccess=function(){resolve(this.result.slice());};req.onerror=function(){console.warn('Unable to get the ringtone: '+ringtone);reject(false);};}});};DialerAgent.prototype._playDefault=function da_playDefault(){if(this.defaultRingtone&&this._alerting){var settingsUrl=new SettingsURL();var ringtoneName=this.defaultRingtone.name;var playRingtone=()=>{this._player.src=settingsUrl.set(this.defaultRingtone);this._player.play();};playRingtone();}};DialerAgent.prototype.isAlerting=function(first_argument){return this._alerting;};DialerAgent.prototype._stopAlerting=function da_stopAlerting(){var player=this._player;this._alerting=false;if(player&&!player.paused){player.pause();player.currentTime=0;}
window.clearInterval(this._vibrateInterval);};DialerAgent.prototype._muteAlerting=function da_muteAlerting(){this._player.volume=0;window.clearInterval(this._vibrateInterval);};DialerAgent.prototype._unmuteAlerting=function da_muteAlerting(){this._player.volume=1;};DialerAgent.prototype._handleIac=function da__handleIac(evt){if(evt.detail.type==='rec-insufficient-storage'){navigator.mozSettings.createLock().get('device.storage.writable.name').then(result=>{var location=result['device.storage.writable.name'];var title='sd-card-full-title';var body='sd-card-full-body';if(location==='sdcard'){title='phone-storage-full-title';body='phone-storage-full-body';}
Service.request('DialogService:show',{header:title,content:body,ok:'settings',onOk:function(){var activityReq=new MozActivity({name:'configure',data:{target:'device',section:'mediaStorage'}});},type:'confirm'});});}};DialerAgent.prototype.openCallscreen=function(){if(this._callscreenWindow){this._callscreenWindow.ensure();this._callscreenWindow.show();this._callscreenWindow.requestOpen();}};exports.DialerAgent=DialerAgent;}(window));