'use strict';(function(exports){var VisibilityManager=function VisibilityManager(){this._normalAudioChannelActive=false;this._deviceLockedTimer=0;this.overlayEvents=['lockscreen-appopened','lockscreen-request-unlock','attentionwindowmanager-deactivated','attentionopened','mozChromeEvent','appclosing','homescreenopened','searchrequestforeground','apprequestforeground','lockscreen-apprequestforeground','secure-apprequestforeground','homescreenrequestforeground','visibleaudiochannelchanged'];};VisibilityManager.prototype.DEBUG=false;VisibilityManager.prototype.CLASS_NAME='VisibilityManager';VisibilityManager.prototype.start=function start(){this.overlayEvents.forEach(function overlayEventIterator(event){window.addEventListener(event,this);},this);};VisibilityManager.prototype.handleEvent=function vm_handleEvent(evt){this.debug('handling '+evt.type+' event..');switch(evt.type){case'searchrequestforeground':case'homescreenrequestforeground':case'lockscreen-apprequestforeground':case'secure-apprequestforeground':if(!attentionWindowManager.hasActiveWindow()){evt.detail.setVisible(true);}
break;case'apprequestforeground':if(!Service.query('locked')&&!attentionWindowManager.hasActiveWindow()){evt.detail.setVisible(true);}
break;case'appclosing':case'homescreenopened':this._normalAudioChannelActive=false;break;case'attentionwindowmanager-deactivated':if(window.Service.query('locked')){return;}
this.publish('showwindow',{type:evt.type});this._resetDeviceLockedTimer();break;case'lockscreen-request-unlock':var detail=evt.detail,activity=null,notificationId=null;if(detail){activity=detail.activity;notificationId=detail.notificationId;}
if(!attentionWindowManager.hasActiveWindow()){this.publish('showwindow',{activity:activity,notificationId:notificationId});}
this._resetDeviceLockedTimer();break;case'lockscreen-appopened':this.debug('locking, hide the whole windows',this._normalAudioChannelActive);if(!this._normalAudioChannelActive){this.publish('hidewindow',{screenshoting:false,type:evt.type});}
this._resetDeviceLockedTimer();break;case'attentionopened':if(!Service.query('locked')){this.publish('hidewindow',{type:evt.type});}
break;case'visibleaudiochannelchanged':this._resetDeviceLockedTimer();if(this._normalAudioChannelActive&&evt.detail.channel!=='normal'&&Service.query('locked')){this._deviceLockedTimer=setTimeout(function setVisibility(){if(window.Service.query('locked')){this.publish('hidewindow',{screenshoting:false,type:evt.type});}}.bind(this),3000);}
this._normalAudioChannelActive=(evt.detail.channel==='normal');this.debug('Normal AudioChannel changes to ',evt.detail.channel,this._normalAudioChannelActive);break;}};VisibilityManager.prototype._resetDeviceLockedTimer=function vm_resetDeviceLockedTimer(){if(this._deviceLockedTimer){clearTimeout(this._deviceLockedTimer);this._deviceLockedTimer=0;}};VisibilityManager.prototype.publish=function vm_publish(eventName,detail){this.debug('publishing: ',eventName);var evt=new CustomEvent(eventName,{detail:detail});window.dispatchEvent(evt);};VisibilityManager.prototype.debug=function vm_debug(){if(this.DEBUG){console.log('['+this.CLASS_NAME+']'+'['+Service.currentTime()+']'+
Array.slice(arguments).concat());}};exports.VisibilityManager=VisibilityManager;}(window));