'use strict';let Share={data:null,songTitle:null,subtitle:null,saveAsDefault:false,activity:null,hasSaveTone:false,defaultTone:null,init:function(){this.setDefaultRingTone();if(document.location.hash==='#activity'){this.initActivity();}else{this.initWindowOpened();}
window.addEventListener('keydown',(e)=>{if(e.key==='Backspace'){e.preventDefault();this.cancelHandel();}});window.addEventListener('largetextenabledchanged',()=>{document.body.classList.toggle('large-text',navigator.largeTextEnabled);});document.body.classList.toggle('large-text',navigator.largeTextEnabled);},setDefaultRingTone(){const getTone=window.navigator.mozSettings.createLock().get('dialer.ringtone.name');getTone.onsuccess=()=>{this.defaultTone=getTone.result['dialer.ringtone.name'];}},initActivity:function(){navigator.mozSetMessageHandler('activity',(activity)=>{function flatten(arr){return arr&&arr.length?arr[0]:null;}
this.activity=activity;this.data=activity.source.data;this.data.blob=flatten(this.data.blobs);this.data.metadata=flatten(this.data.metadata);this.data.name=flatten(this.data.filenames);this.showShareView();});},initWindowOpened:function(){window.addEventListener('visibilitychange',()=>{if(document.hidden){window.close();}});window.addEventListener('message',(event)=>{if(event.origin!==window.location.origin){console.error('Couldn\'t recieve message: origins don\'t match',event.origin,window.location.origin);return;}
this.data=event.data;this.event=event;this.showShareView();});},showShareView:function(){navigator.mozL10n.once(()=>{this.setTitle();this.setPicture();this.setPreview();this.createOptions();window.dispatchEvent(new Event("createRingtoneReady"));});},setTitle:function(){if(this.data.metadata&&this.data.metadata.title){this.songTitle=this.data.metadata.title;}else if(this.data.name){this.songTitle=this.data.name;}else{this.songTitle=navigator.mozL10n.get('ringtone-untitled');}
if(this.data.metadata&&this.data.metadata.artist){this.subtitle=this.data.metadata.artist;}
document.getElementById('songtitle').textContent=this.songTitle;document.getElementById('artist').textContent=this.subtitle;},setPicture:function(){const picture=document.getElementById('picture');let url='/style/images/albumart.jpg';if(this.data.metadata&&this.data.metadata.picture){if(!this.data.metadata.artist){document.getElementById('artist').textContent='\u00a0';document.querySelector('.small').hidden=true;}else{document.querySelector('.title').classList.remove('title');}
try{url=URL.createObjectURL(this.data.metadata.picture);}catch(e){console.error('Couldn\'t set picture:',e);}}
picture.hidden=false;picture.style.backgroundImage='url('+url+')';},setPreview:function(){const preview=document.getElementById('preview');preview.src=URL.createObjectURL(this.data.blob);preview.addEventListener('error',()=>{this.showDialog('play-error-title','play-error-desc',this.errorHandle.bind(this));});},createOptions:function(){const params={menuClassName:'menu-button',items:[{name:'Cancel',l10nId:'create-cancel',priority:1,method:this.cancelHandel.bind(this)},{name:'Select',l10nId:'create-select',priority:2,method:this.checkControl.bind(this)},{name:'Save',l10nId:'create-save',priority:3,method:this.saveTone.bind(this)}]};const option=new SoftkeyPanel(params);option.show();},checkControl:function(){if(document.getElementById('softkeyPanel')){const checkBox=document.getElementById('default-switch');const key='create-'+(checkBox.checked?'select':'deselect');const checkIcon=document.getElementById('software-keys-center');checkIcon.textContent=navigator.mozL10n.get(key);this.saveAsDefault=!checkBox.checked;}},toneTooLargeHandle:function(){if(this.activity){this.activity.postError('tone file is too large');}else{window.close();}},errorHandle:function(){if(this.activity){this.activity.postError('add tone error');}else{window.close();}},cancelHandel:function(){if(this.activity){this.activity.postError('cancel add tone');}else{window.close();}},savedSuccessHandle:function(details,toneName){let l10nID=null;if(details.hasSaved){l10nID=details.setAsDefault?'file-set-as-default-ringtone':'file-has-saved';}else{l10nID=details.setAsDefault?'file-set-as-default-ringtone':'file-saved';}
Toaster.showToast({title:toneName,messageL10nId:l10nID});if(this.activity){this.activity.postResult({command:'save',details});}else{if(!details.hasSaved){this.event.source.postMessage({command:'save',details},this.event.origin);}
window.close();}},saveTone:function(){if(this.hasSaveTone){return;}
this.hasSaveTone=true;if(this.data.blob.size>=10485760){Toaster.showToast({title:this.songTitle,messageL10nId:'file-size-is-too-large'});this.toneTooLargeHandle();return;}
document.getElementById('saving-overlay').hidden=false;const info={name:this.songTitle,subtitle:this.subtitle,blob:this.data.blob,filename:this.data.blob.name};let toneName="";window.customRingtones.add(info).then((result)=>{const tone=result.tone;toneName=tone.name;if(result.hasSaved){if(toneName===this.defaultTone||(toneName!==this.defaultTone&&!this.saveAsDefault)){return{toneID:tone.id,setAsDefault:false,hasSaved:true}}else if(toneName!==this.defaultTone&&this.saveAsDefault){return window.systemTones.set('ringtone',tone).then(()=>{return{toneID:tone.id,setAsDefault:true,hasSaved:true}});}}else{if(this.saveAsDefault){return window.systemTones.set('ringtone',tone).then(()=>{return{toneID:tone.id,setAsDefault:true,hasSaved:false}});}
return{toneID:tone.id,setAsDefault:false,hasSaved:false}}}).then((details)=>{this.savedSuccessHandle(details,toneName);this.hasSaveTone=false;},(error)=>{console.log('Error saving ringtone',error);this.showDialog('save-error-title','save-error-desc',this.errorHandle.bind(this));this.hasSaveTone=false;});},showDialog:function(title,message,okCallback){const dialogConfig={title:{id:title,args:{}},body:{id:message,args:{}},accept:{l10nId:'ok',priority:2,callback:()=>{dialog.destroy();okCallback();}}};const dialog=new ConfirmDialogHelper(dialogConfig);dialog.show(document.getElementById('app-confirmation-dialog'));}};Share.init();