
var BluetoothHelper=function(){var profiles={'HFP':0x111E,'A2DP':0x110D};var _bluetooth=window.navigator.mozBluetooth;var _isReady=false;var _callbacks=[];var _adapter=null;var _oldAdapter=null;var _v2=true;var _ready=function(callback){if(!callback||!_bluetooth){return;}
if(_isReady){callback();}else{_callbacks.push(callback);}};var _handleRequest=function(request,callback,errorcb){request.onsuccess=function(){if(callback){callback(request.result);}};request.onerror=function(){console.log('Error handling bluetooth request');if(errorcb){errorcb();}};};var _processCallbacks=function(){if(_adapter){_isReady=true;_callbacks.forEach(function(callback){callback();});_callbacks=[];}else{console.log('BluetoothHelper(): connot get default adapter yet');}};var _fetchAdapterV2=function(){_bluetooth.onattributechanged=function onManagerAttributeChanged(evt){for(var i in evt.attrs){switch(evt.attrs[i]){case'defaultAdapter':console.log('defaultAdapter changed. address:',_bluetooth.defaultAdapter.address);_adapter=_bluetooth.defaultAdapter;_processCallbacks();break;default:break;}}};_adapter=_bluetooth.defaultAdapter;if(_adapter){_processCallbacks();}};var _fetchAdapter=function(){var req=_bluetooth.getDefaultAdapter();if(req){req.onsuccess=function(){if(_adapter){_oldAdapter=_adapter;}
_isReady=true;_adapter=req.result;if(_oldAdapter&&_oldAdapter.onpairedstatuschanged){_adapter.onpairedstatuschanged=_oldAdapter.onpairedstatuschanged;}
_callbacks.forEach(function(callback){callback();});_callbacks=[];};req.onerror=function(){console.log('BluetoothHelper(): connot get default adapter!!!');};}};var _getAdapter=function(){if(_v2){_fetchAdapterV2();}else{_fetchAdapter();}};var _resetAdapter=function(){if(_adapter){_oldAdapter=_adapter;}
_isReady=false;_adapter=null;};var _decodeUrlSchemePrefix=function(code){switch(code){case 0:return'http://www.';case 1:return'https://www.';case 2:return'http://';case 3:return'https://';}
return'';}
var _decodeEddystoneUrl=function(code){switch(code){case 0:return'.com/';case 1:return'.org/';case 2:return'.edu/';case 3:return'.net/';case 4:return'.info/';case 5:return'.biz/';case 6:return'.gov/';case 7:return'.com';case 8:return'.org';case 9:return'.edu';case 10:return'.net';case 11:return'.info';case 12:return'.biz';case 13:return'.gov';}
return String.fromCharCode(code);}
var _calcDistance=function(rssi,txPower){const signalLoss=41;const coefficient1=0.42093;const coefficient2=6.9476;const coefficient3=0.54992;let ratio=rssi*1.0/(txPower-signalLoss);if(ratio<1.0){return Math.pow(ratio,10);}else{return coefficient1*Math.pow(ratio,coefficient2)+coefficient3;}}
var _findEddystoneUrl=function(adData){const boundary=31-3;let offset=0;while(offset<boundary){let len=adData[offset];if(len===0){console.log('length of AD structure should not be 0.');return null;}
let i=offset;let adType=adData[++i];if(adType===22){if(adData[++i]!==170||adData[++i]!==254){return null;}
if(adData[++i]!==16){return null;}
return offset;}
offset+=len;}
return null;}
var _parseEddystoneUrl=function(scanRecord,rssi){if(!(scanRecord instanceof ArrayBuffer)){return null;}
var uint8Array=new Uint8Array(scanRecord);let pos=_findEddystoneUrl(uint8Array);if(pos===null){return null;}
let dataLen=uint8Array[pos];let txPower=uint8Array[pos+5];let urlScheme=uint8Array[pos+6];let signedTxPower=txPower<<24>>24;let dist=_calcDistance(rssi,signedTxPower);const metaLen=7;uint8Array=uint8Array.slice(pos+metaLen,pos+dataLen+1);let eddystoneUrl=_decodeUrlSchemePrefix(urlScheme);uint8Array.forEach(function(element){eddystoneUrl+=_decodeEddystoneUrl(element);});return{url:eddystoneUrl,distance:dist};}
if(_bluetooth){if(typeof(_bluetooth.onattributechanged)==='undefined'){_v2=false;}
if(_v2){_bluetooth.onadapteradded=function onAdapterAdded(evt){_getAdapter();};}else{_bluetooth.addEventListener('enabled',_getAdapter);_bluetooth.addEventListener('adapteradded',_getAdapter);_bluetooth.addEventListener('disabled',_resetAdapter);}
_getAdapter();}
return{profiles:profiles,answerWaitingCall:function(){_ready(function(){_adapter.answerWaitingCall();});},ignoreWaitingCall:function(){_ready(function(){_adapter.ignoreWaitingCall();});},toggleCalls:function(){_ready(function(){_adapter.toggleCalls();});},getConnectedDevicesByProfile:function(profileID,cb,errorcb){_ready(function(){_handleRequest(_adapter.getConnectedDevices(profileID),cb,errorcb);});},connectSco:function(cb){_ready(function(){_handleRequest(_adapter.connectSco(),cb);});},disconnectSco:function(cb){_ready(function(){_handleRequest(_adapter.disconnectSco(),cb);});},getPairedDevices:function(cb){_ready(function(){_handleRequest(_adapter.getPairedDevices(),cb);});},getAddress:function(cb){if(_v2){console.log('getAddress function is deprecated');return;}
_ready(function(){var address=_adapter.address;cb(address);});},setPairingConfirmation:function(address,confirmed){if(_v2){console.log('setPairingConfirmation API is deprecated');return;}
_ready(function(){_adapter.setPairingConfirmation(address,confirmed);});},setPinCode:function(address,pincode){if(_v2){console.log('setPairingConfirmation API is deprecated');return;}
_ready(function(){_adapter.setPinCode(address,pincode);});},setPasskey:function(address,key){if(_v2){console.log('setPairingConfirmation API is deprecated');return;}
_ready(function(){_adapter.setPasskey(address,key);});},isScoConnected:function(cb,errorcb){_ready(function(){_handleRequest(_adapter.isScoConnected(),cb,errorcb);});},sendMediaMetaData:function(metadata,cb,errorcb){_ready(function(){_handleRequest(_adapter.sendMediaMetaData(metadata),cb,errorcb);});},sendMediaPlayStatus:function(metadata,cb,errorcb){_ready(function(){_handleRequest(_adapter.sendMediaPlayStatus(metadata),cb,errorcb);});},set onhfpstatuschanged(callback){_ready(function(){_adapter.onhfpstatuschanged=callback;});},set onscostatuschanged(callback){_ready(function(){_adapter.onscostatuschanged=callback;});},set ona2dpstatuschanged(callback){_ready(function(){_adapter.ona2dpstatuschanged=callback;});},set onrequestmediaplaystatus(callback){_ready(function(){_adapter.onrequestmediaplaystatus=callback;});},set onpairedstatuschanged(callback){if(_v2){console.log('onpairedstatuschanged API is deprecated');return;}
_ready(function(){_adapter.onpairedstatuschanged=callback;});},v2:_v2,enable:function(){if(_v2){_ready(function(){_adapter.enable();});}else{console.log('enable is not support in v1 API!');}},disable:function(){if(_v2){_ready(function(){_adapter.disable();});}else{console.log('disable is not support in v1 API!');}},parseEddystoneUrl:function(scanRecord,rssi){if(_v2){return _parseEddystoneUrl(scanRecord,rssi);}else{console.log('parseEddystoneUrl is not support in v1 API!');}}};};