
function ThumbnailList(groupClass,container){if(!groupClass||!container){throw new Error('group class or container cannot be null or undefined');}
this.thumbnailMap={};this.groupMap={};this.itemGroups=[];this.count=0;this.groupClass=groupClass;this.container=container;navigator.mozL10n.ready(this.localize.bind(this));}
ThumbnailList.prototype.addItem=function(item){if(!item){return null;}
if(this.thumbnailMap[item.name]){return this.thumbnailMap[item.name];}
var _this=this;function createItemGroup(item,before){var group=new _this.groupClass(item);_this.container.insertBefore(group.htmlNode,before?before.htmlNode:null);return group;}
function getItemGroup(item){var groupID=_this.groupClass.getGroupID(item);var i;for(i=0;i<_this.itemGroups.length;i++){if(_this.itemGroups[i].groupID===groupID){return _this.itemGroups[i];}else if(_this.groupClass.compareGroupID(_this.itemGroups[i].groupID,groupID)<0){break;}}
var createdGroup=createItemGroup(item,_this.itemGroups[i]);_this.itemGroups.splice(i,0,createdGroup);return createdGroup;}
var group=getItemGroup(item);var thumbnail=group.addItem(item);this.groupMap[item.name]=group;this.thumbnailMap[item.name]=thumbnail;this.count++;thumbnail.addTapListener(thumbnailClickHandler);return thumbnail;};ThumbnailList.prototype.removeItem=function(filename){if(!this.thumbnailMap[filename]){return;}
var group=this.groupMap[filename];group.removeItem(this.thumbnailMap[filename]);if(!group.getCount()){this.container.removeChild(group.htmlNode);this.itemGroups.splice(this.itemGroups.indexOf(group),1);}
this.count--;delete this.groupMap[filename];delete this.thumbnailMap[filename];};ThumbnailList.prototype.reset=function(){for(var name in this.thumbnailMap){this.groupMap[name].removeItem(this.thumbnailMap[name]);}
this.container.innerHTML='';this.thumbnailMap={};this.itemGroups=[];this.groupMap={};this.count=0;};ThumbnailList.prototype.isPickMode=function(){return this.container.classList.contains('pick');};ThumbnailList.prototype.setPickMode=function(pick){if(pick){this.container.classList.add('pick');}else{this.container.classList.remove('pick');}};ThumbnailList.prototype.isSelectMode=function(){return this.container.classList.contains('select');};ThumbnailList.prototype.setSelectMode=function(select){if(select){this.container.classList.add('select');}else{this.container.classList.remove('select');}};ThumbnailList.prototype.updateAllThumbnailTitles=function(){var self=this;if(this.pendingTitleTextUpdate&&this.pendingTitleTextUpdate.length){this.pendingTitleTextUpdate.length=0;}
var thumbnailKeys=Object.keys(this.thumbnailMap);this.pendingTitleTextUpdate=thumbnailKeys;setTimeout(updateNextThumbnailBatch);function updateNextThumbnailBatch(){for(var i=0;i<10;i++){if(thumbnailKeys.length===0){return;}
var nextKey=thumbnailKeys.shift();self.thumbnailMap[nextKey].updateTitleText();}
setTimeout(updateNextThumbnailBatch);}};ThumbnailList.prototype.findNextThumbnail=function(filename){var currentGroup=this.groupMap[filename];if(!currentGroup){return this.itemGroups.length?this.itemGroups[0].thumbnails[0]:null;}
var currentThumbnail=this.thumbnailMap[filename];var idx;if(currentGroup.thumbnails.length===1){idx=this.itemGroups.indexOf(currentGroup);if(idx===0){if(this.itemGroups.length>1){currentThumbnail=this.itemGroups[1].thumbnails[0];}else{currentThumbnail=null;}}else{var thumbnails=this.itemGroups[idx-1].thumbnails;currentThumbnail=thumbnails[thumbnails.length-1];}}else{idx=currentGroup.thumbnails.indexOf(currentThumbnail);if(idx===0){currentThumbnail=currentGroup.thumbnails[1];}else{currentThumbnail=currentGroup.thumbnails[idx-1];}}
return currentThumbnail;};ThumbnailList.prototype.nextThumbnail=function(filename){var currentGroup=this.groupMap[filename];if(!currentGroup){return this.itemGroups[0].thumbnails[0];}
var currentThumbnail=this.thumbnailMap[filename];var idx=this.itemGroups.indexOf(currentGroup);if(currentGroup.thumbnails.length===1){if(idx===0){if(this.itemGroups.length>1){currentThumbnail=this.itemGroups[1].thumbnails[0];}else{currentThumbnail=this.itemGroups[0].thumbnails[0];}}else{if(idx===this.itemGroups.length-1){currentThumbnail=this.itemGroups[0].thumbnails[0];}else{var thumbnails=this.itemGroups[idx+1].thumbnails;currentThumbnail=thumbnails[0];}}}else{var index=currentGroup.thumbnails.indexOf(currentThumbnail);if(index===(currentGroup.thumbnails.length-1)){if(!this.itemGroups[idx+1]){currentThumbnail=this.itemGroups[0].thumbnails[0];}else{var thumbnails=this.itemGroups[idx+1].thumbnails;currentThumbnail=thumbnails[0];}}else{currentThumbnail=currentGroup.thumbnails[index+1];}}
return currentThumbnail;};ThumbnailList.prototype.prevThumbnail=function(filename){var currentGroup=this.groupMap[filename];if(!currentGroup){return this.itemGroups[0].thumbnails[0];}
var currentThumbnail=this.thumbnailMap[filename];var idx;idx=this.itemGroups.indexOf(currentGroup);if(currentGroup.thumbnails.length===1){if(idx===0){if(this.itemGroups.length>1){var thumbnails=this.itemGroups[this.itemGroups.length-1].thumbnails;currentThumbnail=thumbnails[thumbnails.length-1];}else{currentThumbnail=this.itemGroups[0].thumbnails[0];}}else{var thumbnails=this.itemGroups[idx-1].thumbnails;currentThumbnail=thumbnails[thumbnails.length-1];}}else{var index=currentGroup.thumbnails.indexOf(currentThumbnail);if(index===0){if(idx===0){var thumbnails=this.itemGroups[this.itemGroups.length-1].thumbnails;}else{var thumbnails=this.itemGroups[idx-1].thumbnails;}
currentThumbnail=thumbnails[thumbnails.length-1];}else{currentThumbnail=currentGroup.thumbnails[index-1];}}
return currentThumbnail;};ThumbnailList.prototype.localize=function(){this.itemGroups.forEach(function(group){group.localize();});};