
let MODE_LIST=1;let MODE_LIST_FROM_SUBLIST=2;let MODE_SUBLIST=3;let MODE_SUBLIST_LIST=4;let MODE_SUBLIST_CREATE_LIST=5;let MODE_PLAYER=6;let MODE_SEARCH_FROM_LIST=7;let MODE_SEARCH_FROM_LIST_PICK=8;let MODE_SEARCH_FROM_SUBLIST=9;let MODE_PICKER=10;var ModeManager={_modeStack:[],playerTitle:null,dropedMode:null,withRefresh:false,get currentMode(){return this._modeStack[this._modeStack.length-1];},get prevMode(){return this._modeStack.length>=2?this._modeStack[this._modeStack.length-2]:undefined;},start:function(mode,callback){this._modeStack=[mode];this._updateMode(callback);},clearState:function(){if(ListView.needReset){ListView.resetUI();}
if(ListView.mode==='edit'){ListView.toggleAll('deselectAll');ListView.mode='normal';}
if(SubListView.mode==='edit'){ListView.toggleAll('deselectAll');SubListView.mode='normal';}
if(toPlaylist.state){toPlaylist.state=false;toPlaylist.source=[];}},push:function(mode,callback){this.dropedMode=null;this._modeStack.push(mode);this._updateMode(callback);},pop:function(){if(this._modeStack.length<=1){return;}
OptionMenu.isActive()&&OptionMenu.cancel();this.dropedMode=this._modeStack.pop();this._updateMode();},updateTitle:function(){if(this.currentMode===MODE_LIST||this.currentMode===MODE_SEARCH_FROM_LIST){TitleBar.updateById('music');}},playWithInit:function lv_playWithInit(isStatic){if(dongleState.canPlayByDongle){const handle=musicdb.enumerate('metadata.title',null,'next',(record)=>{if(record){musicdb.cancelEnumeration(handle);playByDongle({source:[record],focusIndex:0});}});return;}
ModeManager.push(MODE_PLAYER,function(){if(PlayerView.dataSource.length===0){musicdb.getAll(function _getAll(dataArray){dataArray.sort((a,b)=>{if(a.metadata.title<b.metadata.title){return-1;}else{return 1;}});App.knownSongs=dataArray;PlayerView.setSourceType(TYPE_MIX);PlayerView.dataSource=App.knownSongs;PlayerView.setDBInfo({key:'metadata.title',range:null,direction:'next',option:'title',count:App.knownSongs.length});PlayerView.play(0,null,isStatic);});}}.bind(this));},updatePlayingIcon:function(){if(this.currentMode===MODE_LIST){ListView.updatePlayingIcon();}else if(this.currentMode===MODE_SUBLIST){SubListView.updatePlayingIcon(SubListView.isInMyPlaylist);}},_updateMode:function(callback){var mode=this.currentMode;var playerLoaded=(typeof PlayerView!=='undefined');let themeMeta=document.querySelector('meta[name="theme-color"]');this.updateTitle();if(mode===MODE_LIST&&TabBar.option==='title'&&this.dropedMode&&!this.withRefresh){ListView.isNeedLoadNearestNodes();}
let modeClasses=['list-mode','list-from-sublist-mode','sublist-mode','sublist-list-mode','sublist-create-list-mode','player-mode','search-from-list-mode','search-from-list-pick-mode','search-from-sublist-mode','picker-mode'];modeClasses.forEach(function resetMode(targetClass){document.body.classList.remove(targetClass);});document.body.classList.add(modeClasses[mode-1]);if(App.pendingPick){document.body.classList.add('picker-mode');ListView.view.focus();}
if(mode===MODE_PLAYER){themeMeta.setAttribute('content','');var player=document.getElementById('views-player');player.classList.remove('hidden');if(!OptionMenu.isActive()){setTimeout(()=>{if(document.hidden){SoftKeyStore.store(SoftKeyStore.registeredDOMMap.get(player).keys);}else{player.focus();}});}
LazyLoader.load('js/ui/views/player_view.js',function(){if(!playerLoaded){PlayerView.init();PlayerView.setOptions(App.playerSettings);}
if(callback){callback();}}.bind(this));}else{if(themeMeta.getAttribute('content')===''){themeMeta.setAttribute('content','rgb(255, 255, 255)');}
switch(mode){case MODE_LIST:ListView.searchInput.value='';SearchView.searchListView.classList.add('hidden');ListView.anchor.classList.remove('hidden');SubListView.playlistL10nId=null;SubListView.listNeedReset=false;SubListView.needReset=false;SubListView.listIndex=null;SubListView.indexBeforeDelete=0;if(TabBar.option==='title'){if(this.dropedMode){ListView.updatePlayingIcon();this.dropedMode===MODE_SEARCH_FROM_LIST&&ListView.updateSelectedItems();}}
setTimeout(()=>{if(!ListView.isFocusingInput||TabBar.option==='playlist'){ListView.view.focus();}});break;case MODE_LIST_FROM_SUBLIST:ListView.searchInput.value='';SearchView.searchListView.classList.add('hidden');ListView.anchor.classList.remove('hidden');ListView.updatePlayingIcon();ListView.updateSelectedItems();setTimeout(()=>{if(!ListView.isFocusingInput){ListView.view.focus();}});break;case MODE_SUBLIST:SubListView.searchInput.value='';SubListView.view.classList.remove('hidden');SubListView.viewController(MODE_SUBLIST,SubListView.playlistL10nId?{playlistL10nId:SubListView.playlistL10nId}:undefined);SubListView.updatePlayingIcon(SubListView.isInMyPlaylist);SubListView.updateSelectedItems();setTimeout(()=>{if(!SubListView.batchUpdateTimer&&!SubListView.isFocusingInput){SubListView.view.focus();}});break;case MODE_SUBLIST_LIST:SubListView.view.classList.remove('hidden');SubListView.viewController(MODE_SUBLIST_LIST,{playlistL10nId:PLAYLIST});SubListView.updateSelectedItems();setTimeout(()=>SubListView.view.focus());break;case MODE_SUBLIST_CREATE_LIST:SubListView.view.classList.remove('hidden');SubListView.viewController(MODE_SUBLIST_CREATE_LIST);setTimeout(()=>SubListView.view.focus());break;case MODE_SEARCH_FROM_LIST:case MODE_SEARCH_FROM_LIST_PICK:SearchView.searchListView.classList.remove('hidden');ListView.anchor.classList.add('hidden');setTimeout(()=>{if(!ListView.isFocusingInput||TabBar.option==='playlist'){ListView.view.focus();}});break;case MODE_SEARCH_FROM_SUBLIST:SubListView.viewController(MODE_SEARCH_FROM_SUBLIST,SubListView.playlistL10nId?{playlistL10nId:SubListView.playlistL10nId}:undefined);setTimeout(()=>{if(!SubListView.isFocusingInput){SubListView.view.focus();}});break;}
document.getElementById('views-player').classList.add('hidden');if(callback){callback();}}},};