'use strict';var thumbnails=$('thumbnails');var FilesStore;var fullscreenView;var cropView;var listProgressBar=$('list-progress');let isEnable=true;const LAYOUT_MODE={list:'thumbnailListView',select:'thumbnailSelectView',fullscreen:'fullscreenView',edit:'editView',pick:'pickView',crop:'cropView',favorite:'favoriteView',dongle:'donglePick'};var editedPhotoIndex;var selectedFileNames=[];var selectedFileNamesToBlobs={};var hasSaved=false;var editSaveCallback=null;var lock;let gaiaProgress=$('gaia-progress');navigator.mozL10n.once(function showBody(){initActivity();window.dispatchEvent(new CustomEvent('moz-chrome-dom-loaded'));init();Dongle.initDongleManager();checkHasDmWallpaper();Settings.loadSettingDB();});function init(){document.body.classList.toggle('large-text',navigator.largeTextEnabled);Gallery.init();window.onresize=resizeHandler;window.performance.mark('navigationInteractive');window.dispatchEvent(new CustomEvent('moz-chrome-interactive'));initDB();if(isEnable&&picking){initHtml();isEnable=false;}}
function initActivity(){navigator.mozSetMessageHandler('activity',(a)=>{switch(a.source.name){case'browse':if(currentView===LAYOUT_MODE.fullscreen){setView(LAYOUT_MODE.list);}
break;case'pick':if('dongle/image'===a.source.data.type){Dongle.initDongle(a);}else{LazyLoader.load(['js/pick.js','js/pickeditor.js'],()=>{Pick.start(a);});}
break;}});}
function initDB(){photodb=new MediaDB('pictures',metadataParserWrapper,{version:2,autoscan:false,batchHoldTime:2000,batchSize:3});window.performance.mark('navigationLoaded');var loaded=false;function metadataParserWrapper(file,onsuccess,onerror,bigFile){Gallery.isAddFile=true;if(loaded){metadataParser(file,onsuccess,onerror,bigFile);return;};LazyLoader.load(['js/metadata_scripts.js','shared/js/media/crop_resize_rotate.js'],function(){loaded=true;metadataParser(file,onsuccess,onerror,bigFile);});}
photodb.onupgrading=function(evt){Overlay.show('upgrade');};photodb.onunavailable=function(event){if(picking){if(!Dongle.isDonglePick){Pick.restart();}}else{setView(LAYOUT_MODE.list);}
var why=event.detail;if(why===MediaDB.NOCARD)
Overlay.show('nocard');else if(why===MediaDB.UNMOUNTED)
Overlay.show('pluggedin');};photodb.onenumerable=function(){Gallery.creatingThumbnails=true;initThumbnails();};photodb.onready=function(){if(Overlay.current==='nocard'||Overlay.current==='pluggedin'||Overlay.current==='upgrade'){Overlay.hide();};};photodb.onscanstart=function onscanstart(){if(!lock){lock=navigator.requestWakeLock('screen');}};photodb.onscanend=function onscanend(e){lock.unlock();lock=null;if(!e.detail.containsData&&FilesStore.getLength()===0){Overlay.show('emptygallery');if(e.detail.firstscan){visuallyLoadedHandle();}}
if(e.detail.firstscan&&e.detail.containsData){clearTimeout(Gallery.hideProgressBarTimeout);Gallery.hideProgressBarTimeout=setTimeout(()=>{if(picking&&FilesStore.getLength()===0){Overlay.show('emptygallery');}
ProgressBar.hideGaiaProgress();Gallery.creatingThumbnails=false;},300);}else{ProgressBar.hideGaiaProgress();Gallery.creatingThumbnails=false;}
window.performance.mark('fullyLoaded');};photodb.onopenMediaDBFail=function(){window.close();};photodb.onnomediastorage=function onnomediastorage(e){setView(LAYOUT_MODE.list);Overlay.show('emptygallery');};photodb.oncardremoved=function oncardremoved(){if(picking&&!Dongle.isDonglePick){Pick.cancel();return;}
setView(LAYOUT_MODE.list);};photodb.oncreated=function(event){event.detail.forEach(fileCreated);};photodb.ondeleted=function(event){if(window.performance.getEntriesByName('gallery-delete-start','mark').length>0){window.performance.mark('gallery-delete-end');window.performance.measure('performance-gallery-delete','gallery-delete-start','gallery-delete-end');window.performance.clearMeasures('performance-gallery-delete');window.performance.clearMarks('gallery-delete-start');window.performance.clearMarks('gallery-delete-end');}
forEachFileInfo(event.detail,fileDeleted,()=>{needNav();});};function forEachFileInfo(fileinfos,func,alldone){var last=fileinfos.length;for(var i in fileinfos){if(isNaN(i))continue;last--;func(fileinfos[i],0===last?alldone:undefined);}}
window.addEventListener('visibilitychange',function(e){if(!document.hidden){photodb.scan();shareProcess=false;}else{photodb.stopScan();}});doNotScanInBackgroundHack(photodb);}
function initThumbnails(){if(isInitThumbnail){photodb.scan();return;}
isInitThumbnail=true;thumbnailList=new ThumbnailList(ThumbnailDateGroup,thumbnails);FilesStore=new FilesStore();startTheFirstEnumerate();}
function startTheFirstEnumerate(){Gallery.enumerateState=photodb.enumerate('date',null,'prev',enumerateHandle);}
function startOthersEnumerate(){Gallery.enumerateState=photodb.advancedEnumerate('date',null,'prev',Gallery.enumerateIndex,enumerateHandle);}
function enumerateHandle(file){if(file){Gallery.enumerateIndex++;if(!picking||!file.metadata.largeSize){Gallery.enumerateFiles.push(file);}
if(Gallery.enumerateFiles.length===BATCH_SIZE){photodb.cancelEnumeration(Gallery.enumerateState);createEnumerateFilesThumbnail();}}else{Gallery.enumerateEnd=true;createEnumerateFilesThumbnail();}}
function createEnumerateFilesThumbnail(){Gallery.enumerateFiles.forEach((file)=>{const thumbnailItem=thumbnailList.addItem(file);FilesStore.setFileInfo(file);if(currentView===LAYOUT_MODE.select){selectViewCreateNewImg(thumbnailItem);}
if(Favorite.isFavoriteList){Favorite.favoriteViewCreateImg(thumbnailItem);}});Favorite.refreshBackground(0);needNav();if(Gallery.isFirstScreen){Gallery.isFirstScreen=false;if(0!==Gallery.enumerateFiles.length){Overlay.hide();if(picking){if(!Dongle.isDonglePick){setView(LAYOUT_MODE.pick);SoftkeyManager.initPickRelateButton();}}else{setView(LAYOUT_MODE.list);}
visuallyLoadedHandle();}}
Gallery.enumerateFiles=[];if(Gallery.enumerateEnd){if(photodb.state===MediaDB.READY){photodb.scan();}else{photodb.addEventListener('ready',photodb.scan.bind(photodb));}}else{if(currentView===LAYOUT_MODE.fullscreen){clearTimeout(Gallery.enumerateTimeout);photodb.cancelEnumeration(Gallery.enumerateState);}else{Gallery.enumerateTimeout=setTimeout(()=>{if(photodb.state===MediaDB.READY){startOthersEnumerate();}else{photodb.addEventListener('ready',startOthersEnumerate);}},200);}}}
function visuallyLoadedHandle(){if(Gallery.visuallyLoaded){return;}
Gallery.visuallyLoaded=true;window.performance.mark('visuallyLoaded');window.performance.mark('contentInteractive');window.dispatchEvent(new CustomEvent('moz-app-visually-complete'));window.dispatchEvent(new CustomEvent('moz-content-interactive'));pendingInit(()=>{thumbnails.addEventListener('click',thumbnailClickHandler);if(isEnable){initHtml();isEnable=false;}});}
function needNav(){if(currentView!==LAYOUT_MODE.fullscreen){thumbnails.classList.add(NEED_NAV);};}
function getInsertPosition(fileInfo,findEleIndex){var fileGroup=thumbnailList.findGroup(fileInfo);if(!fileGroup){console.error('file group does not exist in thumbnail List',fileInfo.name);return-1;}
var index=0;if(findEleIndex)
index=fileGroup.getDisplayPos(fileInfo);else
index=fileGroup.getIndex(fileInfo);if(index<0){console.error(fileInfo.name,' does not exist in thumbnail list');return-1;}
for(var n=0;n<thumbnailList.itemGroups.length;n++){if(thumbnailList.itemGroups[n].groupID===fileGroup.groupID){break;}
index+=thumbnailList.itemGroups[n].getCount();}
return index;}
function fileDeleted(filename,navCallback){if(Gallery.deleteSelected){return;}
let deleteImage=thumbnails.querySelector('[data-filename="'+filename+'"]');if(!deleteImage){return;};let index=selectedFileNames.indexOf(filename);if(index!==-1){delete selectedFileNamesToBlobs[filename];selectedFileNames.splice(index,1);updateMultipleCount(selectedFileNames.length);};let oldFileKey=Gallery.numberFilesKeyCounter(deleteImage.firstElementChild);FilesStore.currentFileKey=oldFileKey;if(currentView===LAYOUT_MODE.fullscreen){let oldFocus=Gallery.currentFocusIndex;let findKey=Gallery.getFileKey(true,true);if(findKey===-1){findKey=Gallery.getFileKey(false,true);}
if(findKey===-1){if(currentView!==LAYOUT_MODE.pick){let view=Favorite.isFavoriteList?LAYOUT_MODE.favorite:LAYOUT_MODE.list;setView(view);}}else{FilesStore.currentFileKey=findKey;updateFrames(FilesStore.currentFileKey);}
if(oldFocus<Gallery.currentFocusIndex){Gallery.currentFocusIndex--;}
Favorite.updateOptionsMenu();}
thumbnailList.removeItem(FilesStore.getFileInfo(oldFileKey));FilesStore.deteleFileInfo(oldFileKey);if(navCallback){navCallback();}
if(oldFileKey<editedPhotoIndex){editedPhotoIndex--;}
if(Favorite.isFavoriteList){let allThumbnails=Favorite.getALLFavorites();if(allThumbnails.length){if(currentView!==LAYOUT_MODE.fullscreen){Favorite.favoriteViewDeleteImg();}}else{Favorite.showEmptyLayer();}}else{let allThumbnails=NavigationMap.listControls();if(!allThumbnails.length){Overlay.show('emptygallery');}}
window.dispatchEvent(new CustomEvent('filedeleted',{detail:{filename:filename}}));}
function deleteFile(name,metadata){if(!name){return;};let storage=navigator.getDeviceStorage('pictures');let deleteRequest=storage.delete(name);deleteRequest.onsuccess=()=>{fileDeleted(name);};deleteRequest.onerror=(e)=>{console.error('Failed to delete',filename,'from DeviceStorage:',e.target.error);};if(metadata.preview&&metadata.preview.filename){storage.delete(metadata.preview.filename);};}
function fileCreated(fileinfo){photodb.getFileInfo(fileinfo.name,function(fileinfo){if(picking&&fileinfo.metadata.largeSize){return;}
const thumbnailItem=thumbnailList.addItem(fileinfo);needNav();FilesStore.setFileInfo(fileinfo);Favorite.refreshBackground(Gallery.currentFocusIndex);if(Overlay.current==='emptygallery'||Overlay.current==='scanning'){Overlay.hide();if(picking){if(!Dongle.isDonglePick){setView(LAYOUT_MODE.pick);SoftkeyManager.initPickRelateButton();}}else{setView(LAYOUT_MODE.list);}
visuallyLoadedHandle();}
if(Favorite.isFavoriteList){Favorite.favoriteViewCreateImg(thumbnailItem);}
if(currentView===LAYOUT_MODE.select){selectViewCreateNewImg(thumbnailItem);}
if(currentView===LAYOUT_MODE.fullscreen){const allThumbnails=Favorite.isFavoriteList?Favorite.getALLFavorites():NavigationMap.listControls();const fileKey=FilesStore.currentFileKey;const selector=`.thumbnail-list-img[data-fileskeycounter="${fileKey}"]`;const element=thumbnails.querySelector(selector).parentNode;Gallery.currentFocusIndex=Array.prototype.indexOf.call(allThumbnails,element);updateFrames(FilesStore.currentFileKey);}
const insertPosition=getInsertPosition(fileinfo);if(editSaveCallback)editSaveCallback();if(insertPosition<0){return;}
if(editedPhotoIndex>=insertPosition){editedPhotoIndex++;}
if(hasSaved){if(currentView===LAYOUT_MODE.fullscreen){setView(LAYOUT_MODE.fullscreen);updateFrames(FilesStore.currentFileKey);}
if(currentView===LAYOUT_MODE.list){let currentItem=thumbnails.querySelector('div.focus');if(currentItem){currentItem.scrollIntoView(false);}}
Gallery.editedImageAddBg(thumbnailItem.imgNode,fileinfo);hasSaved=false;}});}
function scrollToShowThumbnail(n){if(!FilesStore.getFileInfo(n)){return;}
let selector='[data-filename="'+FilesStore.getFileInfo(n).name+'"]';var thumbnail=thumbnails.querySelector(selector);if(thumbnail){var screenTop=thumbnails.scrollTop;var screenBottom=screenTop+thumbnails.clientHeight;var thumbnailTop=thumbnail.offsetTop;var thumbnailBottom=thumbnailTop+thumbnail.offsetHeight;if(thumbnailTop<screenTop){thumbnails.scrollTop=thumbnailTop;}
else if(thumbnailBottom>screenBottom){thumbnails.scrollTop=thumbnailBottom-thumbnails.clientHeight;}}}
function setView(view){if(currentView===view||NavigationMap.inProgress)
return;switch(currentView){case LAYOUT_MODE.select:thumbnails.removeAttribute('mode');Array.forEach(thumbnails.querySelectorAll('.thumbnail-list-img'),function(elt){elt.dataset.selected=false;elt.checkBoxContainerNode.setAttribute('data-icon','check-off');elt.classList.remove('selected');});cleanSelectStates();break;case LAYOUT_MODE.fullscreen:clearFrames();if(!Gallery.enumerateEnd){startOthersEnumerate();}
break;};let theme=document.querySelectorAll('meta[name="theme-color"]')[0];let themColor={'editView':'transparent','fullscreenView':'transparent'}[view]||'rgb(0,0,0)';if(theme&&themColor!=='transparent'){theme.setAttribute('content',themColor);}
document.body.classList.remove(currentView);document.body.classList.add(view);switch(view){case LAYOUT_MODE.list:scrollToShowThumbnail(FilesStore.currentFileKey);break;case LAYOUT_MODE.fullscreen:resizeFrames();break;case LAYOUT_MODE.select:scrollToShowThumbnail(FilesStore.currentFileKey);SoftkeyManager.setSkMenu(LAYOUT_MODE.select);resetSelection();break;case LAYOUT_MODE.edit:break;}
Gallery.lastView=currentView;currentView=view;ViewHelper.resetView();if(theme&&themColor==='transparent'){theme.setAttribute('content',themColor);}}
function thumbnailClickHandler(evt){window.performance.mark('gallery-preview-start');let target=evt.target;if(!target){return;}
target=target.classList.contains('thumbnail')?target.firstElementChild:target;if(!target||!target.classList.contains('thumbnail-list-img')){return;}
if(photodb.state!==MediaDB.READY){return;}
ProgressBar.hideGaiaProgress();if(picking&&currentView===LAYOUT_MODE.pick&&FilesStore.currentFileKey>=0){Pick.select(FilesStore.getFileInfo(FilesStore.currentFileKey));}else if(currentView===LAYOUT_MODE.select||Dongle.isDonglePick){updateSelection(target);}else{if(FilesStore.getFileInfo(FilesStore.currentFileKey).metadata.largeSize){const dialogConfig={title:{id:'invalid-image',args:{}},body:{id:'image-too-big',args:{}},accept:{name:'Ok',l10nId:'ok',callback:null}};confirmDialog(dialogConfig);return;}
if(Dongle.dongleEnabled){Dongle.hasJioMediaCable().then((hasApp)=>{if(hasApp){Dongle.imagePlayOnDongleDevice(target);}else{setView(LAYOUT_MODE.fullscreen);}});}else{setView(LAYOUT_MODE.fullscreen);}
FilesStore.currentFileKey=Gallery.numberFilesKeyCounter(target);updateFrames(FilesStore.currentFileKey);if(window.performance.getEntriesByName('gallery-preview-start','mark').length>0){window.performance.mark('gallery-preview-end');window.performance.measure('performance-gallery-preview','gallery-preview-start','gallery-preview-end');window.performance.clearMeasures('performance-gallery-preview');window.performance.clearMarks('gallery-preview-start');window.performance.clearMarks('gallery-preview-end');}}}
function updateSelection(thumbnail){const selected=thumbnail.classList.contains('selected');if(Dongle.isDonglePickMultiple&&!selected&&selectedFileNames.length>=Dongle.maxPickCount){return;}
const index=FilesStore.currentFileKey;if(index<0){return;}
thumbnail.classList.toggle('selected');const filename=FilesStore.getFileInfo(index).name;if(!selected){thumbnail.dataset.selected=true;thumbnail.checkBoxContainerNode.setAttribute('data-icon','check-on');selectedFileNames.push(filename);if(thumbnail.parentNode.classList.contains("largeSize")){selectedInvalid++;}
photodb.getFile(filename,function(file){selectedFileNamesToBlobs[filename]=file;});}else{thumbnail.dataset.selected=false;thumbnail.checkBoxContainerNode.setAttribute('data-icon','check-off');if(thumbnail.parentNode.classList.contains("largeSize")){selectedInvalid--;}
delete selectedFileNamesToBlobs[filename];let i=selectedFileNames.indexOf(filename);if(i!==-1){selectedFileNames.splice(i,1);}}
updateMultipleCount(selectedFileNames.length);if(Dongle.isDonglePick){Dongle.updateSoftKeyButton(!selected);}else{let thumbnailsCount=0;if(Favorite.isFavoriteList){thumbnailsCount=Favorite.getALLFavorites().length;}else{thumbnailsCount=NavigationMap.listControls().length;}
const isAll=selectedFileNames.length===thumbnailsCount;SoftkeyManager.setSkMenu();SoftkeyManager.updateSkText(isAll?'kai-deselect-all':'kai-select-all');Gallery.setSelectSubView(isAll?'all':(!selected?'des':''));isSelectAll=!isAll;}}
function launchCameraApp(){if(Gallery.triggerCamera){return;}
Gallery.triggerCamera=true;const activity=new MozActivity({name:'record',data:{type:'photos'}});activity.onsuccess=()=>{Gallery.triggerCamera=false;};activity.onerror=()=>{Gallery.triggerCamera=false;};}
function share(blobs,blobName){if(blobs.length===0)
return;var names=[],types=[],fullpaths=[];blobs.forEach(function(blob){var name=blob.name;if(!name&&blobs.length===1)
name=blobName;fullpaths.push(name);name=name.substring(name.lastIndexOf('/')+1);names.push(name);var type=blob.type;if(type)
type=type.substring(0,type.indexOf('/'));types.push(type);});var type;if(types.length===1||types.every(function(t){return t===types[0];}))
type=types[0]+'/*';else
type='application/*';var a=new MozActivity({name:'share',data:{type:type,number:blobs.length,blobs:blobs,filenames:names,filepaths:fullpaths}});shareProcess=true;a.onsuccess=function(){setTimeout(function(){shareProcess=false;},500);};a.onerror=function(e){shareProcess=false;if(a.error.name==='NO_PROVIDER'){var msg=navigator.mozL10n.get('share-noprovider');alert(msg);}
else{console.warn('share activity error:',a.error.name);}};}
function resizeHandler(){if(currentView===LAYOUT_MODE.fullscreen){resizeFrames();setFramesPosition();}}
function doNotScanInBackgroundHack(photodb){const enoughMB=512;var memoryMB=0;window.addEventListener('visibilitychange',backgroundScanKiller);photodb.addEventListener('scanend',function(){window.removeEventListener('visibilitychange',backgroundScanKiller);});function backgroundScanKiller(){if(!document.hidden||memoryMB>=enoughMB){return;}
if(!navigator.getFeature){exit();}
else{navigator.getFeature('hardware.memory').then(function(mem){memoryMB=mem;if(memoryMB<enoughMB){exit();}});}
function exit(){if(document.hidden&&photodb.scanning){console.warn('[Gallery] exiting to avoid background scan.');setTimeout(function(){window.close();},500);}}}}
function initHtml(){enable(fullscreenView=$('fullscreen-view'));enable(infoDialog=$('info-view'));enable(cropView=$('crop-view'));enable($('edit-view'));enable($('confirm-dialog'));if(!Settings.settingsDialog){enable(Settings.settingsDialog=$('settings-dialog'));}}
function enable(h){h.innerHTML=h.innerHTML.replace(/(<!--)|(-->)/g,'');}
let ProgressBar={createGaiaProgress:function(show){let e=document.createElement('gaia-progress');e.id='gaia-progress';if(!show){e.classList.add('hidden');}
let spinner=$('spinner');spinner.parentNode.insertBefore(e,spinner);return e;},showGaiaProgress:function(){if(Dongle.isDonglePick){return;}
if(!gaiaProgress){gaiaProgress=this.createGaiaProgress(true);}else if(gaiaProgress.classList.contains('hidden')){gaiaProgress.classList.remove('hidden');}},hideGaiaProgress:function(){gaiaProgress&&gaiaProgress.classList.add('hidden');}};function checkStorage(){return new Promise((resolve)=>{let req=navigator.mozSettings.createLock().get('device.storage.writable.name');req.onsuccess=()=>{let mediaLocation=req.result['device.storage.writable.name'];let storages=navigator.getDeviceStorages('sdcard');let storage;if(mediaLocation==='sdcard'){storage=storages[0];}else{storage=storages[1];};let freeSpaceRequest=storage.freeSpace();freeSpaceRequest.onsuccess=(result)=>{let freeSpace=result.target.result;resolve({size:freeSpace,name:mediaLocation});};freeSpaceRequest.onerror=()=>{console.warn('checkAvailableSpace met error');}}});};function fullStorage(){checkStorage().then((res)=>{let isSdCard=res.name==='sdcard'?true:false;let titleId=isSdCard?'phone-is-full-title':'sd-card-is-full-title';let bodyId=isSdCard?'phone-is-full-content':'sd-card-is-full-content';var dialogConfig={title:{id:titleId,args:{}},body:{id:bodyId,args:{}},cancel:{l10nId:'cancel',priority:1,callback:function(){}},confirm:{l10nId:'kai-settings',priority:3,callback:function(){goToSettings();}}};confirmDialog(dialogConfig);});};function goToSettings(){new MozActivity({name:'configure',data:{target:'device',section:'mediaStorage'}});};function selectViewCreateNewImg(thumbnailItem){let IMG=thumbnailItem.imgNode;let checkBox=IMG.checkBoxContainerNode;checkBox.classList.remove('hidden');if(Gallery.isTriggerAll){IMG.classList.add('selected');IMG.dataset.selected=true;IMG.checkBoxContainerNode.setAttribute('data-icon','check-on');selectedFileNames.push(IMG.fileData.name);photodb.getFile(IMG.fileData.name,function(file){selectedFileNamesToBlobs[IMG.fileData.name]=file;});if(IMG.parentNode.classList.contains("largeSize")){selectedInvalid++;}
updateMultipleCount(selectedFileNames.length);};};function checkHasDmWallpaper(){const lock=navigator.mozSettings.createLock();lock.get(DM_WALLPAPER_IMAGE).then((value)=>{if(value[DM_WALLPAPER_IMAGE]){dmWallpaperImage=true;}else{dmWallpaperImage=false;}});if(lock.forceClose){lock.forceClose();}}
function pendingInit(pendingInitCallback){setTimeout(()=>{const lazyFiles=['shared/style/status.css','shared/style/progress_activity.css','shared/style/navigation.css','shared/style/action_menu.css','shared/style/toaster.css','shared/elements/gaia-progress/dist/gaia-progress.js','shared/js/input_handler.js','shared/js/toaster.js','js/frame_scripts.js','js/spinner.js'];LazyLoader.load(lazyFiles,()=>{if(pendingInitCallback){pendingInitCallback();}});},1000);}