
if(typeof window.lget!=='function'){window.lget=function(l10nId){return navigator.mozL10n.get(l10nId);};}
const NavigationMap={currentActivatedLength:0}
function confirmDialog(dialogConfig){if(typeof ConfirmDialogHelper==='undefined'){LazyLoader.load('js/shared/confirm_dialog_helper.js',()=>{const dialog=new ConfirmDialogHelper(dialogConfig);dialog.show(document.getElementById('app-dialog'));});}else{const dialog=new ConfirmDialogHelper(dialogConfig);dialog.show(document.getElementById('app-dialog'));}}
var Open={activity:null,activityData:null,saved:false,maxImageSize:null,imageIsLarge:false,init:function(){Open.maxImageSize=CONFIG_MAX_IMAGE_PIXEL_SIZE;frame=new MediaFrame(document.getElementById('frame'),false,Open.maxImageSize);if(Open.activityData.allowSave){frame.container.classList.add('need-save-button');softkeyManager.show();}
createFrame();openImage();},checkFilename:function(){if(this.activityData.filename.indexOf('.gallery/')!=-1){return false;}else{var dotIdx=this.activityData.filename.lastIndexOf('.');if(dotIdx===-1){return false;}
var ext=this.activityData.filename.substr(dotIdx+1);return MimeMapper.guessTypeFromExtension(ext)===this.blob.type;}},save:function(){getStorageIfAvailable('pictures',Open.blob.size,(ds)=>{Open.storage=ds;let filename=Open.activityData.filename;const file=filename.substring(filename.lastIndexOf('/')+1);filename="/"+Open.storage.storageName+"/downloads/"+file;getUnusedFilename(Open.storage,filename,function(filename){const saveRequest=Open.storage.addNamed(Open.blob,filename);saveRequest.onsuccess=()=>{Open.saved=filename;showToaster('saved',{filename:filename.substring(filename.lastIndexOf('/')+1)});};saveRequest.onerror=(e)=>{console.error(e);};});},()=>{storageIsFull();});},done:function(){Open.activity.postResult({saved:Open.saved});Open.activity=null;}}
var element;function optionCheck(ele){element=ele;if(!element){element=document.querySelector('#option-menu .menu-button:first-child');}
let focused=document.querySelectorAll('.focus');if(focused.length>0){focused[0].classList.remove('focus');}
element.setAttribute('tabindex',1);element.classList.add('focus');element.focus();}
function mutationsHandler(mutations){mutations.forEach((mutation)=>{if(mutation.addedNodes.length===0){return;}
let childs=mutation.addedNodes;for(let i=0;i<childs.length;i++){if(childs[i].id==="option-menu"){optionCheck();childs[i].addEventListener('keydown',function(e){switch(e.key){case'ArrowUp':if(element){optionCheck(element.previousSibling||document.querySelector('#option-menu .menu-button:last-child'));}
break;case'ArrowDown':if(element){optionCheck(element.nextSibling||document.querySelector('#option-menu .menu-button:first-child'));}
break;}});}}});}
const menuItems={'home':[{name:'Save',l10nId:'save',priority:4,method:Open.save}]}
var softkeyManager;navigator.mozL10n.once(function(){document.body.classList.toggle('large-text',navigator.largeTextEnabled);softkeyManager=new SoftkeyPanel({header:lget('kai-options'),items:menuItems['home']});navigator.mozSetMessageHandler('activity',function activityHandler(request){Open.activity=request;Open.activityData=request.source.data;Open.blob=request.source.data.blob;Open.init();});var observer=new MutationObserver(mutationsHandler);observer.observe(document.body,{childList:true,attributes:false,chatacterData:false,subtree:false});window.addEventListener('keydown',(evt)=>{if(evt.key==='Enter'||evt.key==='Accept'){evt.target.click();for(let i=0;i<evt.target.children.length;i++){evt.target.children[i].click();}}});});var frame;function createFrame(){if(lowMemory){frame.image.setAttribute('animationMode','dontanim');}
if(CONFIG_REQUIRED_EXIF_PREVIEW_WIDTH){frame.setMinimumPreviewSize(CONFIG_REQUIRED_EXIF_PREVIEW_WIDTH,CONFIG_REQUIRED_EXIF_PREVIEW_HEIGHT);}
window.addEventListener('resize',frame.resize.bind(frame));if(Open.activityData.exitWhenHidden){window.addEventListener('visibilitychange',function(){if(document.hidden){Open.done();}});}
frame.onerror=function invalid(){displayError('image-invalid');};}
function openImage(){const blob=Open.blob;getImageSize(blob,success,function error(){if(!Open.imageIsLarge){displayError('image-invalid');}});function success(metadata){Open.activityData.width=metadata.width;Open.activityData.height=metadata.height;let pixels=metadata.width*metadata.height;if(metadata.type!=='jpeg'&&lowMemory){Open.maxImageSize=LOW_MAX_IMAGE_PIXEL_SIZE_NO_JPEG;};let filesizelimit=2*Open.maxImageSize;if(pixels>Open.maxImageSize||blob.size>filesizelimit){Open.imageIsLarge=true;displayError('image-too-big');return;}
if(!metadata.preview||pixels<512*1024){setTimeout(function(){frame.displayImage(blob,metadata.width,metadata.height,null,metadata.rotation,metadata.mirrored);},10);}else{parseJPEGMetadata(blob.slice(metadata.preview.start,metadata.preview.end,'image/jpeg'),function success(previewmetadata){metadata.preview.width=previewmetadata.width;metadata.preview.height=previewmetadata.height;frame.displayImage(blob,metadata.width,metadata.height,metadata.preview,metadata.rotation,metadata.mirrored);},function error(){frame.displayImage(blob,metadata.width,metadata.height,null,metadata.rotation,metadata.mirrored);});}}}
function showToaster(id,args){var options={messageL10nId:id,messageL10nArgs:args,latency:2000,useTransition:false};if(typeof Toaster==='undefined'){LazyLoader.load(['shared/js/toaster.js','shared/style/toaster.css'],()=>{Toaster.showToast(options);});}else{Toaster.showToast(options);}}
function displayError(bodyId){const dialog=document.querySelector('#overlay');const text=dialog.querySelector('#overlay-text');text.setAttribute('data-l10n-id',bodyId);dialog.classList.add('show');softkeyManager.hide();const dialogSoftKey=new SoftkeyPanel({items:[{name:'ok',l10nId:'ok',priority:2,method:Open.done.bind(Open)}]});dialogSoftKey.show();}
function storageIsFull(){let req=navigator.mozSettings.createLock().get('device.storage.writable.name');req.onsuccess=()=>{let mediaLocation=req.result['device.storage.writable.name'];let isSdCard=mediaLocation==='sdcard'?true:false;let titleId=isSdCard?'phone-is-full-title':'sd-card-is-full-title';let bodyId=isSdCard?'phone-is-full-content':'sd-card-is-full-content';var dialogConfig={title:{id:titleId,args:{}},body:{id:bodyId,args:{}},cancel:{l10nId:'cancel',priority:1,callback:function(){}},confirm:{l10nId:'kai-settings',priority:3,callback:function(){new MozActivity({name:'moz_configure_window',data:{target:'device',section:'mediaStorage'}});window.close();}}};confirmDialog(dialogConfig);};};