
function ThumbnailItem(fileData,fileKey){if(!fileData){throw new Error('fileData should not be null or undefined.');}
this.data=fileData;this.htmlNode=document.createElement('div');this.htmlNode.classList.add('thumbnail');this.htmlNode.dataset.filename=fileData.name;this.htmlNode.setAttribute('data-columncount',Gallery.columnCount);this.imgNode=document.createElement('div');this.imgNode.classList.add('thumbnail-list-img');if(fileKey===0||fileKey){this.imgNode.setAttribute('data-filesKeyCounter',fileKey);}else{this.imgNode.setAttribute('data-filesKeyCounter',FilesStore.filesKeyCounter);}
this.imgNode.dataset.filename=fileData.name;this.imgNode.setAttribute('animationMode','dontanim');this.imgNode.fileData=fileData;this.imgNode.fileData.thumbnailContainer=this.imgNode;this.imgNodeOverlay=document.createElement('div');this.imgNodeOverlay.classList.add('thumbnail-list-img-overlay');createMultipleSelectInput(this.imgNode);this.imgNode.appendChild(this.imgNodeOverlay);if(fileData.metadata.largeSize){this.htmlNode.classList.add('largeSize');const largeIcon=document.createElement('i');largeIcon.setAttribute('data-icon','exclamation');largeIcon.classList.add('thumbnail-list-img-large');this.imgNode.appendChild(largeIcon);}
this.htmlNode.appendChild(this.imgNode);Favorite.createFavoriteDiv(this.imgNode,fileData.metadata.favorite,'thumbnail-favorite-status');this.localize();}
ThumbnailItem.formatter=new navigator.mozL10n.DateTimeFormat();ThumbnailItem.prototype.localize=function(){var date=new Date(this.data.date);var description=navigator.mozL10n.get('imageDescriptionShort');var label=ThumbnailItem.formatter.localeFormat(date,description);this.htmlNode.setAttribute('aria-label',label);this.htmlNode.setAttribute('role','heading');};function ThumbnailDateGroup(item){if(!item){throw new Error('item should not be null or undefined.');}
this.thumbnails=[];this.groupID=ThumbnailDateGroup.getGroupID(item);if(!ThumbnailDateGroup.Template){throw new Error('template is required while rendering.');}
var _=navigator.mozL10n.get;var dateFormatter=new navigator.mozL10n.DateTimeFormat();if(Settings.GROUPBYDATEANDLOCATION){var htmlText=ThumbnailDateGroup.Template.interpolate({'group-header':dateFormatter.localeFormat(new Date(item.date),_('date-group-header'))});}else{var htmlText=ThumbnailDateGroup.Template.interpolate({'group-header':''});}
var dummyDiv=document.createElement('DIV');dummyDiv.innerHTML=htmlText;var groupHeader=dummyDiv.querySelector('.thumbnail-group-header');if(groupHeader&&!Settings.GROUPBYDATEANDLOCATION){groupHeader.classList.add('hidden');}
var domNode=dummyDiv.firstElementChild;if(!domNode){throw new Error('the template is empty');}
this.htmlNode=domNode;this.container=domNode.querySelector('.thumbnail-group-container');if(navigator.mozL10n.readyState==='complete'){}}
ThumbnailDateGroup.Template=new Template('thumbnail-group-header');ThumbnailDateGroup.getGroupID=function(item){if(!Settings.GROUPBYDATEANDLOCATION){return 0;}
var dateObj=new Date(item.date);var month=dateObj.getMonth()+1;return'group_'+dateObj.getFullYear()+'-'+
(month<10?'0'+month:month);};ThumbnailDateGroup.compareGroupID=function(id1,id2){return id1>id2?1:(id1<id2?-1:0);};ThumbnailDateGroup.prototype.addItem=function(item,fileKey){if(!item){return;}
let thumbnail=new ThumbnailItem(item,fileKey);var insertPosition=this.getInsertPosition(thumbnail);this.container.insertBefore(thumbnail.htmlNode,this.container.children[insertPosition]);this.thumbnails.splice(insertPosition,0,thumbnail);return thumbnail;};ThumbnailDateGroup.prototype.getInsertPosition=function(thumbnail){var self=this;switch(Settings.SORTTYPE){case 0:if(self.thumbnails.length===0||thumbnail.data.date>self.thumbnails[0].data.date){return 0;}else if(thumbnail.data.date<self.thumbnails[self.thumbnails.length-1].data.date){return self.thumbnails.length;}else{return MediaUtils.binarySearch(self.thumbnails,thumbnail,function(a,b){return b.data.date-a.data.date;});}
break;case 1:if(self.thumbnails.length===0){return 0;}else{return MediaUtils.binarySearch(self.thumbnails,thumbnail,function(a,b){var filenameA=(a.data.name.split('/').pop()).toLowerCase();var filenameB=(b.data.name.split('/').pop()).toLowerCase();return filenameA.localeCompare(filenameB);});}
break;case 2:if(self.thumbnails.length===0){return 0;}else{return MediaUtils.binarySearch(self.thumbnails,thumbnail,function(a,b){return b.data.size-a.data.size;});}
break;case 3:if(self.thumbnails.length===0){return 0;}else{return MediaUtils.binarySearch(self.thumbnails,thumbnail,function(a,b){a=a.data.type.toLowerCase();b=b.data.type.toLowerCase();return a.localeCompare(b);});}
break;}};ThumbnailDateGroup.prototype.getCount=function(){return this.thumbnails.length;};ThumbnailDateGroup.prototype.getIndex=function(fileInfo){var thumbnail={data:fileInfo};var index=this.getInsertPosition(thumbnail)-1;return(index>=0&&index<this.container.children.length)?index:-1;};ThumbnailDateGroup.prototype.getDisplayPos=function(fileInfo){var self=this;var eleIndex=-1;Object(self.thumbnails).forEach(function(item,index){if(fileInfo.name===item.data.name){eleIndex=index;}});return eleIndex;};ThumbnailDateGroup.prototype.removeItem=function(fileInfo){var idx=this.getDisplayPos(fileInfo);if(-1===idx)return;this.thumbnails.splice(idx,1);this.container.removeChild(this.container.children[idx]);};ThumbnailDateGroup.formatter=new navigator.mozL10n.DateTimeFormat();ThumbnailDateGroup.prototype.localize=function(){var date=new Date(this.date);var format=navigator.mozL10n.get('date-group-header');var formattedDate=ThumbnailDateGroup.formatter.localeFormat(date,format);this.header.textContent=formattedDate;this.thumbnails.forEach(function(thumbnail){thumbnail.localize();});};function ThumbnailList(groupClass,container){if(!groupClass||!container){throw new Error('group class or container cannot be null or undefined');}
this.itemGroups=[];this.groupClass=groupClass;this.container=container;};ThumbnailList.prototype.findGroup=function(fileInfo){var group={groupID:ThumbnailDateGroup.getGroupID(fileInfo)};var index=this.itemGroups.bsearch(group,(a,b)=>{return ThumbnailDateGroup.compareGroupID(b.groupID,a.groupID);});return index!==-1?this.itemGroups[index]:null;};ThumbnailList.prototype.findThumbnail=function(fileInfo){var group=this.findGroup(fileInfo);if(group){var index=group.getIndex(fileInfo);if(-1!==index)
return group.container.children[index];}
return null;};ThumbnailList.prototype.addItem=function(item,fileKey){if(!item){return null;}
var self=this;function createItemGroup(item,before){var group=new self.groupClass(item);self.container.insertBefore(group.htmlNode,before?before.htmlNode:null);return group;}
function getItemGroup(item){var groupID=self.groupClass.getGroupID(item);var i;for(i=0;i<self.itemGroups.length;i++){if(self.itemGroups[i].groupID===groupID){return self.itemGroups[i];}else if(self.groupClass.compareGroupID(self.itemGroups[i].groupID,groupID)<0){break;}}
var createdGroup=createItemGroup(item,self.itemGroups[i]);self.itemGroups.splice(i,0,createdGroup);return createdGroup;}
var group=getItemGroup(item);let thumbnail=group.addItem(item,fileKey);return thumbnail;};ThumbnailList.prototype.removeItem=function(fileInfo){var group=this.findGroup(fileInfo);if(group){group.removeItem(fileInfo);if(!group.getCount()){this.container.removeChild(group.htmlNode);this.itemGroups.splice(this.itemGroups.indexOf(group),1);}}};ThumbnailList.prototype.reset=function(){this.container.innerHTML='';this.itemGroups=[];};ThumbnailList.prototype.resetThumbnail=function(){var self=this;self.reset();for(let[key,value]of FilesStore.filesStoreMap){self.addItem(value,key);}};ThumbnailList.prototype.getAllThumbnails=function getAllThumbnails(){let allThumbnails=[];const groups=this.itemGroups;for(let i=0;i<groups.length;i++){const{thumbnails}=groups[i];allThumbnails=allThumbnails.concat(thumbnails);}
return allThumbnails;};'use strict';function shareItems(){if(currentView===LAYOUT_MODE.select){let IMGS=thumbnails.querySelectorAll('.selected.thumbnail-list-img');let largeImageNames=[];let shareImageNames=[];if(IMGS.length<1){return;};Array.forEach(IMGS,function(IMG){if(IMG.fileData.metadata.largeSize){largeImageNames.push(IMG.fileData.name);}else{shareImageNames.push(IMG.fileData.name);};});let blobs=shareImageNames.map(function(name){return selectedFileNamesToBlobs[name];});if(largeImageNames.length>0){Message.show('kai-some-photos-not-share');};share(blobs);}else{let fileinfo=FilesStore.getFileInfo(FilesStore.currentFileKey);photodb.getFile(fileinfo.name,function(blob){share([blob]);});}}
function resetMultiSelect(){thumbnails.setAttribute('mode','multi-select');Array.forEach(thumbnails.querySelectorAll('.thumbnail-list-img'),function(item){item.dataset.selected=false;item.checkBoxContainerNode.setAttribute('data-icon','check-off');});}
function selectAllPhotos(){var selectedNum=0;let IMGS=null;if(Favorite.isFavoriteList){IMGS=Favorite.getALLFavorites();}else{IMGS=NavigationMap.listControls();}
selectedFileNames=[];selectedFileNamesToBlobs={};selectedInvalid=0;if(isSelectAll){Gallery.isTriggerAll=true;Array.forEach(IMGS,function(IMG){IMG=IMG.firstElementChild;IMG.classList.add('selected');IMG.dataset.selected=true;IMG.checkBoxContainerNode.setAttribute('data-icon','check-on');selectedFileNames.push(IMG.fileData.name);photodb.getFile(IMG.fileData.name,function(file){selectedFileNamesToBlobs[IMG.fileData.name]=file;});if(IMG.parentNode.classList.contains("largeSize")){selectedInvalid++;}});selectedNum=IMGS.length;SoftkeyManager.setSkMenu();SoftkeyManager.updateSkText('kai-deselect-all');}
else{Gallery.isTriggerAll=false;Array.forEach(IMGS,function(IMG){IMG=IMG.firstElementChild;IMG.classList.remove('selected');IMG.dataset.selected=false;IMG.checkBoxContainerNode.setAttribute('data-icon','check-off');});SoftkeyManager.setSkMenu();SoftkeyManager.updateSkText('kai-select-all');}
updateMultipleCount(selectedNum);isSelectAll=!isSelectAll;Gallery.setSelectSubView(!isSelectAll?"all":"");}
function resetSelection(){selectedFileNames=[];selectedFileNamesToBlobs={};updateMultipleCount(0);resetMultiSelect();}
function cleanSelectStates(){selectedInvalid=0;isSelectAll=true;Gallery.isTriggerAll=false;}
function updateMultipleCount(count){navigator.mozL10n.setAttributes($('multiple-select-count'),'kai-selected-items-count',{n:count});}
function deleteSelectedPhotos(){Gallery.deleteFiles=thumbnails.querySelectorAll('.selected.thumbnail-list-img');if(Gallery.deleteFiles.length<1){return;};var dialogConfig={title:{id:'kai-confirmation',args:{}},body:{id:Gallery.deleteFiles.length>1?'kai-delete-selected-images':'kai-delete-selected-image',args:{}},cancel:{l10nId:'cancel',callback:function(){},},confirm:{l10nId:'delete',callback:function(){Gallery.deleteSelected=true;window.addEventListener('keydown',keydownHandler,true);document.getElementById('mask-background').classList.remove('hidden');SoftkeyManager.softkey.hide();setView(Gallery.lastView);NavigationMap.inProgress=true;listProgressBar.value=0;listProgressBar.classList.remove('hidden');let storage=navigator.getDeviceStorage('pictures');for(let i=0;i<Gallery.deleteFiles.length;i++){let fileData=Gallery.deleteFiles[i].fileData;deleteSeletedFiles(storage,fileData);};},},};confirmDialog(dialogConfig);}
function deleteSeletedFiles(storage,fileData){let name=fileData.name;let metadata=fileData.metadata;let deleteRequest=storage.delete(name);deleteRequest.onsuccess=()=>{Gallery.deleteSuccessFiles.push(fileData);let successCount=Gallery.deleteSuccessFiles.length;let errorCount=Gallery.deleteErrorFiles.length;let deletedCount=successCount+errorCount;if(deletedCount!==Gallery.deleteFiles.length){return;};for(let i=0;i<successCount;i++){let fileData=Gallery.deleteSuccessFiles[i];let deleteImage=fileData.thumbnailContainer;let deleteImgFileKey=Gallery.numberFilesKeyCounter(deleteImage);let fileInfo=FilesStore.getFileInfo(deleteImgFileKey);thumbnailList.removeItem(fileInfo);FilesStore.deteleFileInfo(deleteImgFileKey);listProgressBar.value=parseInt(100*i/successCount);};deleteDone(successCount);};deleteRequest.onerror=(e)=>{Gallery.deleteErrorFiles.push(fileData);console.error('Failed to delete',name,'from DeviceStorage:',e.target.error);};if(metadata.preview&&metadata.preview.filename){storage.delete(metadata.preview.filename);};}
function deleteDone(deleteFilesCount){Message.show('kai-deleted-n-photos',deleteFilesCount);listProgressBar.classList.add('hidden');NavigationMap.inProgress=false;document.getElementById('mask-background').classList.add('hidden');if(Favorite.isFavoriteList){let allThumbnails=Favorite.getALLFavorites();if(!allThumbnails.length){Favorite.showEmptyLayer();}else{Favorite.favoriteViewDeleteImg();Favorite.refreshBackground(Gallery.currentFocusIndex);}}else{let allThumbnails=NavigationMap.listControls();if(!allThumbnails.length){if(Gallery.creatingThumbnails){Overlay.show('scanning');}else{Overlay.show('emptygallery');}}else{Favorite.refreshBackground(Gallery.currentFocusIndex);}}
SoftkeyManager.softkey.show();needNav();Gallery.deleteErrorFiles=[];Gallery.deleteFiles=[];Gallery.deleteSuccessFiles=[];Gallery.deleteSelected=false;window.removeEventListener('keydown',keydownHandler,true);}
function keydownHandler(e){switch(e.key){case'BrowserBack':case'Backspace':SoftkeyManager.backKeyHandler(e);break;default:e.preventDefault();e.stopPropagation();break;}}
function chkIsCurrentLarge(){let fileinfo=FilesStore.getFileInfo(FilesStore.currentFileKey);if(fileinfo&&fileinfo.metadata&&fileinfo.metadata.largeSize){return true;}
return false;}
function updateMetadata(fileName,metadata,callback){photodb.updateMetadata(fileName,metadata,callback);}
function deleteSingleItem(){let fileinfo=FilesStore.getFileInfo(FilesStore.currentFileKey);let dialogConfig={title:{id:'kai-confirmation',args:{}},body:{id:currentView===LAYOUT_MODE.fullscreen?'kai-delete-this-image':'kai-delete-selected-image',args:{}},backcallback:function(){},cancel:{l10nId:'cancel',callback:function(){},},confirm:{l10nId:'delete',callback:function(){if(currentView===LAYOUT_MODE.fullscreen){window.performance.mark('gallery-delete-start');}
window.addEventListener('filedeleted',singleDeleteDone);deleteFile(fileinfo.name,fileinfo.metadata);Message.show('kai-single-image-deleted');},},};confirmDialog(dialogConfig);function singleDeleteDone(){window.removeEventListener('filedeleted',singleDeleteDone);needNav();}}
function createMultipleSelectInput(imgNode){var checkBoxContainerNode=document.createElement('div');checkBoxContainerNode.classList.add('check-icon');checkBoxContainerNode.classList.add('hidden');checkBoxContainerNode.setAttribute('data-icon','check-off');imgNode.checkBoxContainerNode=checkBoxContainerNode;imgNode.appendChild(checkBoxContainerNode);}