'use strict';(function(exports){var AppWindowManager=function(){};AppWindowManager.prototype={DEBUG:false,name:'AppWindowManager',EVENT_PREFIX:'appwindowmanager',continuousTransition:false,HARDWARE_KEYEVENTS:['browserback','backspace','softleft','softright','enter','arrowup','arrowdown','1','2','3','5','8','e','i','o','r','w'],slowTransition:false,element:document.getElementById('windows'),screen:document.getElementById('screen'),isActive:function(){return!!this._activeApp;},setHierarchy:function(active){if(!this._activeApp||!this._activeApp.element){this.debug('No active app.');this.display();return;}
if(active){if(!appWindowFactory.isLaunchingWindow()&&!WrapperFactory.isLaunchingWindow()){this.focus();}}else{if(this._activeApp.browser.element){setBrowserProperty(this._activeApp.browser.element,'canTakeFocus',false);}
this._activeApp.getTopMostWindow().setVisibleForScreenReader(false);}},killApps:function(){for(var id in this._apps){let app=this._apps[id];app.kill();}},focus:function(){if(!this._activeApp){return;}
if(!this._activeApp.element){this.display();return;}
this.debug('focusing '+this._activeApp.name);this._activeApp.focus();this._activeApp.setNFCFocus(true);},isRunning:function awm_isRunning(config){if(config.manifestURL&&this.getApp(config.origin)){return true;}else{return false;}},getActiveWindow:function(){return this.getActiveApp();},isPlayingContent:function(app){if(app&&app.audioChannels&&app.audioChannels.get('content')&&app.audioChannels.get('content').isPlaying()){return true;}
return false;},getActiveApp:function awm_getActiveApp(){return this._activeApp||(window.homescreenWindowManager?window.homescreenWindowManager.getHomescreen():null);},getApp:function awm_getApp(origin,manifestURL){for(var id in this._apps){var app=this._apps[id];if(app.origin===origin&&(!manifestURL||app.manifestURL===manifestURL)&&(!app.isBrowser()||app.config.url===origin)){return app;}}
return null;},getAppByURL:function awm_getAppByURL(url){for(var id in this._apps){var app=this._apps[id];if(app.config.url===url){return app;}}
return null;},getBrowserApp:function awm_getBrowserApp(origin){for(var id in this._apps){var app=this._apps[id];if(app.origin===origin&&app.isBrowser()){return app;}}
return null;},getApps:function awm_getApps(){return this._apps;},_activeApp:null,_apps:{},_settingsObserveHandler:null,_nfcHandler:null,display:function awm_display(newApp,openAnimation,closeAnimation,eventType){this._dumpAllWindows();var appCurrent=this._activeApp,appNext=newApp||homescreenWindowManager.getHomescreen('home'===eventType);if(!appNext){this.debug('no next app.');return;}
while(appNext.nextWindow){appNext=appNext.nextWindow;}
this.debug(' current is '+(appCurrent?appCurrent.url:'none')+'; next is '+(appNext?appNext.url:'none'));if(appCurrent&&appCurrent.instanceID==appNext.instanceID){this.debug('the app has been displayed.');appCurrent.open();return;}
if(document.mozFullScreen){document.mozCancelFullScreen();}
this.screen.classList.remove('fullscreen-app');var switching=appCurrent&&!appCurrent.isHomescreen&&!appNext.isHomescreen;this._updateActiveApp(appNext.instanceID);var that=this;if(appCurrent&&layoutManager.keyboardEnabled){window.addEventListener('keyboardhidden',function onhiddenkeyboard(){window.removeEventListener('keyboardhidden',onhiddenkeyboard);that.switchApp(appCurrent,appNext,switching);});if(this.continuousTransition){inputWindowManager.hideInputWindow();}else{inputWindowManager.hideInputWindowImmediately();}}else if(rocketbar.active){window.addEventListener('rocketbar-overlayclosed',function onClose(){window.removeEventListener('rocketbar-overlayclosed',onClose);that.switchApp(appCurrent,appNext,switching);});}else{this.switchApp(appCurrent,appNext,switching,openAnimation,closeAnimation)}},switchApp:function awm_switchApp(appCurrent,appNext,switching,openAnimation,closeAnimation){this.debug('before ready check'+appCurrent+appNext);appNext.ready(function(){if(appNext.isDead()){if(!appNext.isHomescreen){this._updateActiveApp(appCurrent.instanceID);return;}else{appNext=homescreenWindowManager.getHomescreen();appNext.ensure(true);}}
appNext.reviveBrowser();this.debug('ready to open/close'+switching);if(switching){this.publish('appswitching');}
this._updateActiveApp(appNext.instanceID);var immediateTranstion=false;if(appNext.rotatingDegree===90||appNext.rotatingDegree===270){immediateTranstion=true;}else if(appCurrent){var degree=appCurrent.determineClosingRotationDegree();if(degree===90||degree===270){immediateTranstion=true;}}else if(appNext.isHomescreen){immediateTranstion=true;}
if(appNext.resized&&!layoutManager.match(appNext.width,appNext.height)){immediateTranstion=true;}
appNext.open(immediateTranstion?'immediate':((switching===true)?'invoked':openAnimation));if(appCurrent&&appCurrent.instanceID!==appNext.instanceID){appCurrent.close(immediateTranstion?'immediate':((switching===true)?'invoking':closeAnimation));}else{this.debug('No current running app!');}}.bind(this));},start:function awm_start(){this.activated=false;if(this.slowTransition){this.element.classList.add('slow-transition');}else{this.element.classList.remove('slow-transition');}
window.addEventListener('launchapp',this);window.addEventListener('appcreated',this);window.addEventListener('appterminated',this);window.addEventListener('ftuskip',this);window.addEventListener('appopened',this);window.addEventListener('apprequestopen',this);window.addEventListener('apprequestclose',this);window.addEventListener('homescreenopened',this);window.addEventListener('homescreenterminated',this);window.addEventListener('reset-orientation',this);window.addEventListener('homescreencreated',this);window.addEventListener('homescreen-changed',this);window.addEventListener('killapp',this);window.addEventListener('displayapp',this);window.addEventListener('applicationuninstall',this);window.addEventListener('hidewindow',this);window.addEventListener('showwindow',this);window.addEventListener('hidewindowforscreenreader',this);window.addEventListener('showwindowforscreenreader',this);window.addEventListener('attentionopened',this);window.addEventListener('orientationchange',this);window.addEventListener('appopening',this);window.addEventListener('localized',this);window.addEventListener('hierarchytopmostwindowchanged',this);window.addEventListener('keyboard-activated',this);window.addEventListener('keyboard-deactivated',this);if(Service.query('isLowMemoryDevice')){window.addEventListener('mozmemorypressure',this);}
this._settingsObserveHandler={'continuous-transition.enabled':{defaultValue:null,callback:function(value){if(!value){return;}
this.continuousTransition=!!value;}.bind(this)},'nfc.enabled':{defaultValue:false,callback:(value)=>{if(!this._nfcHandler){this._nfcHandler=new NfcHandler(this);}
if(value){this._nfcHandler.start();}else{this._nfcHandler.stop();}}}};for(var name in this._settingsObserveHandler){SettingsListener.observe(name,this._settingsObserveHandler[name].defaultValue,this._settingsObserveHandler[name].callback);}
Service.request('registerHierarchy',this);Service.register('killApps',this);},stop:function awm_stop(){window.removeEventListener('launchapp',this);window.removeEventListener('appcreated',this);window.removeEventListener('appterminated',this);window.removeEventListener('ftuskip',this);window.removeEventListener('appopened',this);window.removeEventListener('apprequestopen',this);window.removeEventListener('apprequestclose',this);window.removeEventListener('homescreenopened',this);window.removeEventListener('reset-orientation',this);window.removeEventListener('homescreencreated',this);window.removeEventListener('homescreenterminated',this);window.removeEventListener('homescreen-changed',this);window.removeEventListener('killapp',this);window.removeEventListener('displayapp',this);window.removeEventListener('applicationuninstall',this);window.removeEventListener('hidewindow',this);window.removeEventListener('showwindow',this);window.removeEventListener('hidewindowforscreenreader',this);window.removeEventListener('showwindowforscreenreader',this);window.removeEventListener('attentionopened',this);window.removeEventListener('orientationchange',this);window.removeEventListener('appopening',this);window.removeEventListener('localized',this);window.removeEventListener('hierarchytopmostwindowchanged',this);window.removeEventListener('mozmemorypressure',this);for(var name in this._settingsObserveHandler){SettingsListener.unobserve(name,this._settingsObserveHandler[name].callback);}
this._settingsObserveHandler=null;Service.request('unregisterHierarchy',this);},'_handle_system-resize':function(){if(this._activeApp){this.debug(' Resizing '+this._activeApp.name);if(!this._activeApp.isTransitioning()){this._activeApp.resize();return false;}}
return true;},_handle_home:function(evt){if(FtuLauncher.respondToHierarchyEvent(evt)){if(!homescreenWindowManager.ready){return true;}
let topMostIsBrowser=(this._activeApp.isBrowser()||this._activeApp.isCursorEnabled())&&this._activeApp.getTopMostWindow()===this._activeApp;if(topMostIsBrowser&&evt.detail&&evt.detail.back&&!evt.detail.hold){this._activeApp._handle__back(evt);}else{if(evt.detail.back&&this._activeApp.frontWindow&&!this._activeApp.frontWindow._killed){this._activeApp.getTopMostWindow().kill();}else if(topMostIsBrowser&&evt.detail&&evt.detail.back){this._activeApp._handle__back(evt);}else if(!this._activeApp.isHomescreen&&evt.detail.kill){this._activeApp.kill();}else{this.display(null,null,null,'home');}}
return false;}else{return false;}},_handle_holdhome:function(evt){var ret=FtuLauncher.respondToHierarchyEvent(evt);return ret;},respondToHierarchyEvent:function(evt){if(this.HARDWARE_KEYEVENTS.indexOf(evt.type)>=0){return!this._activeApp||!this._activeApp.getTopMostWindow().handleHardwareKeyEvent(evt);}else if(this['_handle_'+evt.type]){return this['_handle_'+evt.type](evt);}else{return true;}},handleEvent:function awm_handleEvent(evt){this.debug('handling '+evt.type);var activeApp=this._activeApp;var detail=evt.detail;switch(evt.type){case'hierarchytopmostwindowchanged':if(Service.query('getTopMostUI')!==this){return;}
this._activeApp&&this._activeApp.getTopMostWindow().setNFCFocus(true);break;case'orientationchange':this.broadcastMessage(evt.type,Service.query('getTopMostUI')===this);break;case'appcreated':var app=evt.detail;this._apps[evt.detail.instanceID]=app;break;case'appterminated':var app=evt.detail;var instanceID=app.instanceID;if(activeApp&&instanceID===activeApp.instanceID){this.display();}
delete this._apps[instanceID];break;case'reset-orientation':if(activeApp){activeApp.setOrientation();}
break;case'ftuskip':if(!Service.query('locked')){this.display();}
break;case'appopening':case'appopened':case'homescreenopened':if('homescreenopened'===evt.type){this._apps[evt.detail.instanceID]=evt.detail;}
this._updateActiveApp(evt.detail.instanceID);break;case'homescreencreated':this._apps[evt.detail.instanceID]=evt.detail;break;case'homescreenterminated':delete this._apps[evt.detail.instanceID];break;case'homescreen-changed':this.display();break;case'killapp':this.kill(evt.detail.origin);break;case'displayapp':case'apprequestopen':this.display(evt.detail);break;case'apprequestclose':if(evt.detail.isActive()){this.display();}else{this.debug(evt.detail.name,' is not active so ignoring');}
break;case'applicationuninstall':this.kill(evt.detail.application.origin);break;case'hidewindow':activeApp&&activeApp.broadcast('hidewindow',evt.detail);break;case'hidewindowforscreenreader':activeApp.setVisibleForScreenReader(false);break;case'showwindowforscreenreader':activeApp.setVisibleForScreenReader(true);break;case'showwindow':this.onShowWindow(detail);break;case'attentionopened':if(activeApp){if(!activeApp.isOOP()){activeApp.setVisible(false,true);}else{activeApp.blur();}}
break;case'launchapp':var config=evt.detail;this.debug('launching'+config.origin);this.launch(config);break;case'localized':this.broadcastMessage('localized');break;case'keyboard-activated':this._activeApp&&this._activeApp.getTopMostWindow().toggleSpatialNavigation(false);break;case'keyboard-deactivated':this._activeApp&&this._activeApp.getTopMostWindow().toggleSpatialNavigation();break;case'mozmemorypressure':this.killInprocessApps();break;}},_handle_launchactivity:function(evt){if(evt.detail.isActivity&&evt.detail.inline&&this._activeApp){this._activeApp.broadcast('launchactivity',evt.detail);return false;}
return true;},'_handle_mozChromeEvent':function(evt){if(!evt.detail||evt.detail.type!=='inputmethod-contextchange'){return true;}
if(this._activeApp){this._activeApp.getTopMostWindow().broadcast('inputmethod-contextchange',evt.detail);return false;}
return true;},_dumpAllWindows:function(){if(!this.DEBUG){return;}
console.log('=====DUMPING APP WINDOWS BEGINS=====');for(var id in this._apps){var app=this._apps[id];if(app.previousWindow){continue;}
this._dumpWindow(app);while(app.nextWindow){this._dumpWindow(app,'->child:');app=app.nextWindow;}}
console.log('=====END OF DUMPING APP WINDOWS=====');},_dumpWindow:function(app,prefix){console.log((prefix?prefix:'')+'['+app.instanceID+']'+
(app.name||app.title||'ANONYMOUS')+' ('+app.url+')');if(app.calleeWindow){console.log('==>activity:['+app.instanceID+']'+
(app.name||app.title||'ANONYMOUS')+' ('+app.url+')');}},launch:function awm_launch(config){if(config.changeURL&&this.getApp(config.origin)){this.getApp(config.origin).modifyURLatBackground(config.url);}
if(config.stayBackground){return;}else{if(config.isActivity&&this._activeApp&&!this._activeApp.isHomescreen){this.linkWindowActivity(config);}
this.display(this.getApp(config.origin));}},linkWindowActivity:function awm_linkWindowActivity(config){var caller;var callee=this.getApp(config.origin);caller=this._activeApp.getTopMostWindow();if(caller.getBottomMostWindow()===callee){callee.frontWindow&&callee.frontWindow.kill();}else{callee.callerWindow=caller;caller.calleeWindow=callee;}},debug:function awm_debug(){if(this.DEBUG){console.log('['+this.name+']'+'['+Service.currentTime()+']'+
Array.slice(arguments).concat());}},kill:function awm_kill(origin,manifestURL){for(var id in this._apps){if(this._apps[id].origin===origin&&(!manifestURL||this._apps[id].manifestURL===manifestURL)){this._apps[id].kill();}}},killInprocessApps:function awm_killInprocessApps(){var musicOrigin='app://music.gaiamobile.org';var musicManifestURL='app://music.gaiamobile.org/manifest.webapp';var homescreenOrigin='app://launcher.gaiamobile.org';var homescreenManifestURL='app://launcher.gaiamobile.org/manifest.webapp';if(this.getApp(musicOrigin,musicManifestURL)){if(Service.query('getTopMostWindow').isHomescreen){this.kill(musicOrigin,musicManifestURL);}else{if(musicManifestURL!==this._activeApp.getTopMostWindow().manifestURL&&!this.getApp(homescreenOrigin,homescreenManifestURL)){this.kill(musicOrigin,musicManifestURL);}}}
if(!Service.query('isAlerting')&&!Service.query('onCall')&&!Service.query('getTopMostWindow').isHomescreen){Service.request('freeCallscreenWindow');}
if(!Service.query('getTopMostWindow').isHomescreen){Service.request('killHomescreen');}},publish:function awm_publish(event,detail){var evt=document.createEvent('CustomEvent');evt.initCustomEvent(event,true,false,detail||this);this.debug('publish: '+event);window.dispatchEvent(evt);},_updateActiveApp:function awm__changeActiveApp(instanceID){var appHasChanged=(this._activeApp!==this._apps[instanceID]);this.debug(appHasChanged,this.activated,this._activeApp);var activated=false;if(!this.activated&&appHasChanged&&!this._activeApp){activated=true;}else if(!appHasChanged&&this._activeApp&&!this.activated){activated=true;}
this._activeApp=this._apps[instanceID];if(!this._activeApp){this.debug('no active app alive: '+instanceID);return;}
var fullScreenLayout=this._activeApp.isFullScreenLayout();this.screen.classList.toggle('fullscreen-layout-app',fullScreenLayout);this._activeApp.resize();if(appHasChanged){this.publish('activeappchanged');}
this.debug('=== Active app now is: ',(this._activeApp.name||this._activeApp.origin),'===');if(activated){this.publish(this.EVENT_PREFIX+'-activated');}},broadcastMessage:function awm_broadcastMessage(message,detail){for(var id in this._apps){this._apps[id].broadcast(message,detail);}},onShowWindow:function awm_onShowWindow(detail){var activeApp=this._activeApp;var launchHomescreen=()=>{var home=homescreenWindowManager.getHomescreen();if(home){if(home.isActive()){home.setVisible(true);}else{this.display();}}};detail=detail?detail:{};var{activity,notificationId}=detail;if(activity||notificationId){if(activeApp&&!activeApp.isHomescreen){activeApp.setVisible(true);if(activity){this.fireActivity(activity);}else if(notificationId){this.fireNotificationClicked(notificationId);}}else{if(activity){this.fireActivity(activity);}else if(notificationId){launchHomescreen();this.fireNotificationClicked(notificationId);}}}else{if(activeApp&&!activeApp.isHomescreen){activeApp.setVisible(true);}else{launchHomescreen();}}},fireActivity:function awm_fireActivity(activityContent){var a=new window.MozActivity(activityContent);a.onerror=function ls_activityError(){console.log('MozActivity: activity error.');};},fireNotificationClicked:function awm_fireNotificationClicked(notificationId){var event=document.createEvent('CustomEvent');event.initCustomEvent('mozContentNotificationEvent',true,true,{type:'desktop-notification-click',id:notificationId});window.dispatchEvent(event);window.dispatchEvent(new CustomEvent('notification-clicked',{detail:{id:notificationId}}));}};exports.AppWindowManager=AppWindowManager;}(window));