'use strict';(function(exports){var _id=0;function AppAuthenticationDialog(app){this.app=app;this._event=null;this.containerElement=app.element;this.instanceID=_id++;this._injected=false;this.app.element.addEventListener('mozbrowserusernameandpasswordrequired',this);}
AppAuthenticationDialog.prototype=Object.create(window.BaseUI.prototype);AppAuthenticationDialog.prototype.CLASS_NAME='AuthenticationDialog';AppAuthenticationDialog.prototype.EVENT_PREFIX='authdialog';AppAuthenticationDialog.prototype.ELEMENT_PREFIX='authentication-dialog-';AppAuthenticationDialog.prototype.elements=null;AppAuthenticationDialog.prototype._event=null;AppAuthenticationDialog.prototype._fetchElements=function aad__fetchElements(){this.element=document.getElementById(this.CLASS_NAME+this.instanceID);this.elements={};var toCamelCase=function toCamelCase(str){return str.replace(/\-(.)/g,function replacer(str,p1){return p1.toUpperCase();});};this.elementClasses=['http-authentication-message','http-username-input','http-password-input','http-show-password-checkbox'];this.elementClasses.forEach(function createElementRef(name){this.elements[toCamelCase(name)]=this.element.querySelector('.'+this.ELEMENT_PREFIX+name);},this);this.focusable=Array.prototype.slice.call(this.element.querySelectorAll('.authentication-dialog input'));};AppAuthenticationDialog.prototype.view=function aad_view(){var id=this.CLASS_NAME+this.instanceID;return`<section class="authentication-dialog skin-organic" id="${id}"
      role="region">
      <h1 class="authentication-dialog-http-authentication-header"
          data-l10n-id="signIn"></h1>
      <p class="authentication-dialog-http-authentication-message">
      </p>
      <label>
        <span data-l10n-id="username" class="p-sec"></span>
        <input type="text"
               class="authentication-dialog-http-username-input p-sec" />
      </label>
      <label>
        <span data-l10n-id="password" class="p-sec"></span>
        <input type="password"
               class="authentication-dialog-http-password-input p-sec" />
      </label>
      <label class="checkbox">
        <span data-l10n-id="show-password" class="p-pri"></span>
        <input type="checkbox"
               class="authentication-dialog-http-show-password-checkbox checkbox"/>
        <span data-icon="check-off" ></span>
        <span data-icon="check-on" ></span>
      </label>
    </section>`;};AppAuthenticationDialog.prototype.handleEvent=function(evt){this.debug(' AAD>> got event: '+evt.type);evt.preventDefault();evt.stopPropagation();this._event=evt;if(!this._injected){this.render();this.registerSoftKey();}
this.show();this._injected=true;};AppAuthenticationDialog.prototype.handleKey=function(evt){if(!this.isVisible()||!this._event){return;}
this.debug(' AAD>> handleKey: '+evt.key);switch(evt.key){case'ArrowUp':case'ArrowDown':this.move(evt.key);break;case'Enter':this.toggleCheckbox();break;case'SoftLeft':evt.preventDefault();evt.stopPropagation();this.cancelHandler();break;case'SoftRight':evt.preventDefault();evt.stopPropagation();this.confirmHandler();break;}};AppAuthenticationDialog.prototype.softkeyHandler=function(key){if(!this.isVisible()||!this._event){return;}
this.debug(' AAD>> softkeyHandler: '+key.type);};AppAuthenticationDialog.prototype.onfocus=function(evt){this.debug(' AAD>> onfocus: ');evt.target.parentElement.classList.add('focused');};AppAuthenticationDialog.prototype.onblur=function(evt){this.debug(' AAD>> onblur: ');evt.target.parentElement.classList.remove('focused');};AppAuthenticationDialog.prototype.isVisible=function(){return this.element&&this.element.classList.contains('visible');};AppAuthenticationDialog.prototype._registerEvents=function aad__registerEvents(){this.element.addEventListener('keydown',this.handleKey.bind(this));this.focusable.forEach((inputElement)=>{inputElement.addEventListener('focus',this.onfocus.bind(this));inputElement.addEventListener('blur',this.onblur.bind(this));});};AppAuthenticationDialog.prototype._unregisterEvents=function aad__unregisterEvents(){this.app.element.removeEventListener('mozbrowserusernameandpasswordrequired',this);};AppAuthenticationDialog.prototype.registerSoftKey=function(){Service.request('SoftKeyStore:register',{left:'cancel',right:'signIn'},this.element);};AppAuthenticationDialog.prototype.focus=function(){this.debug(' AAD>> focus');var bottomWindow=this.app.getBottomMostWindow();var topmostui=Service.query('getTopMostUI');var shouldFocus=(Service.query('getTopMostWindow')===this.app&&topmostui&&topmostui.name===bottomWindow.HIERARCHY_MANAGER);if(shouldFocus&&this.focusElement){this.focusElement.focus();}};AppAuthenticationDialog.prototype.show=function aad_show(){var evt=this._event;var elements=this.elements;this.app.setVisibleForScreenReader(false);this.element.classList.add('visible');this.debug(' AAD>> showing');navigator.mozL10n.setAttributes(elements.httpAuthenticationMessage,'http-authentication-message2',{host:evt.detail.host});elements.httpUsernameInput.value='';elements.httpPasswordInput.value='';this.focusElement=this.focusable[0];this.debug(this.focusElement);Service.request('focus');};AppAuthenticationDialog.prototype.hide=function aad_hide(){this.elements.httpUsernameInput.blur();this.elements.httpPasswordInput.blur();this.elements.httpShowPasswordCheckbox.blur();this.app.setVisibleForScreenReader(true);this.element.classList.remove('visible');if(this.app){Service.request('focus');}
this.debug(' AAD>> hided');};AppAuthenticationDialog.prototype.move=function add_mode(key){var index=this.focusable.indexOf(document.activeElement);if(index===-1){return;}
if(key==='ArrowDown'){this.focusElement=this.focusable[(index+1)%this.focusable.length];}else if(key==='ArrowUp'){this.focusElement=this.focusable[(index-1+this.focusable.length)%this.focusable.length];}
this.debug(this.focusElement);Service.request('focus');};AppAuthenticationDialog.prototype.confirmHandler=function aad_confirmHandler(){var elements=this.elements;var evt=this._event;this.hide();evt.detail.authenticate(elements.httpUsernameInput.value,elements.httpPasswordInput.value);this._event=null;};AppAuthenticationDialog.prototype.cancelHandler=function aad_cancelHandler(){var evt=this._event;this.hide();evt.detail.cancel();this._event=null;};AppAuthenticationDialog.prototype.toggleCheckbox=function(){if(document.activeElement===this.elements.httpShowPasswordCheckbox){this.elements.httpShowPasswordCheckbox.checked=!this.elements.httpShowPasswordCheckbox.checked;var passwordFieldType=!!this.elements.httpShowPasswordCheckbox.checked?'text':'password';var dataIcon=!!this.elements.httpShowPasswordCheckbox.checked?'check-on':'check-off';this.elements.httpPasswordInput.setAttribute('type',passwordFieldType);this.elements.httpPasswordInput.setAttribute('data-icon',dataIcon);}};exports.AppAuthenticationDialog=AppAuthenticationDialog;}(window));