'use strict';(function(exports){var ENABLE_IN_APP_SHEET=false;SettingsListener.observe('in-app-sheet.enabled',false,function(value){ENABLE_IN_APP_SHEET=value;});var ChildWindowFactory=function ChildWindowFactory(app){this.app=app;this.app.element.addEventListener('mozbrowseropenwindow',this);this.app.element.addEventListener('_launchactivity',this);};ChildWindowFactory.prototype.destroy=function(){this.app.element.removeEventListener('mozbrowseropenwindow',this);this.app.element.removeEventListener('_launchactivity',this);this.app=null;};ChildWindowFactory.prototype.handleEvent=function cwf_handleEvent(evt){if(Service.query('getTopMostWindow')&&evt.type!=='_closing'&&evt.type!=='_closed'){Service.query('getTopMostWindow').cacheSpatialNavigationIfNeeded();}
if(evt.type==='_launchactivity'){this.createActivityWindow(evt);return;}
if(evt.detail&&evt.detail.instanceID&&evt.detail.instanceID!==this.app.instanceID){if(this['_handle_child_'+evt.type]){this['_handle_child_'+evt.type](evt);}
return;}
if(this.isHomescreen){return;}
if(evt.detail.name=='_blank'&&!window.Service.runningFTU&&evt.detail.features!=='attention'){this.createNewWindow(evt);evt.stopPropagation();return;}
if(evt.detail.isApp){this.app.publish('openwindow',{manifestURL:evt.detail.name,url:evt.detail.url,timestamp:Date.now()});evt.stopPropagation();return;}
var caught=false;switch(evt.detail.features){case'dialog':if(/^(app|http|https):\/\//i.test(evt.detail.url)){caught=this.createPopupWindow(evt);}else{caught=this.launchActivity(evt);}
break;case'attention':if(!this.createAttentionWindow(evt)){this.createPopupWindow(evt);}
break;case'mozhaidasheet':caught=this.createChildWindow(evt);break;default:if(ENABLE_IN_APP_SHEET){caught=this.createChildWindow(evt);}else{caught=this.createPopupWindow(evt);}
break;}
if(caught){evt.stopPropagation();}};ChildWindowFactory.prototype.createPopupWindow=function(evt){if(this.app.frontWindow&&(this.app.frontWindow.isTransitioning()||this.app.frontWindow.isActive())){return false;}
if(/^(http|https):\/\//i.test(evt.detail.url)){evt.detail.frameElement.removeAttribute('mozapp');}
var configObject={url:evt.detail.url,name:this.app.name,iframe:evt.detail.frameElement,origin:this.app.origin,rearWindow:this.app};var childWindow=new PopupWindow(configObject);childWindow.element.addEventListener('_closing',this);childWindow.element.addEventListener('_closed',this);this.child=childWindow;childWindow.open();setBrowserProperty(this.app.browser.element,'canTakeFocus',false);return true;};ChildWindowFactory.prototype._sameOrigin=function(url1,url2){var a=url1.split('/');var b=url2.split('/');return(a[0]===b[0]&&a[2]===b[2]);};ChildWindowFactory.prototype.createNewWindow=function(evt){if(!this.app.isActive()||this.app.isTransitioning()){return false;}
var configObject={url:evt.detail.url,name:evt.detail.name,iframe:evt.detail.frameElement};window.dispatchEvent(new CustomEvent('openwindow',{detail:configObject}));return true;};ChildWindowFactory.prototype.createChildWindow=function(evt){if(!this.app.isActive()||this.app.isTransitioning()){return false;}
var configObject={url:evt.detail.url,name:this.app.name,iframe:evt.detail.frameElement,origin:this.app.origin};if(this._sameOrigin(this.app.origin,evt.detail.url)){configObject.manifestURL=this.app.manifestURL;configObject.previousWindow=this.app;}else{configObject.name='';configObject.origin=evt.detail.url;}
var childWindow=new AppWindow(configObject);childWindow.requestOpen();return true;};ChildWindowFactory.prototype.createAttentionWindow=function(evt){if(!this.app||!this.app.hasPermission('attention')){console.error('Cannot create attention window. '+'Invalid of underprivileged app');return false;}
if(document.mozFullScreen){document.mozCancelFullScreen();}
var attentionFrame=evt.detail.frameElement;var attention=new AttentionWindow({iframe:attentionFrame,url:evt.detail.url,name:evt.detail.name,manifestURL:this.app.manifestURL,origin:this.app.origin,parentWindow:this.app});this.app.attentionWindow=attention;attention.requestOpen();return true;};ChildWindowFactory.prototype._handle_child__closing=function(){if(!this.app.isVisible()||this.app._killed){return;}
this.app.setOrientation();if(this.child){this.child.element.removeEventListener('_closing',this);}};ChildWindowFactory.prototype._handle_child__closed=function(){if(this.child){this.child.element.removeEventListener('_closed',this);this.child=null;}
Service.request('focus');};ChildWindowFactory.prototype.createActivityWindow=function(evt){var configuration=evt.detail;var top=this.app.getTopMostWindow();if(top.manifestURL==configuration.manifestURL&&top.url==configuration.url){return;}
if(configuration.parentAppPageURL){var self=this;Service.request('getActiveWindowByPageUrl',configuration.parentAppPageURL,this).then(function(initiator){var activityOpenerWindowStyle=window.getComputedStyle(top.element);var activityOpenerZIndex=((activityOpenerWindowStyle!==null)?activityOpenerWindowStyle.zIndex:null);var activityInitiatorWindowStyle=null;var activityInitiatorZIndex=null;if(initiator!==null){activityInitiatorWindowStyle=window.getComputedStyle(initiator.element);activityInitiatorZIndex=((activityInitiatorWindowStyle!==null)?activityInitiatorWindowStyle.zIndex:null);if(activityOpenerZIndex<activityInitiatorZIndex){configuration.opener_zIndexToRestore=activityOpenerZIndex;configuration.opener_origin=top.origin;configuration.opener_manifestURL=top.manifestURL;top.element.style.zIndex=activityInitiatorZIndex;}}
self.openNewActivity(top,configuration);});}else{this.openNewActivity(top,configuration);}};ChildWindowFactory.prototype.openNewActivity=function(top,configuration){top.setNFCFocus(false);var activity=new ActivityWindow(configuration,top);activity.element.addEventListener('_closing',this);activity.element.addEventListener('_closed',this);this.child=activity;activity.open();top._setVisibleForScreenReader(false);};ChildWindowFactory.prototype.launchActivity=function(evt){var activity=new MozActivity({name:'view',data:{type:'url',url:evt.detail.url}});activity.onerror=function(){this.app.debug('view activity error:'+activity.error.name+evt.detail.url);};return true;};exports.ChildWindowFactory=ChildWindowFactory;}(window));