'use strict';var CrashReporter=(function(){var _=navigator.mozL10n.get;var settings=navigator.mozSettings;var screen=document.getElementById('screen');var crashInfo=document.getElementById('crash-info');var dialog=document.getElementById('crash-dialog');var active=false;var softkeyparams=null;var crashedAppName=null;var showReportButton=false;var shownOnce=false;SettingsListener.observe('app.reportCrashes','ask',function handleCrashSetting(value){showReportButton=(value!='always'&&value!='never');});function showDialog(crashID,isChrome){active=true;window.addEventListener('keydown',handlekey);shownOnce=true;var elem=document.getElementById('crash-dialog-title');if(isChrome){navigator.mozL10n.setAttributes(elem,'crash-dialog-os2');}else{navigator.mozL10n.setAttributes(elem,'crash-dialog-app',{name:crashedAppName||_('crash-dialog-app-noname')});}
var params={menuClassName:'menu-button',header:{l10nId:''},items:[{name:'Cancel',l10nId:'cancel',priority:1,method:function(){removeDialog();}},{name:'Send Report',l10nId:'tcl-send-report',priority:3,method:function(){removeDialog();submitCrash(crashID);if(checkbox.checked){settings.createLock().set({'app.reportCrashes':'always'});settings.createLock().set({'crashReporter.dialogShown':true});}}},]};softkeyparams=params;screen.classList.add('crash-dialog');publish('-activated');}
var checkbox=document.getElementById('always-send');var checkboxLabel=document.getElementById('always-report');function onCheckboxClick(){if(checkbox.checked){checkbox.checked=false;}else{checkbox.checked=true;}};var crashInfoLink=document.getElementById('crash-info-link');function onLearnMoreClick(){var params={menuClassName:'menu-button',header:{l10nId:''},items:[{name:'Cancel',l10nId:'tcl-cancelButtonId',priority:1,method:function(){SoftkeyHelper.hide();console.log("berton remove learn-more");dialog.classList.remove('learn-more');SoftkeyHelper.init(softkeyparams,function(){removeDialog();});}}]};SoftkeyHelper.init(params,function(){SoftkeyHelper.hide();dialog.classList.remove('learn-more');SoftkeyHelper.init(softkeyparams,function(){removeDialog();});});dialog.classList.add('learn-more');};function handleEnterKey(){if(crashInfoLink.classList.contains('focus')){onLearnMoreClick();}else if(checkboxLabel.classList.contains('focus')){onCheckboxClick();}}
function publish(event){let evt=new CustomEvent('crash-reporter'+event,{bubbles:true,detail:this});window.dispatchEvent(evt);}
function handleEndKey(){removeDialog();}
function removeDialog(){SoftkeyHelper.hide();screen.classList.remove('crash-dialog');var dialog=document.getElementById('crash-dialog');dialog.parentNode.removeChild(dialog);window.removeEventListener('keydown',handlekey);active=false;publish('-deactivated');Service.request('focus');}
function showBanner(crashID,isChrome){var appName=crashedAppName||_('crash-dialog-app-noname');var message=isChrome?_('crash-banner-os2'):_('crash-banner-app',{name:appName});Service.request('SystemToaster:show',{title:message});}
function deleteCrash(crashID){var event=document.createEvent('CustomEvent');event.initCustomEvent('mozContentEvent',true,true,{type:'delete-crash',crashID:crashID});window.dispatchEvent(event);}
function submitCrash(crashID){var event=document.createEvent('CustomEvent');event.initCustomEvent('mozContentEvent',true,true,{type:'submit-crash',crashID:crashID});window.dispatchEvent(event);}
function handleCrash(crashID,isChrome){var dialogReq=settings.createLock().get('crashReporter.dialogShown');dialogReq.onsuccess=function dialogShownSuccess(){var dialogShown=dialogReq.result['crashReporter.dialogShown'];console.log("crash crashReporter.dialogShown  dialogShown is "+dialogShown);if(!dialogShown&&!shownOnce){showDialog(crashID,isChrome);}else{showBanner(crashID,isChrome);}};}
function setAppName(name){crashedAppName=name;}
window.addEventListener('mozChromeEvent',function handleChromeEvent(e){if(e.detail.type=='handle-crash'){handleCrash(e.detail.crashID,e.detail.chrome);}});function handleAppCrash(e){var app=e.detail;if(app.isActive()){setAppName(app.name);}}
function handlekey(e){switch(e.key){case'MozHomeScreen':removeDialog();break;case'ArrowUp':if(dialog.classList.contains('learn-more')){e.preventDefault();e.stopPropagation();crashInfo.scrollBy(0,-50);}
break;case'ArrowDown':if(dialog.classList.contains('learn-more')){e.preventDefault();e.stopPropagation();crashInfo.scrollBy(0,50);}
break;case'EndCall':case'BackSpace':e.preventDefault();e.stopPropagation();handleEndKey();break;case'Enter':e.preventDefault();e.stopPropagation();handleEnterKey();break;}}
function setHierarchy(value){if(value){focus();}else if(active){SoftkeyHelper.hide();}}
function focus(){dialog.focus();if(dialog.classList.contains('learn-more')){onLearnMoreClick();}else{SoftkeyHelper.init(softkeyparams,function(){removeDialog();});}}
function isActive(){return active;}
window.addEventListener('appcrashed',handleAppCrash);window.addEventListener('activitycrashed',handleAppCrash);window.addEventListener('homescreencrashed',handleAppCrash);window.addEventListener('searchcrashed',handleAppCrash);return{name:'CrashReporter',EVENT_PREFIX:'crash-reporter',setHierarchy:setHierarchy,handleCrash:handleCrash,handleAppCrash:handleAppCrash,isActive:isActive,setAppName:setAppName};})();Service.request('registerHierarchy',CrashReporter);