'use strict';var NDEFUtils={DEBUG:false,_debug:function _debug(msg,optObject){if(this.DEBUG){this._logVisibly(msg,optObject);}},_logVisibly:function _logVisibly(msg,optObject){var output='[NDEFUtils]: '+msg;if(optObject){output+=JSON.stringify(optObject);}
console.log(output);},parseHandoverNDEF:function parseHandoverNDEF(ndefMsg){try{return this._doParseHandoverNDEF(ndefMsg);}catch(err){this._logVisibly(err);return null;}},_doParseHandoverNDEF:function doParseHandoverNDEF(msg){var nfcUtils=new NfcUtils();var hRecordBuffer=new NfcBuffer(msg[0].payload);var version=hRecordBuffer.getOctet();var h={majorVersion:version>>>4,minorVersion:version&0x0f,type:nfcUtils.toUTF8(msg[0].type),ac:[]};if(msg[0].tnf!==NDEF.TNF_WELL_KNOWN){throw Error('Expected Well Known TNF in Hs/Hr record');}
if(['Hs','Hr'].indexOf(h.type)<0){throw Error('Record "'+h.type+'" not supported.');}
var hRecord=nfcUtils.parseNDEF(hRecordBuffer);if(!hRecord){throw Error('Could not parse embedded NDEF in Hr/Hs record');}
if(hRecordBuffer.offset<msg[0].payload.length){throw Error('Embedded NDEF payload contains extraneous bytes');}
for(var i=0;i<hRecord.length;i+=1){var type=nfcUtils.toUTF8(hRecord[i].type);if('ac'===type){h.ac.push(this._parseAlternativeCarrier(hRecord[i].payload,msg));}else if('cr'===type){h.cr=this._parseCollisionResolution(hRecord[i].payload);}}
if('Hr'===h.type&&!h.cr){throw Error('Collision resolution record missing');}
return h;},_parseAlternativeCarrier:function _parseAlternativeCarrier(bytes,msg){var nfcUtils=new NfcUtils();var b=new NfcBuffer(bytes);var ac={cps:b.getOctet()&0x03};var recordId=b.getOctetArray(b.getOctet());ac.cdr=msg.filter(function(record){return nfcUtils.equalArrays(record.id,recordId);}.bind(this))[0];if(!ac.cdr){throw Error('Could not find record with given id');}
return ac;},_parseCollisionResolution:function _parseCollisionResolution(bytes){if(bytes.length!==2){throw Error('Expected random number in Collision Resolution Record');}
return(bytes[0]<<8)|bytes[1];},searchForBluetoothAC:function searchForBluetoothAC(h){var nfcUtils=new NfcUtils();for(var i=0;i<h.ac.length;i++){var cdr=h.ac[i].cdr;if(cdr.tnf===NDEF.TNF_MIME_MEDIA){if(nfcUtils.equalArrays(cdr.type,NDEF.MIME_BLUETOOTH_OOB)){return cdr;}}}
return null;},parseBluetoothSSP:function parseBluetoothSSP(cdr){var nfcUtils=new NfcUtils();if(!cdr||!cdr.payload||cdr.payload.length<8){return null;}
var btssp={};var buf=new NfcBuffer(cdr.payload);var btsspLen=buf.getOctet()|(buf.getOctet()<<8);if(cdr.payload.length!==btsspLen){this._debug('Invalid BT SSP record. Length indicated:'+
btsspLen+', actual length: '+cdr.payload.length);return null;}
btssp.mac=this.formatMAC(buf.getOctetArray(6));while(buf.offset!=cdr.payload.length){var len=buf.getOctet()-1;var type=buf.getOctet();if(buf.offset+len>buf.uint8array.length){this._debug('EIR field '+type+' indicated length='+
len+', but only '+(buf.uint8array.length-buf.offset)+' characters left in buffer.');return null;}
switch(type){case 0x08:case 0x09:var n=buf.getOctetArray(len);btssp.localName=nfcUtils.toUTF8(n);break;default:buf.skip(len);break;}}
return btssp;},formatMAC:function formatMAC(mac){if(!mac||mac.length!==6){return null;}
var res=[];for(var i=0;i<6;i+=1){var m=mac[i].toString(16);res.unshift(m.length===1?'0'+m:m);}
return res.join(':').toUpperCase();},parseMAC:function parseMAC(mac){if(!mac||!/^([0-9A-F]{2}:){6}$/i.test(mac+':')){return null;}
var macVals=mac.split(':');var m=[];for(var i=5;i>=0;i-=1){m.push(parseInt(macVals[i],16));}
return m;},validateCPS:function validateCPS(cps){var allowedValues=[NDEF.CPS_INACTIVE,NDEF.CPS_ACTIVE,NDEF.CPS_ACTIVATING,NDEF.CPS_UNKNOWN];return(allowedValues.indexOf(cps)>=0);},encodeHandoverRequest:function encodeHandoverRequest(mac,cps){var nfcUtils=new NfcUtils();var m=this.parseMAC(mac);if(!m){this._debug('Invalid BT MAC address: '+mac);return null;}
if(!this.validateCPS(cps)){this._debug('Invalid CPS: '+cps);return null;}
var rndMSB=Math.floor(Math.random()*0xff)&0xff;var rndLSB=Math.floor(Math.random()*0xff)&0xff;var OOBLength=2+m.length;var OOB=[OOBLength,0].concat(m);var pid=nfcUtils.fromUTF8('0');var hr=[new MozNDEFRecord({tnf:NDEF.TNF_WELL_KNOWN,type:NDEF.RTD_HANDOVER_REQUEST,payload:new Uint8Array([0x12,0x91,0x02,0x02,0x63,0x72,rndMSB,rndLSB,0x51,0x02,0x04,0x61,0x63,cps,0x01,pid[0],0x00])}),new MozNDEFRecord({tnf:NDEF.TNF_MIME_MEDIA,type:NDEF.MIME_BLUETOOTH_OOB,id:pid,payload:new Uint8Array(OOB)})];return hr;},encodeHandoverSelect:function encodeHandoverSelect(mac,cps,btDeviceName){var nfcUtils=new NfcUtils();var m=this.parseMAC(mac);if(!m){this._debug('Invalid BT MAC address: '+mac);return null;}
if(!this.validateCPS(cps)){this._debug('Invalid CPS: '+cps);return null;}
var OOBLength=2+m.length;var OOB=[OOBLength,0].concat(m);if(btDeviceName){var EIRLength=1+btDeviceName.length;OOB[0]+=EIRLength+1;OOB=OOB.concat(EIRLength,0x09,Array.apply([],btDeviceName));}
var pid=nfcUtils.fromUTF8('0');var hs=[new MozNDEFRecord({tnf:NDEF.TNF_WELL_KNOWN,type:NDEF.RTD_HANDOVER_SELECT,payload:new Uint8Array([0x12,0xD1,0x02,0x04,0x61,0x63,cps,0x01,pid[0],0x00])}),new MozNDEFRecord({tnf:NDEF.TNF_MIME_MEDIA,type:NDEF.MIME_BLUETOOTH_OOB,id:pid,payload:new Uint8Array(OOB)})];return hs;},encodeEmptyHandoverSelect:function encodeEmptyHandoverSelect(){var hs=[new MozNDEFRecord({tnf:NDEF.TNF_WELL_KNOWN,type:NDEF.RTD_HANDOVER_SELECT,payload:new Uint8Array([0x12])})];return hs;}};