'use strict';(function(exports){var DEBUG=false;var NfcManager=function(){};NfcManager.prototype={NFC_HW_STATE:{DISABLING:'nfcDisabling',OFF:'nfcOff',ENABLING:'nfcEnabling',ON:'nfcOn',ENABLE_DISCOVERY:'nfcEnableDiscovery',DISABLE_DISCOVERY:'nfcDisableDiscovery'},_hwState:null,start:function nm_start(){this._debug('Starting NFC Manager');this._hwState=this.NFC_HW_STATE.OFF;window.navigator.mozSetMessageHandler('nfc-manager-tech-discovered',(msg)=>this._handleTechDiscovered(msg));window.navigator.mozSetMessageHandler('nfc-manager-tech-lost',(msg)=>this._handleTechLost(msg));window.addEventListener('screenchange',this);window.addEventListener('lockscreen-appopened',this);window.addEventListener('lockscreen-appclosed',this);this._onSettingsChanged=(enabled)=>this._nfcSettingsChanged(enabled);SettingsListener.observe('nfc.enabled',false,this._onSettingsChanged);this._onDebugChanged=(enabled)=>{DEBUG=enabled;};SettingsListener.observe('nfc.debugging.enabled',false,this._onDebugChanged);SettingsListener.getSettingsLock().set({'nfc.status':'disabled'});},stop:function nm_stop(){this._debug('Stopping NFC Manager');window.navigator.mozSetMessageHandler('nfc-manager-tech-discovered',null);window.navigator.mozSetMessageHandler('nfc-manager-tech-lost',null);window.removeEventListener('screenchange',this);window.removeEventListener('activeappchanged',this);window.removeEventListener('lockscreen-appopened',this);window.removeEventListener('lockscreen-appclosed',this);SettingsListener.unobserve('nfc.enabled',this._onSettingsChanged);SettingsListener.unobserve('nfc.debugging.enabled',this._onDebugChanged);},isActive:function nm_isActive(){return this._hwState===this.NFC_HW_STATE.ON||this._hwState===this.NFC_HW_STATE.ENABLE_DISCOVERY||this._hwState===this.NFC_HW_STATE.DISABLE_DISCOVERY;},isInTransition:function nm_isInTransition(){return this._hwState===this.NFC_HW_STATE.ENABLING||this._hwState===this.NFC_HW_STATE.DISABLING;},_handleTechDiscovered:function nm_handleTechDiscovered(msg){this._debug('Technology Discovered: '+JSON.stringify(msg));msg=msg||{};msg.records=Array.isArray(msg.records)?msg.records:[];window.dispatchEvent(new CustomEvent('nfc-tech-discovered'));window.navigator.vibrate([25,50,125]);if(NfcHandoverManager.tryHandover(msg.records,msg.peer)){return;}
if(msg.records.length){this._fireNDEFDiscovered(msg.records);}else if(msg.peer){this.checkP2PRegistration();}else{this._logVisibly('Got tag without NDEF records, ignoring.');}},_handleTechLost:function nm_handleTechLost(msg){this._debug('Technology Lost: '+JSON.stringify(msg));window.navigator.vibrate([125,50,25]);window.dispatchEvent(new CustomEvent('nfc-tech-lost'));window.removeEventListener('shrinking-sent',this);window.dispatchEvent(new CustomEvent('shrinking-stop'));},handleEvent:function nm_handleEvent(evt){var state;switch(evt.type){case'lockscreen-appopened':case'lockscreen-appclosed':case'screenchange':if(!this.isActive()){return;}
state=(ScreenManager.screenEnabled&&!Service.query('locked'))?this.NFC_HW_STATE.ENABLE_DISCOVERY:this.NFC_HW_STATE.DISABLE_DISCOVERY;if(state===this._hwState){return;}
this._changeHardwareState(state);break;case'shrinking-sent':window.removeEventListener('shrinking-sent',this);this.dispatchP2PUserResponse();window.dispatchEvent(new CustomEvent('shrinking-stop'));break;}},_nfcSettingsChanged:function nm_nfcSettingsChanged(enabled){this._debug('_nfcSettingsChanged, nfc.enabled: '+enabled);if(this.isActive()===enabled||this.isInTransition()){this._debug('_nfcSettingsChanged ignoring settings change');return;}
var state=!enabled?this.NFC_HW_STATE.DISABLING:(Service.query('locked')?this.NFC_HW_STATE.DISABLE_DISCOVERY:this.NFC_HW_STATE.ENABLING);this._changeHardwareState(state);},_changeHardwareState:function nm_changeHardwareState(state){this._debug('_changeHardwareState - state : '+state);this._hwState=state;var nfcdom=window.navigator.mozNfc;if(!nfcdom){return;}
var promise;switch(state){case this.NFC_HW_STATE.DISABLING:promise=nfcdom.powerOff();SettingsListener.getSettingsLock().set({'nfc.status':'disabling'});break;case this.NFC_HW_STATE.DISABLE_DISCOVERY:promise=nfcdom.stopPoll('mode_screen_off');break;case this.NFC_HW_STATE.ENABLING:promise=nfcdom.startPoll();SettingsListener.getSettingsLock().set({'nfc.status':'enabling'});break;case this.NFC_HW_STATE.ENABLE_DISCOVERY:promise=nfcdom.startPoll();break;}
promise.then(()=>{this._debug('_changeHardwareState '+state+' success');if(this.isInTransition()){this._handleNFCOnOff(this._hwState===this.NFC_HW_STATE.ENABLING);}}).catch(e=>{this._logVisibly('_changeHardwareState '+state+' error '+e);if(e.message==="ErrorConnect"){this._handleNFCOnOff(false);return;}
if(this.isInTransition()){this._handleNFCOnOff(this._hwState!==this.NFC_HW_STATE.ENABLING);}});},_handleNFCOnOff:function nm_handleNFCOnOff(isOn){this._debug('_handleNFCOnOf is on:'+isOn);this._hwState=(isOn)?this.NFC_HW_STATE.ON:this.NFC_HW_STATE.OFF;SettingsListener.getSettingsLock().set({'nfc.status':(isOn)?'enabled':'disabled'});var event=new CustomEvent('nfc-state-changed',{detail:{active:isOn}});window.dispatchEvent(event);},_triggerP2PUI:function nm_triggerP2PUI(){var evt=new CustomEvent('check-p2p-registration-for-active-app',{bubbles:true,cancelable:false,detail:this});window.dispatchEvent(evt);},checkP2PRegistration:function nm_checkP2PRegistration(){var nfcdom=window.navigator.mozNfc;if(!nfcdom){return;}
var activeApp=window.Service.currentApp;var manifestURL=activeApp.getTopMostWindow().manifestURL||window.Service.manifestURL;var promise=nfcdom.checkP2PRegistration(manifestURL);promise.then(result=>{if(result){if(activeApp.isTransitioning()||activeApp.isSheetTransitioning()){return;}
window.dispatchEvent(new CustomEvent('shrinking-start'));window.addEventListener('shrinking-sent',this);}else{this._logVisibly('CheckP2PRegistration failed');window.removeEventListener('shrinking-sent',this);window.dispatchEvent(new CustomEvent('shrinking-stop'));}});},dispatchP2PUserResponse:function nm_dispatchP2PUserResponse(){var nfcdom=window.navigator.mozNfc;if(!nfcdom){return;}
var activeApp=window.Service.currentApp;var manifestURL=activeApp.getTopMostWindow().manifestURL||window.Service.manifestURL;nfcdom.notifyUserAcceptedP2P(manifestURL);},_fireNDEFDiscovered:function nm_fireNDEFDiscovered(records){this._debug('_fireNDEFDiscovered: '+JSON.stringify(records));var smartPoster=this._getSmartPoster(records);var record=smartPoster||records[0]||{tnf:NDEF.TNF_EMPTY};var data=NDEF.payload.decode(record.tnf,record.type,record.payload);var options=this._createNDEFActivityOptions(data);if(data!==null){options.data.records=records;}
this._debug('_fireNDEFDiscovered activity options: ',options);var activity=new MozActivity(options);activity.onerror=()=>{this._logVisibly('Firing nfc-ndef-discovered activity failed');};},_getSmartPoster:function nm_getSmartPoster(records){var nfcUtils=new NfcUtils();if(!Array.isArray(records)||!records.length){return null;}
var smartPosters=records.filter(function isSmartPoster(r){return nfcUtils.equalArrays(r.type,NDEF.RTD_SMART_POSTER);});if(smartPosters.length&&records[0].tnf===NDEF.TNF_WELL_KNOWN&&(nfcUtils.equalArrays(records[0].type,NDEF.RTD_URI)||nfcUtils.equalArrays(records[0].type,NDEF.RTD_SMART_POSTER))){return smartPosters[0];}
return null;},_createNDEFActivityOptions:function nm_createNDEFActivityOptions(payload){var options={name:'nfc-ndef-discovered',data:{}};if(payload===null){return options;}
if(payload.type==='uri'){if(payload.uri.indexOf('tel:')===0){options.name='dial';options.data.type='webtelephony/number';options.data.number=payload.uri.substring(4);options.data.uri=payload.uri;}else if(payload.uri.indexOf('mailto:')===0){options.name='new';options.data.type='mail';options.data.url=payload.uri;}else if(payload.uri.indexOf('http://')===0||payload.uri.indexOf('https://')===0||payload.uri.indexOf('data:text/html')===0){options.name='view';options.data.type='url';options.data.url=payload.uri;}else{options.data=payload;}}else if(payload.type==='smartposter'&&(payload.uri.indexOf('http://')===0||payload.uri.indexOf('https://')===0)){options.name='view';options.data=payload;options.data.type='url';options.data.url=payload.uri;delete options.data.uri;}else if(payload.type==='text/vcard'){options.name='import';options.data=payload;}else{options.data=payload;}
if(options.name!=='nfc-ndef-discovered'){options.data.src='nfc';}
return options;},_debug:function nm_debug(msg,optObject){if(DEBUG){this._logVisibly(msg,optObject);}},_logVisibly:function nm_logVisibly(msg,optObject){var output='[NfcManager]: '+msg;if(optObject){output+=JSON.stringify(optObject);}
console.log(output);}};exports.NfcManager=NfcManager;}(window));