'use strict';(function(exports){var DELAY_TO_KILL_SEARCH_WINDOW=1000;function Rocketbar(){this.enabled=false;this.focused=false;this.active=false;this._port=null;this._wasClicked=false;this._pendingMessage=null;this.body=document.body;this.screen=document.getElementById('screen');this.rocketbar=document.getElementById('rocketbar');this.form=document.getElementById('rocketbar-form');this.input=document.getElementById('rocketbar-input');this.results=document.getElementById('rocketbar-results');this.backdrop=document.getElementById('rocketbar-backdrop');this.start();this._latestInputValue=null;this._isReactivated=false;}
Rocketbar.prototype={EVENT_PREFIX:'rocketbar',name:'Rocketbar',isClosing:false,publish:function(name){window.dispatchEvent(new CustomEvent(this.EVENT_PREFIX+name,{detail:this}));},isActive:function(){return this.active;},getActiveWindow:function(){return this.isActive()?this.searchWindow:null;},setHierarchy:function(active){if(active&&(!this.searchWindow||(this.searchWindow&&!this.searchWindow.isFocused()))){this.focus();}
this.searchWindow&&this.searchWindow.setVisibleForScreenReader(active);},start:function(){this.addEventListeners();this.enabled=true;Service.request('registerHierarchy',this);},activate:function(){if(this.isClosing){return Promise.reject();}
this._activateCall=new Promise(resolve=>{if(this.active){resolve();return;}
this.active=true;this.rocketbar.classList.add('active');this.form.classList.remove('hidden');this.screen.classList.add('rocketbar-focused');var searchLoaded=false;var transitionEnded=false;var waitOver=()=>{if(searchLoaded&&transitionEnded){resolve();this._activateCall=null;this.publish('-activated');}};var backdrop=this.backdrop;var finishTransition=()=>{window.dispatchEvent(new CustomEvent('rocketbar-overlayopened'));transitionEnded=true;waitOver();};backdrop.classList.remove('hidden');eventSafety(backdrop,'transitionend',finishTransition,300);this.loadSearchApp().then(()=>{if(this.input.value.length){this.handleInput();}
searchLoaded=true;waitOver();});this.publish('-activating');});if(Service.query('NotificationView.isActive')){this._activateCall.then(this._closeSearch.bind(this));}
return this._activateCall;},deactivate:function(){if(!this.active){return;}
this.active=false;this.isClosing=true;var backdrop=this.backdrop;var self=this;var finish=()=>{this.form.classList.add('hidden');this.rocketbar.classList.remove('active');this.screen.classList.remove('rocketbar-focused');backdrop.classList.add('hidden');eventSafety(backdrop,'transitionend',()=>{window.dispatchEvent(new CustomEvent('rocketbar-overlayclosed'));self.publish('-deactivated');self.isClosing=false;},300);};if(this.focused){eventSafety(window,'keyboardhidden',finish,1000);this.blur();}else{finish();}
this.publish('-deactivating');},addEventListeners:function(){window.addEventListener('apploading',this);window.addEventListener('appforeground',this);window.addEventListener('apptitlechange',this);window.addEventListener('lockscreen-appopened',this);window.addEventListener('appopened',this);window.addEventListener('launchapp',this);window.addEventListener('searchterminated',this);window.addEventListener('global-search-request',this);window.addEventListener('attentionopening',this);window.addEventListener('attentionopened',this);window.addEventListener('activityrequesting',this);window.addEventListener('activityterminated',this);window.addEventListener('searchopened',this);window.addEventListener('searchclosed',this);window.addEventListener('screenchange',this);window.addEventListener('end-key-press',this);this.input.addEventListener('focus',this);this.input.addEventListener('blur',this);this.input.addEventListener('input',this);this.input.addEventListener('keydown',this);this.form.addEventListener('submit',this);this.backdrop.addEventListener('click',this);window.addEventListener('iac-search-results',this);},'_handle_system-resize':function(){if(this.isActive()){this.searchWindow&&this.searchWindow.frontWindow&&this.searchWindow.frontWindow.resize();return false;}
return true;},respondToHierarchyEvent:function(evt){if(this['_handle_'+evt.type]){return this['_handle_'+evt.type](evt);}
return true;},handleEvent:function(e){switch(e.type){case'searchopened':window.addEventListener('open-app',this);break;case'screenchange':if(!Service.query('screenEnabled')&&this.isActive()){if(document.activeElement===this.input){this.handleCancel();}}
break;case'searchclosed':window.removeEventListener('open-app',this);break;case'apploading':case'launchapp':var detail=e.detail;if(detail&&detail.stayBackground){return;}
this._closeSearch();break;case'open-app':if(this.searchWindow&&this.searchWindow.frontWindow){return;}
if(e.detail&&!e.detail.showApp){return;}
case'attentionopening':case'attentionopened':case'appforeground':case'appopened':this._closeSearch();break;case'activityrequesting':if(this.isActive()&&e.detail&&e.detail.name&&(e.detail.name==='voice-input')){this._toggleReactivate(true);}
this._closeSearch();break;case'activityterminated':if(e.detail&&e.detail.manifest&&e.detail.manifest.activities&&e.detail.manifest.activities['voice-input']){this._toggleReactivate(false);}
break;case'lockscreen-appopened':this.handleLock(e);break;case'focus':this.handleFocus(e);break;case'blur':this.handleBlur(e);break;case'input':this.handleInput(e);break;case'keydown':this.handleKeyDown(e);break;case'end-key-press':this.handleCancel();break;case'click':if(e.target==this.backdrop){this._closeSearch();}
break;case'searchterminated':this.handleSearchTerminated(e);break;case'iac-search-results':this.handleSearchMessage(e);break;case'global-search-request':var app=Service.currentApp;var afterActivate;if(app&&!app.isActive()){return;}
if(app&&!app.isBrowser()){this.setInput('');afterActivate=this.focus.bind(this);}else{if(app.config.url.startsWith('app://system.gaiamobile.org')){this.setInput('');}else{if(!this.isClosing){this.setInput(app.config.url);}}
afterActivate=()=>{this.hideResults();setTimeout(()=>{this.focus();this.selectAll();});};}
if(app&&app.appChrome&&!app.appChrome.isMaximized()){app.appChrome.maximize(()=>{this.activate().then(afterActivate);});}else{this.activate().then(afterActivate);}
break;}},setSearchAppURL:function(url){this._searchAppURL=url;this._searchManifestURL=url?url.match(/(^.*?:\/\/.*?\/)/)[1]+'manifest.webapp':'';},setInput:function(input){this.input.value=input;this.rocketbar.classList.toggle('has-text',input.length);},_setSoftKeys:function(){var input=this.input.value;var isFocusOnInput=document.activeElement===this.input;if(isFocusOnInput){if(input.length>0){Service.request('SoftKeyStore:register',{left:'cancel',center:'go'},this.input);}else{Service.request('SoftKeyStore:register',{left:'cancel'},this.input);}}},showResults:function(){if(this.searchWindow&&!this.searchWindow.isDead()){this.searchWindow.open();}
this.results.classList.remove('hidden');this.backdrop.classList.add('results-shown');},hideResults:function(){if(this.searchWindow){this.searchWindow.close();}
this.results.classList.add('hidden');this.backdrop.classList.remove('results-shown');if(this._port){this._port.postMessage({action:'clear'});}},clear:function(){this.setInput('');this.hideResults();},enableNavigation:function(){this.rocketbar.classList.add('navigation');},disableNavigation:function(){this.rocketbar.classList.remove('navigation');},focus:function(){if(this.active){this.input.focus();this._setSoftKeys();}},selectAll:function(){this.input.setSelectionRange(0,this.input.value.length,'forward');},handleFocus:function(){this.focused=true;},_handle_home:function(evt){if(evt.detail&&evt.detail.back===true){var hasInput=this.input.value.length>0;if(this.isActive()&&!hasInput){this.handleCancel();}}else{this.handleCancel();}
return false;},blur:function(){this.input.blur();},handleBlur:function(){this.focused=false;},handleLock:function(){this._closeSearch();},'_handle_mozChromeEvent':function(evt){if(!evt.detail||evt.detail.type!=='inputmethod-contextchange'){return true;}
if(this.searchWindow){this.searchWindow.getTopMostWindow().broadcast('inputmethod-contextchange',evt.detail);return false;}
return true;},_handle_launchactivity:function(e){if(e.detail.isActivity&&e.detail.inline&&this.searchWindow&&this.searchWindow.manifestURL===e.detail.parentApp){this.searchWindow.broadcast('launchactivity',e.detail);return false;}
return true;},_closeSearch:function(){var hideAndDeactivate=()=>{this.hideResults();this.deactivate();if(this.searchWindow){this.searchWindow.kill();this.searchWindow=null;}};if(this._activateCall){this._activateCall.then(hideAndDeactivate);}else{hideAndDeactivate();}},handleInput:function(){var input=this.input.value;var isNewSearch=this._isDifferentFromPreviousSearch(input);this._latestInputValue=input;this._setSoftKeys();this.rocketbar.classList.toggle('has-text',input.length);Service.request('turnKeypadBacklightOn');if(Service.query('NotificationView.isActive')){this._closeSearch();return;}
if(!input){this.hideResults();return;}
if(this.results.classList.contains('hidden')){this.showResults();}
if(this._port&&isNewSearch){this._port.postMessage({action:'change',input:input});}},_isDifferentFromPreviousSearch:function(newValue){if(newValue!==this._latestInputValue){return true;}else{return false;}},_handle_keyboardleaveediting:function(){if(this.isActive()){this._closeSearch();return false;}},handleCancel:function(e){this.setInput('');this._closeSearch();},handleSubmit:function(){var hasInput=this.input.value.length>0;if(!hasInput){return;}
this.input.blur();if(this.results.classList.contains('hidden')){this.showResults();}
this._port.postMessage({action:'submit',input:this.input.value});setTimeout(()=>{this._closeSearch();this.setInput('');},DELAY_TO_KILL_SEARCH_WINDOW);},handleKeyDown:function(e){if(!this.isActive()){return;}
Service.request('turnKeypadBacklightOn');var hasInput=this.input.value.length>0;var key=e.key;switch(key){case'SoftLeft':this.handleCancel();e.stopPropagation();break;case'ArrowDown':if(this.getActiveWindow()&&hasInput){this._focusOnSearch();}else if(this.isActive()&&!hasInput){this.handleCancel();}
break;case'Enter':if(hasInput){this.handleSubmit();}
break;}},loadSearchApp:function(){if(!this.searchWindow){this.searchWindow=new SearchWindow();}
return this.initSearchConnection();},handleSearchTerminated:function(e){if(!this.searchWindow){return;}
this._closeSearch();this.searchWindow=null;this._port=null;},initSearchConnection:function(){if(this.pendingInitConnection){return this.pendingInitConnection;}
this.pendingInitConnection=new Promise((resolve,reject)=>{navigator.mozApps.getSelf().onsuccess=(event)=>{var app=event.target.result;if(!app){reject();return;}
app.connect('search').then(ports=>{ports.forEach(port=>{this._port=port;});if(this._pendingMessage){this.handleSearchMessage(this._pendingMessage);delete this._pendingMessage;}
delete this.pendingInitConnection;resolve();},reject);};});return this.pendingInitConnection;},handleSearchMessage:function(e){if(!this._port){this._pendingMessage=e;this.initSearchConnection();return;}
switch(e.detail.action){case'render':this.activate().then(this.focus.bind(this));break;case'focus':this.focus();break;case'input':this.setInput(e.detail.input);this.focus();this.handleInput();break;case'request-screenshot':places.screenshotRequested(e.detail.url);break;case'hide':this.setInput('');this._closeSearch();break;}},updateSearchIndex:function(){if(this._port){this._port.postMessage({action:'syncPlaces'});}},_focusOnSearch:function(){var activeWindow=this.getActiveWindow();if(!activeWindow){return;}
this.publish('focusonsearchwindow');if(Service.query('isOnRealDevice')){activeWindow.focus();}else{window.requestAnimationFrame(()=>{activeWindow.focus();});}},_toggleReactivate:function(enabled){if(enabled){this._isReactivated=true;}else{if(this._isReactivated){this.activate().then(this.focus.bind(this));}
this._isReactivated=false;}}};exports.Rocketbar=Rocketbar;}(window));