'use strict';var ScreenManager={name:'ScreenManager',DEBUG:false,brightLevel2Value:{'0':0,'0.1':0.04,'0.2':0.115,'0.3':0.225,'0.4':0.336,'0.5':0.447,'0.6':0.557,'0.7':0.668,'0.8':0.779,'0.9':0.889,'1':1},screenEnabled:navigator.mozPower.screenEnabled,extScreenEnabled:function(){return navigator.mozPower.extScreenBrightness>0;},_unlocking:false,_inTransition:false,_deviceLightEnabled:true,_userBrightness:1,_brightnessLoaded:false,_backLightEnabled:true,AUTO_BRIGHTNESS_MINIMUM:0.1,AUTO_BRIGHTNESS_CONSTANT:0.27,AUTO_BRIGHTNESS_MIN_DELTA:10,_previousLux:undefined,_screenBrightnessTransition:null,LOCKING_TIMEOUT:10,POCKETMODE_TIMEOUT:5,NOTICE_DIALOG_TIMEOUT:60,_dimNotice:10*1000,_idleTimeout:0,_idleTimerId:0,_screenOffBy:null,_screenOffTimeout:0,_isExternalScreenInit:false,get lidOpened(){if(this._flipManager){return this._flipManager.flipOpened;}else{return navigator.flipOpened;}},init:function scm_init(){window.addEventListener('attentionopening',this);window.addEventListener('attentionopened',this);window.addEventListener('notice-dialog-activated',this);window.addEventListener('notice-dialog-deactivated',this);window.addEventListener('dialog--activated',this);window.addEventListener('sleep',this);window.addEventListener('wake',this);window.addEventListener('extscreen-toggle',this);window.addEventListener('nfc-tech-discovered',this);window.addEventListener('nfc-tech-lost',this);window.addEventListener('requestshutdown',this);window.addEventListener('unlocking-start',this);window.addEventListener('unlocking-stop',this);window.addEventListener('flip-button-release',this);window.addEventListener('flip-button-press',this);window.addEventListener('secure-appopened',this);window.addEventListener('secure-appterminated',this);window.addEventListener('lockscreen-appclosed',this);window.addEventListener('lockmode-change',this);window.addEventListener('accessibility-action',this);this.screen=document.getElementById('screen');this._screenBrightnessTransition=new ScreenBrightnessTransition();var self=this;var power=navigator.mozPower;power.keyLightEnabled=true;this._wakeLockManager=new ScreenWakeLockManager();this._wakeLockManager.onwakelockchange=this._reconfigScreenTimeout.bind(this);this._wakeLockManager.start();this._firstOn=false;this._screenLock=navigator.requestWakeLock('screen');window.addEventListener('logohidden',this);SettingsListener.observe('screen.timeout',60,function screenTimeoutChanged(value){if(typeof value!=='number'){value=parseInt(value);}
self._idleTimeout=value;self._setIdleTimeout(self._idleTimeout);if(self._flipManager&&self._flipManager.flipOpened===false){return;}
if(!self._firstOn){self._firstOn=true;self.setScreenBrightness(0.5,true);self.turnScreenOn(false);}});SettingsListener.observe('screen.automatic-brightness',true,function deviceLightSettingChanged(value){self.setDeviceLightEnabled(value);});SettingsListener.observe('screen.brightness',1,function brightnessSettingChanged(value){if(self._brightnessLoaded&&!self._backLightEnabled&&value!==self._userBrightness){navigator.mozSettings.createLock().set({'accessibility.backlight':true});}
self._brightnessLoaded=true;let cur=self._userBrightness;self._userBrightness=value;if(!self._backLightEnabled){return;}
if(cur-value>0.5){self.setScreenBrightness(value,true);}else{self.setScreenBrightness(value,false);}});SettingsListener.observe('accessibility.backlight',self._backLightEnabled,function SettingBrightnessChange(enable){self._backLightEnabled=enable;if(enable===true){self.setScreenBrightness(self._userBrightness,false);}else{self.setScreenBrightness(self.AUTO_BRIGHTNESS_MINIMUM,false);}});var telephony=window.navigator.mozTelephony;if(telephony){telephony.addEventListener('callschanged',this);}
Service.registerState('screenEnabled',this);Service.registerState('lidOpened',this);Service.register('turnScreenOn',this);Service.register('turnScreenOff',this);navigator.getFlipManager&&navigator.getFlipManager().then((fm)=>{this._flipManager=fm;this._flipManager.addEventListener('flipchange',this);if(this._flipManager.flipOpened===false){console.log('firsttime bootup and flip is closed');if(!self._isExternalScreenInit){console.log('init external screen needed');self._isExternalScreenInit=true;}
if(telephony){console.log('to call telephony.setMaxTransmitPower');telephony.setMaxTransmitPower(1);}
this.turnScreenOff();}});},autoAdjustBrightness:function scm_adjustBrightness(lux){if(lux<1){lux=1;}
if(this._previousLux!==undefined){var brightnessDelta=Math.abs(this._previousLux-lux);if(brightnessDelta<=this.AUTO_BRIGHTNESS_MIN_DELTA){return;}}
this._previousLux=lux;var computedBrightness=Math.log10(lux)*this.AUTO_BRIGHTNESS_CONSTANT;var clampedBrightness=Math.max(this.AUTO_BRIGHTNESS_MINIMUM,Math.min(1.0,computedBrightness));this.setScreenBrightness(clampedBrightness,false);},handleEvent:function scm_handleEvent(evt){var telephony=window.navigator.mozTelephony;var call;switch(evt.type){case'flipchange':if(this.lidOpened){this.turnScreenOn();}else{this.turnScreenOff(true,'flip');}
break;case'notice-dialog-activated':this.turnScreenOn();this._setIdleTimeout(this.NOTICE_DIALOG_TIMEOUT,true);break;case'notice-dialog-deactivated':this._reconfigScreenTimeout();break;case'attentionopening':case'attentionopened':case'dialog--activated':if(!this.enabled){this.turnScreenOn();}else{this._reconfigScreenTimeout();}
break;case'devicelight':if(!this._deviceLightEnabled||!this.screenEnabled||this._inTransition){return;}
this.autoAdjustBrightness(evt.value);break;case'sleep':this.turnScreenOff(true,'powerkey');break;case'extscreen-toggle':this.toggleExtScreen();break;case'wake':this.turnScreenOn();if(FxAccountsUI.dialog&&!FxAccountsUI.dialog.Hidden())
FxAccountsUI.dialog.focus();break;case'accessibility-action':this._reconfigScreenTimeout();break;case'nfc-tech-discovered':case'nfc-tech-lost':if(this._inTransition){this.turnScreenOn();}else{this._reconfigScreenTimeout();}
break;case'unlocking-start':this._setUnlocking();break;case'secure-appopened':case'secure-appterminated':this._reconfigScreenTimeout();break;case'unlocking-stop':this._resetUnlocking();break;case'userproximity':if(Bluetooth.isProfileConnected(Bluetooth.Profiles.SCO)||telephony.speakerEnabled||Service.query('isHeadsetConnected')){if(this._screenOffBy=='proximity'){this.turnScreenOn();}
break;}
if(evt.near){this.turnScreenOff(true,'proximity');}else{this.turnScreenOn();}
break;case'callschanged':this.turnScreenOn();if(!telephony.calls.length&&!(telephony.conferenceGroup&&telephony.conferenceGroup.calls.length)){window.removeEventListener('userproximity',this);break;}
call=telephony.calls[0];call.addEventListener('statechange',this);if(Service.query('hasVT')){var videoCallProvider=call.videoCallProvider;videoCallProvider.onsessionmodifyrequest=()=>{this.turnScreenOn();};}
break;case'statechange':call=evt.target;if(['connected','alerting','dialing'].indexOf(call.state)===-1){break;}
call.removeEventListener('statechange',this);window.addEventListener('userproximity',this);break;case'lockscreen-appclosed':case'lockscreen-appclosing':case'lockpanelchange':window.removeEventListener('lockscreen-appclosing',this);window.removeEventListener('lockpanelchange',this);this._setIdleTimeout(this._idleTimeout,false);break;case'lockmode-change':if(evt.detail.mode!=='none'){this._reconfigScreenTimeout();}
break;case'logohidden':window.removeEventListener('logohidden',this);this._screenLock.unlock();this._screenLock=null;break;case'requestshutdown':this.turnScreenOn();if(evt.detail&&evt.detail.startPowerOff){evt.detail.startPowerOff(false);}
break;}},toggleExtScreen:function scm_toggleExtScreen(){dump('toggleExtScreen called');if(!this.lidOpened){let toggle=!navigator.mozPower.extScreenEnabled;this.wakeUpExtScreen=toggle;navigator.mozPower.extScreenEnabled=toggle;navigator.mozPower.extScreenBrightness=toggle?1:0;this.fireScreenChangeEvent();return;}},toggleScreen:function scm_toggleScreen(){if(this.screenEnabled){this.turnScreenOff(true,'toggle');}else{this.turnScreenOn();}},turnScreenOff:function scm_turnScreenOff(instant,reason){console.log('screenEnabled: ',instant,this.screenEnabled,reason);if(!this.screenEnabled&&reason!='flip'){return false;}
var self=this;if(reason){this._screenOffBy=reason;}
if(this._screenOffBy=='powerkey'){window.removeEventListener('userproximity',this);}
var screenOff=function scm_screenOff(){self._setIdleTimeout(0);if(self._deviceLightEnabled){window.removeEventListener('devicelight',self);}
window.removeEventListener('lockscreen-appclosing',self);window.removeEventListener('lockpanelchange',self);window.removeEventListener('lockmode-change',self);self.screenEnabled=false;self._inTransition=false;self.fireBeforeScreenOffEvent();self.screen.classList.add('screenoff');clearTimeout(self._screenOffTimeout);if(self._screenOffBy=='flip'){self._screenOffTimeout=setTimeout(function realScreenOff(){self.setScreenBrightness(0,true);console.log('turn the external screen on with 20ms delay');navigator.mozPower.extScreenEnabled=true;navigator.mozPower.extScreenBrightness=1;},20);var telephony=window.navigator.mozTelephony;if(telephony){console.log('to call setMaxTransmitPower');telephony.setMaxTransmitPower(1);}
self._isExternalScreenInit=true;}else if(!self._isExternalScreenInit){console.log('initial the external screen for power current saving purpose');self._isExternalScreenInit=true;navigator.mozPower.extScreenEnabled=true;navigator.mozPower.extScreenEnabled=false;}
self.fireScreenChangeEvent();navigator.mozPower.screenEnabled=false;};if(instant){screenOff();return true;}
this.setScreenBrightness(0.1,false);this._inTransition=true;setTimeout(function noticeTimeout(){if(!self._inTransition){return;}
screenOff();},self._dimNotice);return true;},turnScreenOn:function scm_turnScreenOn(instant){console.log('screenEnabled: ',this.screenEnabled);if(!this.lidOpened){this.wakeUpExtScreen=true;navigator.mozPower.extScreenEnabled=true;navigator.mozPower.extScreenBrightness=1;this.fireScreenChangeEvent();return;}
clearTimeout(this._screenOffTimeout);let restoreBrightness=this._backLightEnabled?this._userBrightness:this.AUTO_BRIGHTNESS_MINIMUM;if(this.screenEnabled){if(this._inTransition){this._inTransition=false;this.setScreenBrightness(restoreBrightness,true);this._reconfigScreenTimeout();}
return false;}
var power=navigator.mozPower;if(power){power.extScreenEnabled=false;power.extScreenBrightness=0;power.screenEnabled=true;}
this.screenEnabled=true;this.setScreenBrightness(restoreBrightness,instant);var telephony=window.navigator.mozTelephony;if(telephony){console.log('to call setMaxTransmitPower to 0');telephony.setMaxTransmitPower(0);}
var ongoingConference=telephony&&telephony.conferenceGroup&&telephony.conferenceGroup.calls.length;if(telephony&&(telephony.calls.length||ongoingConference)){var connected=telephony.calls.some(function checkCallConnection(call){if(call.state=='connected'){return true;}
return false;});if(connected||ongoingConference){window.addEventListener('userproximity',this);}}
this.screen.classList.remove('screenoff');if(this._deviceLightEnabled){window.addEventListener('devicelight',this);}
this._reconfigScreenTimeout();this.fireScreenChangeEvent();return true;},_reconfigScreenTimeout:function scm_reconfigScreenTimeout(){if(this._wakeLockManager.isHeld){this._setIdleTimeout(0);}else if(!this._unlocking){if(window.Service.query('locked')&&!window.secureWindowManager.isActive()){this.debug('_reconfigScreenTimeout: currently locked');const timeout=window.Service.query('isPocketMode')?this.POCKETMODE_TIMEOUT:this.LOCKING_TIMEOUT;this._setIdleTimeout(timeout,true);window.addEventListener('lockscreen-appclosing',this);window.addEventListener('lockpanelchange',this);window.addEventListener('lockmode-change',this);}else{this._setIdleTimeout(this._idleTimeout,false);}}},_setUnlocking:function scm_setUnlocking(){this._unlocking=true;window.clearIdleTimeout(this._idleTimerId);},_resetUnlocking:function scm_resetUnlocking(){this._unlocking=false;this._reconfigScreenTimeout();},setScreenBrightness:function scm_setScreenBrightness(brightness,instant){var value=this.brightLevel2Value[brightness];if(value===undefined){brightness=brightness.toFixed(1);value=this.brightLevel2Value[brightness];}
this._targetBrightness=value;this._curBrightLevel=brightness;var power=navigator.mozPower;if(!power){return;}
if(this._screenBrightnessTransition.isRunning){this._screenBrightnessTransition.abort();}
if(typeof instant!=='boolean'){instant=true;}
if(instant){power.screenBrightness=value;return;}
this._screenBrightnessTransition.transitionTo(this._targetBrightness);},setDeviceLightEnabled:function scm_setDeviceLightEnabled(enabled){if(!enabled&&this._deviceLightEnabled){this.setScreenBrightness(this._userBrightness,false);}
this._deviceLightEnabled=enabled;this._previousLux=undefined;if(!this.screenEnabled){return;}
if(enabled){window.addEventListener('devicelight',this);}else{window.removeEventListener('devicelight',this);}},_setIdleTimeout:function scm_setIdleTimeout(time,instant){this.debug('_setIdleTimeout called: (time, instant):',time,instant);window.clearIdleTimeout(this._idleTimerId);this._idled=false;if(time===0){return;}
var self=this;var idleCallback=function idle_proxy(){self.turnScreenOff(instant,'idle_timeout');};var activeCallback=function active_proxy(){self.turnScreenOn(true);};var finalTimeout=instant?time*1000:(time*1000)-this._dimNotice;this.debug('finalTimeout set:',finalTimeout);this._idleTimerId=window.setIdleTimeout(idleCallback,activeCallback,finalTimeout);},setScreenOffMask:function scm_setScreenOffMask(value){if(!this.lidOpened){if(value){this.screen.classList.add('screenoff');}else{this.screen.classList.remove('screenoff');}}},fireBeforeScreenOffEvent:function scm_fireBeforeScreenOffEvent(){const detail={screenOffBy:this._screenOffBy};const eventDetail={bubbles:true,cancelable:false,detail:detail};const evt=new CustomEvent('beforescreenoff',eventDetail);window.dispatchEvent(evt);},fireScreenChangeEvent:function scm_fireScreenChangeEvent(){var detail={screenEnabled:this.screenEnabled};detail.screenOffBy=this._screenOffBy;detail.wakeUpExtScreen=this.wakeUpExtScreen;var evt=new CustomEvent('screenchange',{bubbles:true,cancelable:false,detail:detail});window.dispatchEvent(evt);window.ExternalScreenManager.send(evt);this.wakeUpExtScreen=false;},debug:function scm_debug(){if(this.DEBUG){console.log(`[${this.name}][${window.Service.currentTime()}] ${Array.slice(arguments).concat()}`);}}};ScreenManager.init();