
(function(exports){'use strict';function SoundManager(){}
var isChangeToSave=true;SoundManager.VIBRATION_SETTINGS_KEY='vibration.enabled';SoundManager.VIBRATION_USER_PREF_KEY='preference.vibration.enabled';SoundManager.CE_RESET_TIME=72000000;SoundManager.TIME_ONE_MINUTE=60000;SoundManager.CACHE_CETIMES='CE_ACCTIME';SoundManager.MAX_VOLUME={'alarm':15,'notification':15,'telephony':5,'content':15,'bt_sco':15};SoundManager.HIDE_SOUND_DELAY=2000;SoundManager.prototype.name='SoundManager';SoundManager.prototype.DEBUG=false;SoundManager.prototype.showUI=true;SoundManager.prototype.publish=function(evtName,detail){window.dispatchEvent(new CustomEvent(evtName),{detail:(detail||this)});};SoundManager.prototype.setHeadsetState=function(enabled){if(this.isHeadsetConnected===enabled){return;}
this.isHeadsetConnected=enabled;this.publish('headphones-status-changed',this.isHeadsetConnected);};SoundManager.prototype.setAudioChannel=function(channel){if(this.currentChannel===channel){return;}
this.currentChannel=channel;};SoundManager.prototype.isActivated=function(){return this.element.classList.contains('visible');};SoundManager.prototype.currentChannel='none';SoundManager.prototype.vibrationEnabled=true;SoundManager.prototype.defaultVolumeControlChannel='unknown';SoundManager.prototype.isHeadsetConnected=false;SoundManager.prototype.muteState='OFF';SoundManager.prototype.vibrationUserPrefEnabled=true;SoundManager.prototype.cachedVolume={'content':-1,'notification':-1};SoundManager.prototype.cachedChannels=['content','notification'];SoundManager.prototype.CEAccumulatorID=null;SoundManager.prototype.CEWarningVol=10;SoundManager.prototype.CEAccumulatorTime=0;SoundManager.prototype.CETimestamp=0;SoundManager.prototype.TEWarningVol=4;SoundManager.prototype.currentVolume={'alarm':10,'notification':10,'telephony':10,'content':10,'bt_sco':10};SoundManager.prototype.params=0;SoundManager.prototype.pendingRequest=new AsyncSemaphore();SoundManager.prototype.homescreenVisible=true;SoundManager.prototype.setVibrationEnabledCount=0;SoundManager.prototype.volumeFetched=false;SoundManager.prototype.activeTimerID=0;SoundManager.prototype.start=function sm_start(){this.element=document.getElementById('volume');this.screen=document.getElementById('screen');this.overlay=document.getElementById('system-overlay');this.handleBeforeKeyDown=this.handleBeforeKeyDown.bind(this);window.addEventListener('mozbrowserbeforekeydown',this.handleBeforeKeyDown);window.addEventListener('volumeup',this);window.addEventListener('volumedown',this);window.addEventListener('mozChromeEvent',this);window.addEventListener('appopen',this);window.addEventListener('ftudone',this);window.addEventListener('holdhome',this);window.addEventListener('homescreenopening',this);window.addEventListener('homescreenopened',this);window.addEventListener(Service.query('isQwerty')?'hold4':'holdhash',this);window.addEventListener('audiochannelchanged',this);var acm=navigator.mozAudioChannelManager;if(acm){this.setHeadsetState(acm.headphones);}
this.initVibrationUserPref();this.bindVolumeSettingsHandlers();var self=this;window.asyncStorage.getItem(SoundManager.CACHE_CETIMES,function getCETime(value){if(!value){return;}else{self.CEAccumulatorTime=0;}});Service.registerState('isHeadsetConnected',this);Service.registerState('currentChannel',this);Service.registerState('isActivated',this);};SoundManager.prototype.stop=function sm_stop(){window.removeEventListener('volumeup',this);window.removeEventListener('volumedown',this);window.removeEventListener('mozChromeEvent',this);window.removeEventListener('appopen',this);window.removeEventListener('ftudone',this);window.removeEventListener('holdhome',this);window.removeEventListener('homescreenopening',this);window.removeEventListener('homescreenopened',this);window.removeEventListener('keyup',this);window.removeEventListener('keydown',this);window.removeEventListener('mozbrowserbeforekeydown',this.handleBeforeKeyDown);window.removeEventListener(Service.query('isQwerty')?'hold4':'holdhash',this);window.removeEventListener('audiochannelchanged',this);Service.unregisterState('isHeadsetConnected',this);Service.unregisterState('currentChannel',this);Service.unregisterState('isActivated',this);};SoundManager.prototype.handleEvent=function sm_handleEvent(e){switch(e.type){case'holdhash':case'hold4':if(Service.query('getTopMostWindow').isHomescreen&&Service.query('getTopMostUI').name==='AppWindowManager'&&document.activeElement.tagName.toLowerCase()==='iframe'){this.toggleVibrate();}
break;case'volumeup':this.handleVolumeKey(1);break;case'volumedown':this.handleVolumeKey(-1);break;case'audiochannelchanged':this.setAudioChannel(e.detail.channel);if('content'===this.getChannel()){this.ceAccumulator();}
break;case'mozChromeEvent':switch(e.detail.type){case'bluetooth-volumeset':if(Bluetooth.isProfileConnected(Bluetooth.Profiles.SCO)){this.changeVolume(e.detail.value-this.currentVolume.bt_sco,'bt_sco');}
break;case'headphones-status-changed':this.setHeadsetState(e.detail.state!=='off');this.ceAccumulator();if((!this.isHeadsetConnected)&&(e.detail.state!=='off')&&(this.currentVolume['content']>=this.CEWarningVol)&&isChangeToSave){this.changeToSave();}
break;case'default-volume-channel-changed':this.defaultVolumeControlChannel=e.detail.channel;break;case'request-volume-up':this.handleVolumeKey(1);break;case'request-volume-down':this.handleVolumeKey(-1);break;case'request-volume-show':this.handleVolumeKey(0);break;}
break;case'appopen':this.homescreenVisible=false;break;case'ftudone':case'homescreenopening':case'homescreenopened':this.homescreenVisible=true;break;}};SoundManager.prototype.handleVolumeKey=function sm_handleVolumeKey(offset){if(Bluetooth.isProfileConnected(Bluetooth.Profiles.SCO)&&this.isOnCall()){this.changeVolume(offset,'bt_sco');}else if(this.isHeadsetConnected&&offset>0){this.headsetVolumeup();}else{this.changeVolume(offset);}};SoundManager.prototype.handleBeforeKeyDown=function sm_handleBeforeKeyDown(event){if(this.isActivated()&&!Service.query('hasVolumeKey')){if(event.key==='ArrowUp'){if(navigator.volumeManager){navigator.volumeManager.requestUp();}}else if(event.key==='ArrowDown'){if(navigator.volumeManager){navigator.volumeManager.requestDown();}}
if(event.key!=='VolumeDown'&&event.key!=='VolumeUp'){if(event.key==='1'||event.key==='3'){const window=Service.query('getTopMostWindow');const origin=window&&window.manifest&&window.manifest.origin;if(origin.indexOf('youtube')>=0){return;}}
event.preventDefault();}}};SoundManager.prototype.setMute=function sm_setMute(mute){if(mute){this.setVibrationEnabled(false);this.enterSilentMode('notification');}else{this.setVibrationEnabled(true);this.leaveSilentMode('notification');this.leaveSilentMode('content');}};SoundManager.prototype.getChannel=function sm_getChannel(){if(this.isOnCall()){return'telephony';}
switch(this.currentChannel){case'normal':case'content':return'content';case'telephony':return'telephony';case'alarm':return'alarm';case'notification':case'ringer':return'notification';default:if(this.defaultVolumeControlChannel!=='unknown'){return this.defaultVolumeControlChannel;}else{return this.homescreenVisible||(Service.query('locked'))||FtuLauncher.isFtuRunning()?'notification':'content';}}};SoundManager.prototype.initVibrationUserPref=function sm_initVUserPref(){var self=this;window.asyncStorage.getItem(SoundManager.VIBRATION_USER_PREF_KEY,function onok(value){if(value===null){var r=SettingsListener.getSettingsLock().get(SoundManager.VIBRATION_SETTINGS_KEY);r.onsuccess=function get_onsuccess(){self.writeVibrationUserPref(r.result[SoundManager.VIBRATION_SETTINGS_KEY]);};r.onerror=function get_onerror(){self.writeVibrationUserPref(true);};}else{self.vibrationUserPrefEnabled=value;}});SettingsListener.observe(SoundManager.VIBRATION_SETTINGS_KEY,true,function(vibration){var setBySelf=false;var toggleVibrationEnabled=function toggle_vibration_enabled(){if(!setBySelf){self.writeVibrationUserPref(vibration);}
self.vibrationEnabled=vibration;};if(self.setVibrationEnabledCount>0){self.setVibrationEnabledCount--;setBySelf=true;}
self.pendingRequest.wait(toggleVibrationEnabled,self);});};SoundManager.prototype.writeVibrationUserPref=function sm_writeUP(value){if(this.vibrationUserPrefEnabled===value){return;}
if(value===null||typeof(value)==='undefined'){value=true;}
var self=this;window.asyncStorage.setItem(SoundManager.VIBRATION_USER_PREF_KEY,value,function set_onsuccess(){self.vibrationUserPrefEnabled=value;});};SoundManager.prototype.ceAccumulator=function sm_ceAccumulator(){if(this.isHeadsetConnected&&this.getChannel()==='content'&&this.currentVolume[this.getChannel()]>this.CEWarningVol){if(this.CEAccumulatorTime===0){this.showCEWarningDialog();}else{this.startAccumulator();}}else{this.stopAccumulator();}};SoundManager.prototype.headsetVolumeup=function sm_headsetVolumeup(){if((this.currentVolume[this.getChannel()]+1)>this.CEWarningVol&&this.getChannel()==='content'){if(this.CEAccumulatorTime===0){var self=this;var okfn=function(){self.changeVolume(1);self.startAccumulator();};this.showCEWarningDialog(okfn);}else{this.startAccumulator();this.changeVolume(1);}}else{this.changeVolume(1);}};SoundManager.prototype.showCEWarningDialog=function sm_showCEDialog(okfn){var _=navigator.mozL10n.get;Service.request('DialogService:show',{header:_('ceWarningtitle'),content:_('ceWarningcontent'),translated:true,type:'alert',onOk:()=>{if(okfn instanceof Function){okfn();}else{this.startAccumulator();}}});};SoundManager.prototype.startAccumulator=function sm_startAccumulator(){if(this.CEAccumulatorID===null){if(this.CEAccumulatorTime===0){this.CEAccumulatorTime=1;this.CETimestamp=parseInt(new Date().getTime(),10);}
var self=this;this.CEAccumulatorID=window.setInterval(function ceCounter(){self.CEAccumulatorTime+=SoundManager.TIME_ONE_MINUTE;self.CETimestamp=parseInt(new Date().getTime(),10);if(self.CEAccumulatorTime>SoundManager.CE_RESET_TIME){self.CEAccumulatorTime=0;self.CETimestamp=0;self.stopAccumulator();self.showCEWarningDialog();}},SoundManager.TIME_ONE_MINUTE);}};SoundManager.prototype.stopAccumulator=function sm_stopAccumulator(){if(this.CEAccumulatorID!==null){window.clearInterval(this.CEAccumulatorID);this.CEAccumulatorID=null;if(this.CETimestamp!==0){this.CEAccumulatorTime=this.CEAccumulatorTime+
(parseInt(new Date().getTime(),10)-this.CETimestamp);}
window.asyncStorage.setItem(SoundManager.CACHE_CETIMES,this.CEAccumulatorTime);}};SoundManager.prototype.isOnCall=function sm_isOnCall(){if(this.currentChannel==='telephony'){return true;}
var telephony=window.navigator.mozTelephony;if(!telephony){return false;}
return telephony.calls.some(function callIterator(call){return(call.state=='connected');});};SoundManager.prototype.bindVolumeSettingsHandlers=function sm_bindHdlers(){var callsMade=0;var callbacksReceived=0;var self=this;function observeSettingsVolumeChange(channel){var setting='audio.volume.'+channel;SettingsListener.observe(setting,5,function onChange(volume){var settingsChange=function settings_change(){var max=SoundManager.MAX_VOLUME[channel];self.currentVolume[channel]=parseInt(Math.max(0,Math.min(max,volume)),10);if(self.currentVolume[channel]!==volume){let settingObject={};settingObject['audio.volume.'+channel]=self.currentVolume[channel];SettingsListener.getSettingsLock().set(settingObject);return;}
if(channel==='content'&&self.volumeFetched&&volume>0){self.leaveSilentMode('content',true);if(isChangeToSave&&self.isHeadsetConnected){if(self.currentVolume['content']<self.CEWarningVol){isChangeToSave=false;}else{self.changeToSave();}}}else if(channel==='notification'&&volume>0){self.leaveSilentMode('notification',true);}else if(channel==='notification'&&volume===0){self.enterSilentMode('notification');}
if(!self.volumeFetched&&++callbacksReceived===callsMade){self.fetchCachedVolume();}
if(channel==='telephony'&&this.isHeadsetConnected&&this.currentChannel==='telephony'&&this.currentVolume['telephony']>=this.TEWarningVol){this.debug(`Warning High Volume with headset in call`);let detail={channel:'telephony'};let highVolumeEvt=new CustomEvent('highvolume',{detail:detail});window.ExternalScreenManager.send(highVolumeEvt);}
if(channel==='content'&&this.isHeadsetConnected&&this.getChannel()==='content'&&this.currentVolume['content']>=this.CEWarningVol){this.debug(`Warning High Volume with headset media play`);let detail={channel:'content'};let highVolumeEvt=new CustomEvent('highvolume',{detail:detail});window.ExternalScreenManager.send(highVolumeEvt);}};self.pendingRequest.wait(settingsChange,self);});}
for(var channel in this.currentVolume){callsMade++;observeSettingsVolumeChange(channel);}};SoundManager.prototype.fetchCachedVolume=function sm_fetchCachedVolume(){if(this.volumeFetched){return;}
this.volumeFetched=true;this.pendingRequest.v(this.cachedChannels.length);var self=this;this.cachedChannels.forEach(function iterator(channel){window.asyncStorage.getItem('content.volume',function onGettingCachedVolume(value){if(!value){self.pendingRequest.p();return;}
self.cachedVolume[channel]=value;self.pendingRequest.p();});});};SoundManager.prototype.calculateVolume=function sm_calVol(curVolume,delta,channel){var volume=curVolume;switch(channel){case'notification':if(volume===0&&!this.vibrationEnabled){volume=-1;}
volume+=delta;break;case'telephony':case'bt_sco':if(volume+delta>=1){volume+=delta;}else{volume=1;}
break;default:volume+=delta;break;}
return volume;};SoundManager.prototype.getVibrationAndMuteState=function sm_getState(delta,channel){var curVolume=this.currentVolume[channel];if(channel==='notification'){var state;var volume=curVolume;if(volume===0&&!this.vibrationEnabled){volume=-1;}
volume+=delta;if(volume<0){state='MUTE';this.vibrationEnabled=false;}else if(volume===0){state='MUTE';this.vibrationEnabled=true;}else{if(curVolume<=0){this.vibrationEnabled=this.vibrationUserPrefEnabled;}
state='OFF';}
if(delta!==0&&volume===0&&this.vibrationEnabled){this.notifyByVibrating();}
return state;}else{if(curVolume+delta<=0){return'MUTE';}else{return'OFF';}}};SoundManager.prototype.notifyByVibrating=function sm_notifyByVibrating(){window.navigator.vibrate(200);};SoundManager.prototype.enterSilentMode=function sm_enterSlient(channel){if(!channel){channel='content';}
if(this.currentVolume[channel]===0){return;}
var isCachedAlready=(this.cachedVolume[channel]===this.currentVolume[channel]);this.cachedVolume[channel]=this.currentVolume[channel];this.pendingRequest.v();var settingObject={};settingObject['audio.volume.'+channel]=0;var req=SettingsListener.getSettingsLock().set(settingObject);var self=this;this.drawVolumeBar(channel,0);req.onsuccess=function onSuccess(){self.pendingRequest.p();if(!isCachedAlready){window.asyncStorage.setItem(channel+'.volume',self.cachedVolume[channel]);}};req.onerror=function onError(){self.pendingRequest.p();};};SoundManager.prototype.leaveSilentMode=function sm_leaveSlient(channel,skip_restore){if(!channel){channel='content';}
if(!skip_restore&&(this.cachedVolume[channel]>0||this.currentVolume[channel]===0)){var req;var settingObject={};var self=this;settingObject['audio.volume.'+channel]=(this.cachedVolume[channel]>0)?this.cachedVolume[channel]:1;this.pendingRequest.v();if(channel===this.getChannel()){this.drawVolumeBar(channel,settingObject['audio.volume.'+channel]);}
req=SettingsListener.getSettingsLock().set(settingObject);req.onsuccess=function onSuccess(){self.pendingRequest.p();};req.onerror=function onError(){self.pendingRequest.p();};}
this.cachedVolume[channel]=-1;};SoundManager.prototype.hideVolume=function sm_hideVolume(){if(!this.visibility){return;}
this.visibility=false;clearTimeout(this.activeTimerID);var overlay=document.getElementById('system-overlay');var notification=document.getElementById('volume');var volumeBar=document.getElementById('volume-bar');var overlayClasses=overlay.classList;var classes=notification.classList;overlayClasses.remove('volume');classes.remove('visible');volumeBar.classList.remove('visible');this.publish('soundManagerHide');};SoundManager.prototype.changeToSave=function sm_changeToSave(){isChangeToSave=false;this.currentVolume['content']=this.CEWarningVol-1;var settingObject={};settingObject['audio.volume.'+'content']=this.CEWarningVol-1;var req=SettingsListener.getSettingsLock().set(settingObject);};SoundManager.prototype.forceVibrate=function(){this.debug('forceVibrate.');this.cachedVolume['notification']=this.currentVolume['notification'];this.currentVolume['notification']=1;this.changeVolume(-1,'notification');};SoundManager.prototype.toggleVibrate=function(){var _channel='notification';var _currentNotificationVolume=this.currentVolume[_channel];if(_currentNotificationVolume||this.cachedVolume[_channel]<0){this.forceVibrate();this.enterSilentMode('content');}else{this.debug('leave vibration mode');if(this.cachedVolume[_channel]===0){this.cachedVolume[_channel]=-1;}
this.changeVolume(this.cachedVolume[_channel],_channel);this.leaveSilentMode('content');}};SoundManager.prototype.drawVolumeBar=function sm_drawVolumeBar(channel,volume){if(channel!==this.getChannel()&&channel!=='bt_sco'){return;}
var volumeBar=document.getElementById('volume-bar');var volumeLeveItem=document.getElementById('volume-level');var volumeInfoTitle=document.getElementById('info-title');var infoIcon=document.getElementById('info-icon');var _localize=navigator.mozL10n.setAttributes;volumeBar.dataset.level=volume;var diameter=volume*16/(SoundManager.MAX_VOLUME[channel]+1)+6;volumeBar.style.width=diameter+'rem';volumeBar.style.height=diameter+'rem';infoIcon.classList.remove('silent','vibrate');if(volume===0){if(this.vibrationEnabled&&channel!=='content'&&channel!=='telephony'&&channel!=='alarm'&&channel!=='bt_sco'){infoIcon.classList.add('vibrate');_localize(volumeInfoTitle,'vibrate-only');}else{infoIcon.classList.add('silent');_localize(volumeInfoTitle,'silent');}}else{volumeInfoTitle.textContent='';}
volumeLeveItem.textContent=volume===0?'':volume+'/'+SoundManager.MAX_VOLUME[channel];}
SoundManager.prototype.changeVolume=function sm_changeVolume(delta,channel){channel=channel?channel:this.getChannel();var vibrationEnabledOld=this.vibrationEnabled;var volume=this.calculateVolume(this.currentVolume[channel],delta,channel);window.ExternalScreenManager.send(new CustomEvent('volumechange',{detail:{channel:channel,volume:volume,max:SoundManager.MAX_VOLUME[channel]}}));this.muteState=this.getVibrationAndMuteState(delta,channel);this.currentVolume[channel]=volume=Math.max(0,Math.min(SoundManager.MAX_VOLUME[channel],volume));var overlay=this.overlay;var notification=this.element;var overlayClasses=overlay.classList;var classes=notification.classList;switch(this.muteState){case'OFF':classes.remove('mute');break;case'MUTE':classes.add('mute');break;}
if(this.vibrationEnabled){classes.add('vibration');}else{classes.remove('vibration');}
if(vibrationEnabledOld!=this.vibrationEnabled){this.setVibrationEnabled(this.vibrationEnabled);}
var volumeBar=document.getElementById('volume-bar');this.updateVolumeTitle();volumeBar.classList.add('visible');this.drawVolumeBar(channel,volume);if(this.showUI){overlayClasses.add('volume');classes.add('visible');}
this.publish('soundManagerShow');this.visibility=true;window.clearTimeout(this.activeTimerID);var self=this;this.activeTimerID=window.setTimeout(function hideSound(){self.hideVolume(self);},SoundManager.HIDE_SOUND_DELAY);if(!window.navigator.mozSettings){return;}
this.pendingRequest.v();notification.dataset.channel=channel;var settingObject={};settingObject['audio.volume.'+channel]=volume;var req=SettingsListener.getSettingsLock().set(settingObject);req.onsuccess=function onSuccess(){self.pendingRequest.p();};req.onerror=function onError(){self.pendingRequest.p();};};SoundManager.prototype.VOLUME_TITLE_L10N_MAPPING={'content':'volume-type-content','telephony':'tcl-volume-type-telephony','alarm':'volume-type-alarm','notification':'tcl-volume-type-notification'};SoundManager.prototype.updateVolumeTitle=function(){if(!this.volumeTitle){this.volumeTitle=document.querySelector('.volume-title');}
this.volumeTitle.dataset.l10nId=this.VOLUME_TITLE_L10N_MAPPING[this.getChannel()];};SoundManager.prototype.setVibrationEnabled=function sm_enableVib(enabled){this.setVibrationEnabledCount++;SettingsListener.getSettingsLock().set({'vibration.enabled':enabled});};exports.SoundManager=SoundManager;exports.soundManager=new SoundManager();if(navigator.mozL10n){navigator.mozL10n.once(function(){exports.soundManager.start();});}
SoundManager.prototype.debug=function sm_debug(){if(this.DEBUG){console.log(`[${this.name}][${window.Service.currentTime()}] ${Array.slice(arguments).concat()}`);}};})(window);