(function(e, t) {
    "object" == typeof exports ? module.exports = t() : "function" == typeof define && define.amd ? define([], t) : e.ASCPContacts = t();
})(this, function() {
    return {
        Tags: {
            Anniversary: 261,
            AssistantName: 262,
            AssistantPhoneNumber: 263,
            Birthday: 264,
            Body: 265,
            BodySize: 266,
            BodyTruncated: 267,
            Business2PhoneNumber: 268,
            BusinessAddressCity: 269,
            BusinessAddressCountry: 270,
            BusinessAddressPostalCode: 271,
            BusinessAddressState: 272,
            BusinessAddressStreet: 273,
            BusinessFaxNumber: 274,
            BusinessPhoneNumber: 275,
            CarPhoneNumber: 276,
            Categories: 277,
            Category: 278,
            Children: 279,
            Child: 280,
            CompanyName: 281,
            Department: 282,
            Email1Address: 283,
            Email2Address: 284,
            Email3Address: 285,
            FileAs: 286,
            FirstName: 287,
            Home2PhoneNumber: 288,
            HomeAddressCity: 289,
            HomeAddressCountry: 290,
            HomeAddressPostalCode: 291,
            HomeAddressState: 292,
            HomeAddressStreet: 293,
            HomeFaxNumber: 294,
            HomePhoneNumber: 295,
            JobTitle: 296,
            LastName: 297,
            MiddleName: 298,
            MobilePhoneNumber: 299,
            OfficeLocation: 300,
            OtherAddressCity: 301,
            OtherAddressCountry: 302,
            OtherAddressPostalCode: 303,
            OtherAddressState: 304,
            OtherAddressStreet: 305,
            PagerNumber: 306,
            RadioPhoneNumber: 307,
            Spouse: 308,
            Suffix: 309,
            Title: 310,
            WebPage: 311,
            YomiCompanyName: 312,
            YomiFirstName: 313,
            YomiLastName: 314,
            CompressedRTF: 315,
            Picture: 316,
            Alias: 317,
            WeightedRank: 318
        }
    };
});