'use strict';(function(exports){var _id=0;var _localize=navigator.mozL10n.setAttributes;var _strForTime=new navigator.mozL10n.DateTimeFormat();function toCamelCase(str){return str.replace(/\-(.)/g,function replacer(str,p1){return p1.toUpperCase();});}
exports.ValueSelector=function(app){this.app=app;this.containerElement=app.element;this.instanceID=_id++;this._currentPickerType=null;this._currentInputType=null;this._currentDatetimeValue='';this._injected=false;this._datePicker=null;this._timePicker=null;this.selectName="";this._showing=false;this.vsCustomizer=new BaseCustomizer();this.focusChangedHandler=this.focusChangedHandler.bind(this);app.element.addEventListener('_opening',this);app.element.addEventListener('_closing',this);app.element.addEventListener('_closed',this);app.element.addEventListener('_inputmethod-contextchange',this);app.element.addEventListener('_localized',this);app.element.addEventListener('mozbrowservisibilitychange',this);window.addEventListener('sys-endkeyhandled',this);window.addEventListener('timeformatchange',this);};ValueSelector.prototype=Object.create(BaseUI.prototype);ValueSelector.prototype.CLASS_NAME='ValueSelector';ValueSelector.prototype.ELEMENT_PREFIX='value-selector-';ValueSelector.prototype.EVENT_PREFIX='value-selector-';ValueSelector.prototype.customID=function vs_customID(){if(this.app){return'['+this.app.origin+']';}else{return'';}};ValueSelector.prototype._im=navigator.mozInputMethod;ValueSelector.prototype.destroy=function(){this.app.element.removeEventListener('_opening',this);this.app.element.removeEventListener('_closing',this);this.app.element.removeEventListener('_closed',this);this.app.element.removeEventListener('_inputmethod-contextchange',this);this.app.element.removeEventListener('_localized',this);this.app.element.removeEventListener('mozbrowservisibilitychange',this);this.app=null;this.containerElement=null;window.removeEventListener('timeformatchange',this);window.removeEventListener('sys-endkeyhandled',this);delete this.vsCustomizer;};ValueSelector.prototype.isInputTypeSupported=function(detail){var typesToHandle=['select-one','select-multiple','date','time','datetime','datetime-local','number'];if(typesToHandle.indexOf(detail.inputType)>=0){switch(detail.inputType){case'number':return(detail.dataset&&(detail.dataset.customType==='custom-range'));default:return true;}}
return false;};ValueSelector.prototype.rangeFormatValue=function vs_rangeFormatValue(){var formattedValue=""+this.elements.rangeMeter.value+" / "+this.elements.rangeMeter.max;return formattedValue;};ValueSelector.prototype.rangeRenderValue=function vs_rangeRenderValue(){this.elements.rangeMeter.value=this.elements.rangeInput.value;this.elements.rangeValueFormattedLbl.textContent=this.rangeFormatValue(this.elements.rangeMeter.value);};ValueSelector.prototype.numberChange=function vs_numberChange(operation){var step=this.stepVectors[operation];if((step!==undefined)&&(step!==0)){var oldValue=this.elements.rangeInput.value;this.elements.rangeInput.value=parseFloat(this.elements.rangeInput.value)+step;var newValue=this.elements.rangeInput.value;if(oldValue!==newValue){this.rangeRenderValue();this.demoValue(newValue);}
return true;}
return false;};ValueSelector.prototype.demoValue=function vs_demoValue(value){if(this.vsCustomizer.isSettingApplied('mode-in-choice-value-demo')){this._im.setValue(value);}};ValueSelector.prototype.handleRangeEvents=function vs_handleRangeEvents(evt){this.app.debug('handling '+evt.type);switch(evt.type){case'keydown':if((this._showing)&&(this._currentPickerType==='number')){if(this.numberChange(evt.key)){evt.preventDefault();}}
break;}};ValueSelector.prototype.handleEvent=function vs_handleEvent(evt){if(evt.type==='keydown'&&evt.target!==this.app.browser.element&&!this.elements.container.contains(evt.target)){return;}
this.app.debug('handling '+evt.type);var target=evt.target;switch(evt.type){case'spin_date_cancel_req':this.cancel();break;case'spin_date_save_req':this.confirm();break;case'submit':case'mousedown':evt.preventDefault();break;case'keydown':if(this._showing){this.handleRangeEvents(evt);switch(evt.key){case'Backspace':case'EndCall':evt.preventDefault();this.cancel();this.hideTimerPicker();break;case'ArrowLeft':case'ArrowRight':evt.preventDefault();break;case'SoftLeft':this.cancel();evt.preventDefault();break;case'SoftRight':evt.preventDefault();if(this._currentInputType!=='select-multiple'){break;}
var optionIndices=[];var selected=this.elements.container.querySelectorAll('[aria-selected="true"]');for(var i=0;i<selected.length;i++){var index=parseInt(selected[i].dataset.optionIndex);optionIndices.push(index);}
this._im.setSelectedOptions(optionIndices);this._im.removeFocus();this.confirm();break;case"Accept":case"Enter":switch(this._currentPickerType){case'select-multiple':this.selectAction();evt.preventDefault();break;case'select-one':case'number':evt.preventDefault();this.confirm();this.app.setSoftkey&&this.app.setSoftkey();break;}
break;}}
break;case'click':if(target.dataset.type==='cancel'){this.cancel();}else if(target.dataset.type==='ok'){this.confirm();}else if(this._currentPickerType=='select-multiple'){this.selectAction();}else{this.handleSelect(target);}
break;case'_opening':case'_closing':case'_closed':if(this._injected){this.hide();}
break;case'mozbrowservisibilitychange':if(evt.detail.visible&&this._injected){this.hide();}
break;case'_localized':if(this._datePicker){this._datePicker.uninit();this._datePicker=null;}
if(this._timePicker){this.hideTimerPicker();}
break;case'timeformatchange':if(this._timePicker){this.hideTimerPicker();}
break;case'_inputmethod-contextchange':if(evt.detail.inputType==='blur'){this.hide();return;}
if(this._showing){return;}
this.vsCustomizer.parseAppData(evt.detail.dataset);this.selectName=evt.detail.name?evt.detail.name:"";if(this.isInputTypeSupported(evt.detail)){this._currentInputType=evt.detail.inputType;this._currentPickerType=(['datetime','datetime-local'].indexOf(this._currentInputType)>-1)?null:this._currentInputType;if(this._injected){this.vsCustomizer.customize();this.show(evt.detail);}else{this.render(function afterRender(){window.requestAnimationFrame(()=>{window.requestAnimationFrame(()=>{this.show(evt.detail);});});}.bind(this));}}
break;case'transitionend':this.element.classList.remove('transitioning');break;}};ValueSelector.prototype.render=function vs_render(callback){this.publish('willrender');LazyLoader.load('shared/js/template.js',function onTemplateLoaded(){this.containerElement.insertAdjacentHTML('beforeend',this.view());this._fetchElements();this.vsCustomizer.init(this.element);this.vsCustomizer.customize();this._registerEvents();this._injected=true;this.publish('rendered');callback();}.bind(this));};ValueSelector.prototype._fetchElements=function vs__fetchElements(){this.element=document.getElementById(this.CLASS_NAME+this.instanceID);this.elements={};this.elementClasses=['range-popup','range-container','range-input','range-meter','range-value-name-lbl','range-value-formatted-lbl','select-option-popup','container','options-container','select-options-buttons','gh-range-title','gh-time-title','time-title','gh-options-title','options-title','time-picker-popup','time-picker','time-picker-container','time-picker-buttons','spin-date-picker-popup','spin-date-picker','spin-date-picker-buttons'];this.elementClasses.forEach(function createElementRef(name){this.elements[toCamelCase(name)]=this.element.querySelector('.'+this.ELEMENT_PREFIX+name);},this);};ValueSelector.prototype.view=function vs_view(){var template=new Template('value-selector-template');return template.interpolate({id:this.CLASS_NAME+this.instanceID});};ValueSelector.prototype._registerEvents=function vs__registerEvents(){this.elements.container.addEventListener('click',this);this.elements.selectOptionPopup.addEventListener('submit',this);this.element.addEventListener('mousedown',this);this.element.addEventListener('transitionend',this);};ValueSelector.prototype._format=function vs__format(date,format){if(!date){return'';}
date=new Date(date);return date.toLocaleFormat(format);};ValueSelector.prototype.textContentLocalize=function vs_textContentLocalize(textContentOwner,textLocalized,textL10nId){if(textLocalized){textContentOwner.textContent=textLocalized;}else if(textL10nId){_localize(textContentOwner,textL10nId);}};ValueSelector.prototype.showRangeSelector=function vs_showRangeSelector(detail){var titleElement=this.elements.ghRangeTitle;if(titleElement){if(this.selectName){titleElement.textContent=this.selectName;}else{var titleL10nId='tcl-dflt-value-level';ghRangeTitle.dataset.l10nId=titleL10nId;ghRangeTitle.textContent=navigator.mozL10n.get(titleL10nId);}}
this.elements.rangeMeter.min=this.elements.rangeInput.min=parseFloat(detail.min);this.elements.rangeMeter.max=this.elements.rangeInput.max=parseFloat(detail.max);this.elements.rangeInput.value=detail.value||this.elements.rangeInput.value;this.rangeRenderValue();this.elements.rangeInput.step=detail.dataset.customStep||((detail.max-detail.min)/10);this.textContentLocalize(this.elements.rangeValueNameLbl,detail.dataset.customValueName,detail.dataset.customValueNameL10nId);var floatStep=parseFloat(this.elements.rangeInput.step);this.stepVectors=[];this.stepVectors['ArrowUp']=floatStep;this.stepVectors['ArrowDown']=-floatStep;this.showPanel('rangePopup');window.addEventListener('keydown',this);this.front();};ValueSelector.prototype.isActive=function(){return this._showing;}
ValueSelector.prototype.registerSoftKeys=function(){var cskSelect='select';switch(this._currentInputType){case'select-multiple':Service.request('SoftKeyStore:register',{left:'cancel',center:cskSelect,right:'save'},this.app.browser.element);break;case'time':case'date':case'datetime':case'datetime-local':Service.request('SoftKeyStore:register',{left:'cancel',right:'',center:'save'},this.elements.spinDatePickerPopup);Service.request('SoftKeyStore:register',{left:'cancel',right:'',center:'save'},this.app.browser.element);break;default:Service.request('SoftKeyStore:register',{left:'cancel',right:'',center:cskSelect},this.app.browser.element);break;}};ValueSelector.prototype.show=function vs_show(detail){this.registerSoftKeys();var currentValue=this.initialValue=detail.value;this._currentDatetimeValue=currentValue;this._showing=true;this.publish('shown');this.app.publish('value-selector-shown');var min=detail.min;var max=detail.max;if(detail.choices){detail.choices=JSON.parse(detail.choices);}
this.app._setVisibleForScreenReader(false);if(this.element.hidden){this.element.classList.add('transitioning');this.element.hidden=false;}
if(document.activeElement.getAttribute('mozbrowser')){window.addEventListener('keydown',this);}else{window.addEventListener('mozbrowserbeforekeydown',this);}
switch(this._currentInputType){case'select-one':case'select-multiple':this.app.debug('select triggered'+JSON.stringify(detail));if(this._currentPickerType==='select-multiple'){this.elements.optionsContainer.classList.add('valueSelector_multi');this.elements.optionsContainer.classList.remove('valueSelector_single');}else{this.elements.optionsContainer.classList.add('valueSelector_single');this.elements.optionsContainer.classList.remove('valueSelector_multi');}
this.showOptions(detail);break;case'date':window.addEventListener("spin_date_save_req",this);window.addEventListener("spin_date_cancel_req",this);this.showDatePicker(currentValue,min,max);break;case'time':this.showTimePicker(currentValue);break;case'datetime':case'datetime-local':this.showDatePicker(this._format(currentValue,'%Y-%m-%d'),min,max);break;}};ValueSelector.prototype.showPanel=function vs_showPanel(type){['rangePopup','selectOptionPopup','timePickerPopup','spinDatePickerPopup'].forEach(function(elementId){this.elements[elementId].hidden=(type!==elementId);},this);if(type==='selectOptionPopup'||type==='timePickerPopup'||type==='spinDatePickerPopup'){var lock=window.navigator.mozSettings.createLock();lock.set({'selectOptionPopup.state':1});}};ValueSelector.prototype.hide=function vs_hide(decision){this._showing=false;if(this.element){if(!this.element.hidden){if(this._currentPickerType==='select-one'||this._currentPickerType==='select-multiple'){Service.request('Accessibility:stopCustomAccessOutput');}
if(this.vsCustomizer.isSettingApplied('mode-in-choice-value-demo')){document.removeEventListener('focusChanged',this.focusChangedHandler);if(decision!=='confirm'){switch(this._currentPickerType){case'select-one':this._im.setSelectedOption(this.initiallySelectedOptionIndex);break;default:this._im.setValue(this.initialValue);break;}}}
this._im.removeFocus();Service.request('SoftKeyStore:unregister',this.app.browser.element);}}
var self=this;if(self._timePicker){self.hideTimerPicker();}
if(self._datePicker){self._datePicker=null;}
if(self.app){self.app._setVisibleForScreenReader(true);}
if(self.element){if(self.element.hidden){return;}
self.element.blur();self.element.classList.add('transitioning');self.element.hidden=true;}
if(self.app&&(typeof self.app.getBottomMostWindow==='function')){if(self.app.getBottomMostWindow().isActive()&&self.app.isActive()){Service.request('focus');}}
if(self.elements){switch(self._currentPickerType){case'select-one':case'select-multiple':self.elements.optionsContainer.innerHTML='';break;}}
self._showing=false;self.app.publish('value-selector-hidden');self.publish('hidden');window.removeEventListener('keydown',self);window.removeEventListener('mozbrowserbeforekeydown',self);window.removeEventListener("spin_date_save_req",self);window.removeEventListener("spin_date_cancel_req",self);if(self.elements&&(!self.elements['selectOptionPopup'].hidden||!self.elements['timePickerPopup'].hidden||!self.elements['spinDatePickerPopup'].hidden)){var lock=window.navigator.mozSettings.createLock();lock.set({'selectOptionPopup.state':0});}};ValueSelector.prototype.handleSelect=function vs_handleSelect(target){if(target.dataset===undefined||(target.dataset.optionIndex===undefined&&target.dataset.optionValue===undefined)){return;}
var selectee;switch(this._currentPickerType){case'select-one':selectee=this.elements.container.querySelectorAll('.focus');for(var i=0;i<selectee.length;i++){selectee[i].classList.remove('focus');}
target.classList.add('focus');var singleOptionIndex;if(selectee.length>0){singleOptionIndex=selectee[0].dataset.optionIndex;}
this._im.setSelectedOption(singleOptionIndex);break;case'select-multiple':target.classList.toggle('focus',!target.classList.contains('focus'));selectee=this.elements.container.querySelectorAll('.focus');var optionIndices=[];for(var i=0;i<selectee.length;i++){var index=parseInt(selectee[i].dataset.optionIndex);optionIndices.push(index);}
this._im.setSelectedOptions(optionIndices);break;}};ValueSelector.prototype.cancel=function vs_cancel(){this.app.debug('cancel invoked');this.hide();};ValueSelector.prototype.confirm=function vs_confirm(){switch(this._currentInputType){case'number':this._im.setValue(this.elements.rangeInput.value);break;case'select-one':var selectee=this.elements.container.querySelectorAll('.focus');var singleOptionIndex=selectee[0].dataset.optionIndex;this._im.setSelectedOption(singleOptionIndex);this._im.removeFocus();break;case'time':var timeValue=this._timePicker.getTimeValue();this.app.debug('output value: '+timeValue);this._im.setValue(timeValue);break;case'date':var dateValue=this._format(this._datePicker.value,'%Y-%m-%d');this.app.debug('output value: '+dateValue);this._im.setValue(dateValue);break;case'datetime':case'datetime-local':var currentDatetimeValue=this._currentDatetimeValue;switch(this._currentPickerType){case'date':this.showTimePicker(this._format(currentDatetimeValue,'%H:%M'));return;case'time':var selectedDate=this._datePicker.value;var hour=this._timePicker.getHour();var minute=this._timePicker.getMinute();var second='';var millisecond='';var date=null;if(currentDatetimeValue!==''){date=new Date(this._currentDatetimeValue);}else{date=new Date();}
second=date.getSeconds();millisecond=date.getMilliseconds();selectedDate.setHours(hour);selectedDate.setMinutes(minute);selectedDate.setSeconds(second);selectedDate.setMilliseconds(millisecond);var datetimeValue='';if(this._currentInputType==='datetime'){datetimeValue=selectedDate.toISOString();}else{datetimeValue=selectedDate.toLocaleFormat('%Y-%m-%dT%H:%M:%S.')+
selectedDate.getMilliseconds();}
this.app.debug('output value: '+datetimeValue);this._im.setValue(datetimeValue);break;}
break;}
this.hide('confirm');};ValueSelector.prototype.demoOption=function vs_demoOption(optionElement,forcedForElement){if(optionElement!==null){if(optionElement===forcedForElement){this._im.setSelectedOption(-1);}
var optionIndex=optionElement.dataset.optionIndex;this._im.setSelectedOption(optionIndex);}};ValueSelector.prototype.focusChangedHandler=function vs_focusChangedHandler(evt){var focusedElement=evt.detail.focusedElement;if(this.elements.optionsContainer.contains(focusedElement)){this.demoOption(focusedElement);}};ValueSelector.prototype.showOptions=function vs_showOptions(detail){var options=null;if(detail.choices&&detail.choices.choices){options=detail.choices.choices;}
if(options){this.buildOptions(options);}
this.showPanel('selectOptionPopup');var target=this.elements.optionsContainer.querySelector('[aria-selected="true"]');if(detail.inputType==='select-multiple'){target=this.elements.optionsContainer.querySelector('.focus');}
if(target){if(detail.inputType==='select-one'||detail.inputType==='select-multiple'){target.scrollIntoView(false);}else{target.parentNode.scroll(0,0);}}
setTimeout((function(){this.createOptions();if(this.vsCustomizer.isSettingApplied('mode-in-choice-value-demo')){this.initiallySelectedOptionIndex=target?target.dataset.optionIndex:-1;document.addEventListener('focusChanged',this.focusChangedHandler);this.demoOption(this.elements.optionsContainer.querySelector('.focus'),target);}}).bind(this),200);};ValueSelector.prototype.selectAction=function vs_selectAction(){var item=this.elements.optionsContainer.querySelector('.focus');if(!item){return;}
if(item.getAttribute('aria-selected')=='true'){item.removeAttribute('aria-selected');}else{item.setAttribute('aria-selected',true);}};ValueSelector.prototype.createOptions=function vs_createOptions(){this.front();var liOptions=this.elements.optionsContainer.querySelectorAll('li[role="option"]');for(var i in liOptions){if(liOptions[i].style){liOptions[i].style.setProperty('--nav-up',i==0?liOptions.length-1:parseInt(i)-1);liOptions[i].style.setProperty('--nav-down',i==liOptions.length-1?0:parseInt(i)+1);liOptions[i].setAttribute('data-nav-id',i);}}};ValueSelector.prototype.buildOptions=function(options){if(this.elements.optionsContainer){this.elements.optionsContainer.innerHTML='';}else{return;}
var groupTemplate=new Template('value-selector-groupoption-template');var template=new Template('value-selector-option-template');this.elements.optionsContainer.setAttribute('aria-multiselectable',this._currentPickerType==='select-multiple');let firstSelectOption=options.find(function(option){return option.selected;});options.forEach(function(option){if(option.group){this.elements.optionsContainer.insertAdjacentHTML('beforeend',groupTemplate.interpolate({text:option.text}));}else{var focusValue;if(this._currentPickerType==='select-multiple'){if(!firstSelectOption){focusValue=(option.optionIndex===0)?'focus':'';}else{focusValue=(option===firstSelectOption)?'focus':'';}}else{focusValue=option.selected?'focus':'';}
this.elements.optionsContainer.insertAdjacentHTML('beforeend',template.interpolate({index:option.optionIndex.toString(10),checked:option.selected.toString(),for:'gaia-option-'+option.optionIndex,focus:focusValue,text:option.text}));}},this);this.elements.container.classList.toggle('scrollable',options.length>8);var optionsTitle=(this.element.classList.contains('use-gaia-header')?this.elements.ghOptionsTitle:this.elements.optionsTitle);if(optionsTitle){if(this.selectName){optionsTitle.textContent=this.selectName;}else{var titleL10nId=this._currentPickerType==='select-one'?'choose-option':'choose-options';optionsTitle.dataset.l10nId=titleL10nId;optionsTitle.textContent=navigator.mozL10n.get(titleL10nId);}}
this.elements.optionsContainer.ariaLabelledby='value-selector-header';Service.request('Accessibility:startCustomAccessOutput');Service.request('Accessibility:announceElement',this.elements.optionsContainer.querySelector('.focus'));};ValueSelector.prototype.showTimePicker=function vs_showTimePicker(currentValue){this._currentPickerType='time';this.showPanel('timePickerPopup');var time;if(!currentValue){var now=new Date();time={hours:now.getHours(),minutes:now.getMinutes()};}else{time=InputParser.importTime(currentValue);}
if(!this._timePicker){var titleElement=this.element.classList.contains('use-gaia-header')?this.elements.ghTimeTitle:this.elements.timeTitle;this._timePicker=new TimePicker(this.selectName,this.elements.timePickerPopup,titleElement);}
this._timePicker.setTime(time);var _self=this;this._timePicker.setOkCallback(function(){_self.confirm();_self.hideTimerPicker();});this.front();};ValueSelector.prototype.front=function vs_front(){if(!this._showing){return;}
var cskSelect='select';switch(this._currentPickerType){case'time':Service.request('SoftKeyStore:register',{left:'cancel',center:'save'},this.app.browser.element);this._timePicker.front();break;case'select-multiple':case'select-one':var selectee=this.elements.container.querySelectorAll('.hasfocused');for(var i=0;i<selectee.length;i++){selectee[i].classList.remove('hasfocused');selectee[i].classList.add('focus');}
var rKey=this._currentPickerType==='select-multiple'?'save':'';Service.request('SoftKeyStore:register',{left:'cancel',center:cskSelect,right:rKey},this.app.browser.element);break;}};ValueSelector.prototype.back=function vs_back(){switch(this._currentPickerType){case'time':this._timePicker.back();break;case'select-multiple':case'select-one':var selectee=this.elements.container.querySelectorAll('.focus');for(var i=0;i<selectee.length;i++){selectee[i].classList.remove('focus');selectee[i].classList.add('hasfocused');}
break;}};ValueSelector.prototype.hideTimerPicker=function vs_hideTimerPicker(){if(this._timePicker){this._timePicker.uninit();}
this._timePicker=null;};ValueSelector.prototype._str2Date=function vs__str2Date(str){if(!str){return null;}
var dcs=str.split('-');var date=new Date(dcs[0],parseInt(dcs[1])-1,dcs[2]);if(isNaN(date.getTime())){date=null;}
return date;};ValueSelector.prototype.showDatePicker=function vs_showDatePicker(currentValue,min,max){this._currentPickerType='date';this.showPanel('spinDatePickerPopup');var minDate=null;var maxDate=null;minDate=this._str2Date(min);maxDate=this._str2Date(max);if(!this._datePicker){this._datePicker=new SpinDatePicker(this.elements.spinDatePicker);}
this._datePicker.setTitle(this.selectName);this._datePicker.focused();this._datePicker.setRange(minDate,maxDate);var _self=this;var date=new Date();if(currentValue){date=InputParser.formatInputDate(currentValue,'');}
this._datePicker.value=date;};function TimePicker(title,element,titleElement){this.is12hFormat=navigator.mozHour12;this.timeState=[];this.timeItem=element.querySelectorAll('.content');this.upItem=element.querySelectorAll('.up');this.downItem=element.querySelectorAll('.down');this.currentFocus=0;this.inputValue='';this.autoCorrectHandler=null;this.AUTOCORRECT_TIME=3000;this.maxCount=[];if(this.is12hFormat){this.container=element.querySelectorAll('.value-picker-wrapper');this.maxCount[0]=11;this.container[2].style.display="block";element.querySelector('.value-selector-time-picker-container').classList.remove('format24h');this.maxCount[2]=1;}
else{this.container=element.querySelectorAll('.wrapper-number');this.maxCount[0]=23;element.querySelector('.wrapper-word').style.display="none";element.querySelector('.value-selector-time-picker-container').classList.add('format24h');}
this.container[0].classList.add('focused');this.maxCount[1]=59;window.addEventListener("keydown",this);this.frontState=true;titleElement.textContent=(title?title:navigator.mozL10n.get('select-time'));}
TimePicker.prototype={setDisplayedText:function tp_setDisplayedText(){var hour=this.timeState[0];var min=this.timeState[1];if(this.is12hFormat){this._updateAMPM(this.timeState[2]);}
this._updateHour(hour,this.is12hFormat);this._updateMin(min);},uninit:function um_uninit(){window.removeEventListener("keydown",this);this.clearAutoCorrectTimeout();for(var i=0;i<this.container.length;i++){this.container[i].classList.remove('focused');}},front:function um_front(){this.frontState=true;},back:function um_back(){this.frontState=false;},handleEvent:function um_handleEvent(evt){if(!this.frontState){return;}
if(evt.type=='keydown'){switch(evt.key){case'0':case'1':case'2':case'3':case'4':case'5':case'6':case'7':case'8':case'9':evt.preventDefault();this.inputChange(evt.key);break;case"ArrowLeft":evt.preventDefault();this.autoCorrection();this.focusChange(-1);break;case"ArrowRight":evt.preventDefault();this.autoCorrection();this.focusChange(1);break;case"ArrowUp":evt.preventDefault();this.autoCorrection();this.textChange(-1);break;case"ArrowDown":evt.preventDefault();this.autoCorrection();this.textChange(1);break;case"Accept":case"Enter":evt.preventDefault();this.autoCorrection();if(this.callback){this.callback();}
break;}}},setOkCallback:function tp_setOkCallback(callback){this.callback=callback;},_updateAMPM:function tp_updateAMPM(state){var am=_strForTime.localeFormat(new Date('1970-01-01T01:00:00'),'%p');var pm=_strForTime.localeFormat(new Date('1970-01-01T23:00:00'),'%p');if(state===0){this.timeItem[2].textContent=am;this.upItem[2].textContent='';this.downItem[2].textContent=pm;}else{this.timeItem[2].textContent=pm;this.upItem[2].textContent=am;this.downItem[2].textContent='';}},_updateHour:function tp_updateHour(hour,is12hFormat){if(hour===0&&is12hFormat){hour=12;}
this.timeItem[0].textContent=(hour<10?'0':'')+hour;this.upItem[0].textContent=this.is12hFormat?hour==1?'':((hour<11?'0':'')+(hour-1)):hour==0?'':((hour<11?'0':'')+(hour-1));this.downItem[0].textContent=this.is12hFormat?hour==12?'':((hour<9?'0':'')+(hour+1)):hour==23?'':((hour<9?'0':'')+(hour+1));},_updateMin:function tp_updateMin(min){this.timeItem[1].textContent=(min<10?'0':'')+min;this.upItem[1].textContent=min==0?'':((min<11?'0':'')+(min-1));this.downItem[1].textContent=min==59?'':((min<9?'0':'')+(min+1));},startAutoCorrectTimeout:function tp_startAutoCorrectTimeout(){this.clearAutoCorrectTimeout();this.autoCorrectHandler=window.setTimeout(()=>{this.autoCorrection();},this.AUTOCORRECT_TIME);},clearAutoCorrectTimeout:function tp_clearAutoCorrectTimeout(){if(this.autoCorrectHandler){window.clearTimeout(this.autoCorrectHandler);this.autoCorrectHandler=null;}},validDataCheck:function tp_validDataCheck(){let validData;if(this.inputValue){let number=parseInt(this.timeItem[this.currentFocus].textContent);if(this.currentFocus===0&&this.is12hFormat){if(number<1||number>12){this.timeItem[this.currentFocus].classList.add('invalid');validData=Math.max(number,1);if(number>12)validData=0;}else{this.timeItem[this.currentFocus].classList.remove('invalid');validData=number;if(number===12)validData=0;}}else if(number>this.maxCount[this.currentFocus]){this.timeItem[this.currentFocus].classList.add('invalid');validData=this.maxCount[this.currentFocus];}else{this.timeItem[this.currentFocus].classList.remove('invalid');validData=number;}}else{validData=this.timeState[this.currentFocus];}
return validData;},autoCorrection:function tp_autoCorrection(){if(this.inputValue){let validData=this.validDataCheck();this.timeState[this.currentFocus]=validData;if(this.currentFocus===0){this._updateHour(validData,this.is12hFormat);}else{this._updateMin(validData);}}
this.timeItem[this.currentFocus].classList.remove('invalid');this.inputValue='';},inputChange:function tp_inputChange(key){if(this.currentFocus<2){if(this.inputValue.length<2){this.inputValue=this.inputValue+''+key;}else{this.inputValue=''+key;}
this.timeItem[this.currentFocus].textContent=this.inputValue;this.validDataCheck();this.startAutoCorrectTimeout();}},textChange:function tp_textChange(direction){this.timeState[this.currentFocus]=this.timeState[this.currentFocus]+direction;if(this.timeState[this.currentFocus]<0){this.timeState[this.currentFocus]=this.maxCount[this.currentFocus];}else if(this.timeState[this.currentFocus]>this.maxCount[this.currentFocus]){this.timeState[this.currentFocus]=0;}
if(this.currentFocus==2){this._updateAMPM(this.timeState[2]);}else if(this.currentFocus==0){var hour=this.timeState[0];this._updateHour(hour,this.is12hFormat);}else if(this.currentFocus==1){var min=this.timeState[1];this._updateMin(min);}},focusChange:function tp_focusChange(direction){this.container[this.currentFocus].classList.remove('focused');this.currentFocus=this.currentFocus+direction;if(this.currentFocus<0){this.currentFocus=this.container.length-1;}else if(this.currentFocus>this.container.length-1){this.currentFocus=0;}
this.container[this.currentFocus].classList.add('focused');},getMinute:function tp_getMinute(){return this.timeState[1];},getHour:function tp_getHours(){if(this.is12hFormat){if(this.timeState[2]==1){return this.timeState[0]+12;}}
return this.timeState[0];},setTime:function tp_setTime(time){this.container[this.currentFocus].classList.remove('focused');this.currentFocus=0;this.container[this.currentFocus].classList.add('focused');if(this.is12hFormat){if(time.hours>=12){this.timeState[2]=1;this.timeState[0]=time.hours-12;}else{this.timeState[2]=0;this.timeState[0]=time.hours;}}else{this.timeState[0]=time.hours;}
this.timeState[1]=time.minutes;this.setDisplayedText();},getTimeValue:function tp_getTimeValue(){var hour=this.getHour();return(hour<10?'0':'')+hour+':'+(this.timeState[1]<10?'0':'')+this.timeState[1];}};})(window);