
var MusicComms={commands:{play:function(event){this.commands.playpause.call(this,event);},playpause:function(event){this._getPlayerReady(function(){var isResumedBySCO=this.isSCOEnabled;this.isSCOEnabled=event.detail.isSCOConnected;if(isResumedBySCO){if(this._statusBeforeSCO===PLAYSTATUS_PLAYING||this._statusBeforeSCO===INTERRUPT_BEGIN)
{PlayerView.play();}else{PlayerView.pause();}}else{if(PlayerView.playStatus===PLAYSTATUS_STOPPED){PlayerView.dataSource=PlayerView.dataSourceBeforeStop;PlayerView.play(PlayerView.indexBeforeStop,true);}else if(PlayerView.playStatus===PLAYSTATUS_PLAYING){PlayerView.pause();}else{PlayerView.play();}}}.bind(this));},pause:function(event){this.isSCOEnabled=event.detail.isSCOConnected;if(this.isSCOEnabled){this._statusBeforeSCO=PlayerView.playStatus;}
if(!this._isPlayerActivated()){return;}
PlayerView.pause();},stop:function(event){if(!this._isPlayerActivated()){return;}
PlayerView.stop();},next:function(event){if(!this._isPlayerActivated()){return;}
if(PlayerView.playStatus===PLAYSTATUS_STOPPED){PlayerView.dataSource=PlayerView.dataSourceBeforeStop;}
PlayerView.next();},previous:function(event){if(!this._isPlayerActivated()){return;}
if(PlayerView.playStatus===PLAYSTATUS_STOPPED){PlayerView.dataSource=PlayerView.dataSourceBeforeStop;}
PlayerView.previous();},seekpress:function(event){if(!this._isPlayerActivated()){return;}
if(this.cancelRelease){window.clearTimeout(this.cancelRelease);}
if(!PlayerView.isTouching){PlayerView.startFastSeeking(event.detail.direction);}},seekrelease:function(event){if(!this._isPlayerActivated()){return;}
this.cancelRelease=window.setTimeout(()=>{PlayerView.stopFastSeeking();},200);},updatemetadata:function(){this._getPlayerReady(function(){PlayerView.updateRemoteMetadata();});},updateplaystatus:function(){this._getPlayerReady(function(){PlayerView.updateRemotePlayStatus();});}},enabled:false,isSCOEnabled:false,_statusBeforeSCO:null,mozinterruptbegin:false,init:function(){this.mrc=new MediaRemoteControls();for(var command in this.commands){this.mrc.addCommandListener(command,this.commands[command].bind(this));}
this.mrc.start(this.updateSCOStatus.bind(this));this.mrc.notifyAppInfo({origin:window.location.origin,icon:window.location.origin+'/style/icons/music_84.png'});this.enabled=true;this.cancelRelease=null;},_getPlayerReady:function(callback){if(typeof PlayerView==='undefined'){LazyLoader.load('js/ui/views/player_view.js',function(){PlayerView.init();PlayerView.setOptions(App.playerSettings);callback();});}else{callback();}},_isPlayerActivated:function(){return(typeof PlayerView!=='undefined'&&this.mozinterruptbegin===false);},notifyMetadataChanged:function(metadata){if(this.enabled){this.mrc.notifyMetadataChanged(metadata);}},notifyStatusChanged:function(info){if(this.enabled){this.mrc.notifyStatusChanged(info);}},updateSCOStatus:function(){if(this.enabled){this.mrc.getSCOStatus(function(status){this.isSCOEnabled=status;}.bind(this));}},isA2dpConnected:function(cb){if(this.enabled){this.mrc.hasConnectedDevicesByA2dp().then(cb);}}};