
var SimpleNavigationHelper=function(selector,element,scrollSelector,initialFocusIndex){this.selector=selector;this.element=element;this.scrollSelector=scrollSelector;this.initialFocusIndex=initialFocusIndex||0;this.element.addEventListener('keydown',this);this._mutationObserver=new MutationObserver(this.refresh.bind(this));this._mutationObserver.observe(this.element,{childList:true,subtree:true,attributes:true});this.element.addEventListener('focus',this);};SimpleNavigationHelper.prototype={loopable:true,setFocus:function(element,noFocus){if(!element){return;}
this._currentFocus=element;this.element.activeElement=element;if(noFocus){return;}
this.scrollIntoView(element);if(this.element.contains(document.activeElement)){element.focus();}},destroy:function(){if(!this.element){return;}
this.element.removeEventListener('keydown',this);this.element.removeEventListener('focus',this);this._candidates=[];this._mutationObserver.disconnect();this._currentFocus=null;this.element.activeElement=null;this.element=null;},updateCandidates:function(){this._candidates=Array.from(this.element.querySelectorAll(this.selector));var i=this._candidates.length;while(i--){if(this.isHidden(this._candidates[i])){this._candidates.splice(i,1);}}},isHidden:function(elem){let hidden=false;while(elem!==document.body){if(getComputedStyle(elem)&&getComputedStyle(elem)["display"]==="none"){hidden=true;break;}
elem=elem.parentNode;}
return hidden;},isAriaHiddenByAncestor:function(){let isHidden=false;let element=this.element;while(element!==document.body){if('true'===element.getAttribute('aria-hidden')){isHidden=true;break;}
element=element.parentNode;}
return isHidden;},refresh(mutations){if(typeof SubListView!=='undefined'&&SubListView.batchUpdateTimer)return;let shouldResetFocus=false;let needFocusIndex=this.initialFocusIndex;mutations.forEach((mutation)=>{[].slice.call(mutation.removedNodes).forEach((node)=>{if(node.contains(this._currentFocus)){shouldResetFocus=true;needFocusIndex=this.getElementIndex(this._currentFocus);}});});this.updateCandidates();if(ModeManager.dropedMode&&ModeManager.currentMode!==MODE_SUBLIST_LIST&&typeof PlayerView!=='undefined'){ModeManager.dropedMode=null;if(TabBar.option==='title'||ModeManager.currentMode===MODE_SUBLIST||ModeManager.currentMode===MODE_SEARCH_FROM_SUBLIST){if(PlayerView.playStatus==='STOPPED'){let currentIndex=this._currentFocus.dataset.index;if(currentIndex&&Number(currentIndex)>=this.initialFocusIndex){if(ModeManager.currentMode===MODE_LIST){ListView.focusIndex=0;}
shouldResetFocus=true;needFocusIndex=this.initialFocusIndex;}}else if(SubListView.isInMyPlaylist){findFcocus.call(this,'id',PlayerView.playSongId);}else{findFcocus.call(this,'songName',PlayerView.playSongName);}}else if(TabBar.option==='playlist'){findFcocus.call(this,'index',ListView.currentTarget.dataset.index);}else{findFcocus.call(this,'keyRange',ListView.currentTarget.dataset.keyRange);}}
function findFcocus(key,target){this._candidates.some((node,i)=>{if(node.dataset[key]&&node.dataset[key]==target){if(ModeManager.currentMode===MODE_LIST){ListView.focusIndex=parseInt(node.dataset.index);}
shouldResetFocus=true;needFocusIndex=i;return true;}});}
if(shouldResetFocus||((!this._currentFocus||this._currentFocus===this.element)&&this._candidates.length)||this.element===document.activeElement){let next=needFocusIndex===this._candidates.length?this._candidates[this.initialFocusIndex]:this._candidates[needFocusIndex];if(next){this._currentFocus=next;this.element.activeElement=next;}else{this._currentFocus=this.element;this.element.activeElement=null;}}
if(this.element.contains(document.activeElement)&&this._currentFocus!==document.activeElement){this.scrollIntoView(this._currentFocus);this._currentFocus.focus();}},handleEvent:function(evt){if('keydown'===evt.type){this.onKeyDown(evt);}else if('focus'===evt.type){if(this._currentFocus&&this._currentFocus!==this.element){this.scrollIntoView(this._currentFocus);this._currentFocus.focus();return;}
let next=this.findNext();if(next){this.scrollIntoView(next);next.focus();this._currentFocus=next;this.element.activeElement=next;}else{this._currentFocus=this.element;this.element.activeElement=null;}}},onKeyDown:function(evt){let nextFocus=null;let handled=false;let timer;switch(evt.key){case'ArrowDown':handled=true;nextFocus=this.findNext();break;case'ArrowUp':handled=true;nextFocus=this.findPrev();break;default:break;}
if(nextFocus){this._currentFocus=nextFocus;this.element.activeElement=nextFocus;this.scrollElement(nextFocus);requestAnimationFrame(()=>{nextFocus.focus();});}
if(handled){evt.stopPropagation();evt.preventDefault();}},scrollElement:function(node){if(this._currentFocus.id.includes('search')){this.findScrollElement(this._candidates[this.initialFocusIndex].parentNode).scrollTo(0,0);return;}
let parentNode=this.findScrollElement(node.parentNode);if(!parentNode){return;}
if(this._currentFocus===this._candidates[this.initialFocusIndex]){parentNode.scrollTo(0,0);return;}
let nodeRect=node.getBoundingClientRect();let parentRect=parentNode.getBoundingClientRect();let top_node=nodeRect.top;let top_parent=parentRect.top;let height_node=nodeRect.height;let height_parent=parentRect.height;let scrollTop=parentNode.scrollTop;if(top_parent>top_node){return parentNode.scrollTo(0,scrollTop-(top_parent-top_node));}
if(top_node-top_parent>height_parent-height_node){return parentNode.scrollTo(0,scrollTop+
(top_node-top_parent-(height_parent-height_node)));}},findScrollElement:function(_node){if(!_node)return;let styles=window.getComputedStyle(_node);if(styles.overflowY!=='visible'){return _node;}else{return this.findScrollElement(_node.parentNode);}},scrollIntoView:function(element,alignToTop=false){if(!element){return}
if(this.scrollSelector){let target=element;let found=false;while(target!==document.body){if(target.matches(this.scrollSelector)){found=true;target.scrollIntoView(false);break;}
target=target.parentNode;}
if(!found){element.scrollIntoView(alignToTop);}}else{element.scrollIntoView(alignToTop);}},getInitialFocus:function(){let candidates=this._candidates;if(!candidates.length){return null;}
return candidates[this.initialFocusIndex];},getElementIndex:function(element){let candidates=this._candidates;if(!candidates||!candidates.length||!element){return 0;}
let elementIndex=0;candidates.some((dom,index)=>{if(dom===element){elementIndex=index%candidates.length;return true;}else{return false;}});return elementIndex;},findNext:function(element){if(!this._candidates||!this._candidates.length){return null;}
element=element||document.activeElement;let candidates=this._candidates;let next=0;candidates.some((dom,index)=>{if(dom===element){next=(index+1)%candidates.length;return true;}else{return false;}});if(!candidates[next]&&!this.loopable){return null;}
return candidates[next]||candidates[this.initialFocusIndex];},findPrev:function(element){element=element||document.activeElement;let candidates=this._candidates;if(!candidates.length){return null;}
let next=null;candidates.some((dom,index)=>{if(dom===element){next=((candidates.length+index)-1)%candidates.length;if(!this.loopable&&0===index){next=null;}
return true;}else{return false;}});if(!candidates[next]&&!this.loopable){return null;}
return candidates[next]||candidates[this.initialFocusIndex];}};