
navigator.mozL10n.once(function onLocalizationInit(){navigator.mozSetMessageHandler('activity',handleOpenActivity);});var savemusic;var allowSave=false;document.body.classList.toggle('large-text',navigator.largeTextEnabled);navigator.mozAudioChannelManager.volumeControlChannel='content';function handleOpenActivity(request){var data=request.source.data;var blob=request.source.data.blob;allowSave=data.allowSave;var header=document.getElementById('header');var storage;var saved=false;if(!blob.name){blob.name=data.filename;allowSave=true;}
checkAvailable();playBlob(blob);savemusic=save.bind(null);header.addEventListener('action',done);function checkAvailable(){if(data.filename&&checkFilename()){getStorageIfAvailable('music',blob.size,function(ds){storage=ds;},function(err){if(typeof err==='number'){storage='full';}});}}
function playBlob(blob){ModeManager._modeStack.push(MODE_PLAYER);PlayerView.isopenpick=true;PlayerView.init();PlayerView.setSourceType(TYPE_BLOB);PlayerView.dataSource=blob;PlayerView.play();PlayerView.view.focus();PlayerView.onerror=function invalid(){Dialog.show('audioinvalid',null,()=>{request.postResult({});},()=>{request.postResult({});},{type:'hint'});};}
function done(){PlayerView.stop();request.postResult({saved:saved});}
function save(){if(storage==='full'){handleStorageFull()
return;}
let originFilename=data.filename;let title=document.getElementById('player-cover-name').firstChild.textContent;let artist=document.getElementById('player-cover-artist').firstChild.textContent;let suffix=originFilename.match(/.+(\..+)$/)[1];let formatName=title+'_'+artist+suffix;let savedFilename='downloads/'+formatName;getUnusedFilename(storage,savedFilename,function(filename){var savereq=storage.addNamed(blob,filename);savereq.onsuccess=function(){Toaster.showToast({message:filename.substring(filename.lastIndexOf('/')+1)+' '+navigator.mozL10n.get('saved'),latency:2000});saved=filename;checkAvailable();};savereq.onerror=function(e){console.error('Error saving',filename,e);};});}
function checkFilename(){var dotIdx=data.filename.lastIndexOf('.'),ext;if(dotIdx>-1){ext=data.filename.substr(dotIdx+1);if(ext==='ogg'){return true;}else{return MimeMapper.guessTypeFromExtension(ext)===data.type;}}else{return false;}}
function handleStorageFull(){let storageName=navigator.getDeviceStorage('music').storageName;if(storageName==='sdcard'){Dialog.show('full-text',null,()=>{PlayerView.view.focus();},()=>{new MozActivity({name:'moz_configure_window',data:{target:'device',section:'mediaStorage'}});request.postResult({});},{headerl10nId:'storageFullTitle',type:'goto-opt-settings'});}else{Dialog.show('full-text-sdcard',null,()=>{PlayerView.view.focus();},()=>{new MozActivity({name:'moz_configure_window',data:{target:'device',section:'mediaStorage'}});request.postResult({});},{headerl10nId:'sdcardFullTitle',type:'goto-opt-settings'});}}}