
function formatTime(secs){if(isNaN(secs)){return;}
secs=Math.floor(secs);var formatedTime;var seconds=secs%60;var minutes=Math.floor(secs/60)%60;var hours=Math.floor(secs/3600);if(hours===0){formatedTime=(minutes<10?'0'+minutes:minutes)+':'+
(seconds<10?'0'+seconds:seconds);}else{formatedTime=(hours<10?'0'+hours:hours)+':'+
(minutes<10?'0'+minutes:minutes)+':'+
(seconds<10?'0'+seconds:seconds);}
return formatedTime;}
function createListElement(option,data,index,highlight,isSelected,originIndex){var li=document.createElement('li');li.className='list-item focusable';li.setAttribute('tabindex','-1');li.dataset.index=index;li.dataset.option=option;if(data.id){li.dataset.id=data.id;}
if(isSelected){li.dataset.selected='true';}
if(typeof originIndex!=='undefined'){li.dataset.originIndex=originIndex;}
var a=document.createElement('a');a.dataset.index=index;a.dataset.option=option;a.setAttribute('role','option');if(index===0){switch(ModeManager.currentMode){case MODE_LIST:li.id='list-first-item';a.setAttribute('aria-labelledby',TabBar.activateId+' list-first-item');break;case MODE_SUBLIST:li.id='sublist-first-item';a.setAttribute('aria-labelledby','title-text sublist-first-item');break;case MODE_SUBLIST_LIST:li.id='sublist-list-first-item';a.setAttribute('aria-labelledby','title-text sublist-list-first-item');break;default:break;}}
var titleBdi;li.appendChild(a);function highlightText(result,text){var textContent=result.textContent;var textLowerCased=textContent.toLocaleLowerCase();var index=Normalizer.toAscii(textLowerCased).indexOf(text);if(index>=0){var innerHTML=textContent.substring(0,index)+'<span class="search-highlight">'+
textContent.substring(index,index+text.length)+'</span>'+
textContent.substring(index+text.length);result.innerHTML=innerHTML;}}
switch(option){case'playlist':titleBdi=document.createElement('bdi');titleBdi.className='list-playlist-title p-pri';if(data.metadata.l10nId){titleBdi.textContent=navigator.mozL10n.get(data.metadata.l10nId);titleBdi.dataset.l10nId=data.metadata.l10nId;}else{titleBdi.textContent=data.metadata.title||navigator.mozL10n.get('unknownTitle');titleBdi.dataset.l10nId=data.metadata.title?'':'unknownTitle';}
a.dataset.keyRange='all';a.dataset.option=data.option;li.dataset.keyRange='all';li.dataset.option=data.option;a.appendChild(titleBdi);break;case'artist':case'album':case'title':var artistBdi;var icon=document.createElement('div');icon.className='check-icon';icon.setAttribute('aria-labelledby','title-text');icon.setAttribute('role','checkbox');icon.setAttribute('aria-checked',!!isSelected);if(option==='title'){li.insertBefore(icon,a);}else{let albumImg=document.createElement('img');albumImg.setAttribute('aria-hidden',true);albumImg.className='list-album-art';li.insertBefore(albumImg,a);li.insertBefore(icon,albumImg);AlbumArt.getCoverURL(data).then(function(url){showImage(albumImg,url);});}
if(option==='artist'){artistBdi=document.createElement('bdi');artistBdi.className='list-single-title p-pri primary';artistBdi.textContent=data.metadata.artist||navigator.mozL10n.get('unknownArtist');artistBdi.dataset.l10nId=data.metadata.artist?'':'unknownArtist';if(highlight){highlightText(artistBdi,highlight);}
a.appendChild(artistBdi);}else{var albumOrTitleBdi=document.createElement('bdi');artistBdi=document.createElement('bdi');albumOrTitleBdi.className='list-main-title p-pri primary';artistBdi.className='list-sub-title p-sec';if(option==='album'){albumOrTitleBdi.textContent=data.metadata.album||navigator.mozL10n.get('unknownAlbum');albumOrTitleBdi.dataset.l10nId=data.metadata.album?'':'unknownAlbum';}else{albumOrTitleBdi.textContent=data.metadata.title||navigator.mozL10n.get('unknownTitle');albumOrTitleBdi.dataset.l10nId=data.metadata.title?'':'unknownTitle';}
artistBdi.textContent=data.metadata.artist||navigator.mozL10n.get('unknownArtist');artistBdi.dataset.l10nId=data.metadata.artist?'':'unknownArtist';if(highlight){highlightText(albumOrTitleBdi,highlight);}
if('title'===option){var playingsongicon=document.createElement('div');playingsongicon.className='list-playing-icon hidden';playingsongicon.setAttribute('data-icon','sound-max');li.appendChild(playingsongicon);li.dataset.songName=data.name;}
a.appendChild(albumOrTitleBdi);a.appendChild(artistBdi);}
a.dataset.keyRange=data.metadata[option];a.dataset.option=option;li.dataset.keyRange=data.metadata[option];li.dataset.option=option;break;case'list':case'song':case'song-index':case'song-track':case'song-multi-title':case'song-multi-title-track':case'song-multi-title-index':var songTitle=data.metadata.title||navigator.mozL10n.get('unknownTitle');var multicheckicon=document.createElement('div');multicheckicon.className='check-icon hidden';multicheckicon.setAttribute('aria-labelledby','title-text');multicheckicon.setAttribute('role','checkbox');multicheckicon.setAttribute('aria-checked',!!isSelected);var playingsongicon=document.createElement('div');playingsongicon.className='list-playing-icon hidden';playingsongicon.setAttribute('data-icon','sound-max');var indexBdi=document.createElement('bdi');if(option==='song-index'||option==='song-multi-title-index'){indexBdi.textContent=index+1;a.appendChild(indexBdi);}else if(option==='song-track'||option==='song-multi-title-track'){indexBdi.textContent=data.metadata.tracknum;a.appendChild(indexBdi);}
titleBdi=document.createElement('bdi');if(option==='list'){indexBdi.className='list-listname-index p-pri';titleBdi.className='list-listname-title p-pri';}else{indexBdi.className='list-song-index p-pri';titleBdi.className='list-song-title p-pri primary';}
titleBdi.textContent=songTitle;titleBdi.dataset.l10nId=data.metadata.title?'':'unknownTitle';if(/song-multi-title/.test(option)){var songinfo=document.createElement('div');songinfo.className='song-info';artistBdi=document.createElement('bdi');artistBdi.className='list-sub-title p-sec';artistBdi.textContent=data.metadata.artist||navigator.mozL10n.get('unknownArtist');artistBdi.dataset.l10nId=data.metadata.artist?'':'unknownArtist';a.appendChild(songinfo);songinfo.appendChild(titleBdi);songinfo.appendChild(artistBdi);}else{a.appendChild(titleBdi);}
if(option==='list'){li.appendChild(multicheckicon);}else{li.insertBefore(multicheckicon,a);li.appendChild(playingsongicon);}
if(data.name){li.dataset.songName=data.name;}else if(data.listName){li.dataset.listName=data.listName;}
break;}
return li;}
function showImage(image,url,option){image.classList.remove(option);image.src='';if(option==='fadeIn'){image.style.opacity=0;}
image.addEventListener('load',handler);function handler(evt){evt.target.removeEventListener('load',handler);image.classList.add(option);}
image.src=url;}
function startActivity(songData,type){if(songData.metadata.locked){return;}
musicdb.getFile(songData.name,function(file){AlbumArt.getCoverBlob(songData).then(function(pictureBlob){var filename=songData.name,name=filename.substring(filename.lastIndexOf('/')+1);var activityData={type:'audio/*',number:1,blobs:[file],filenames:[name],filepaths:[filename],metadata:[{title:songData.metadata.title,artist:songData.metadata.artist,album:songData.metadata.album,picture:pictureBlob}]};var a=new MozActivity({name:type,data:activityData});a.onerror=function(e){console.warn('share activity error:',a.error.name);};});});}
function createHash(num){let result='';let letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';for(let i=0;i<num;i++){result+=letters.charAt(Math.floor(Math.random()*letters.length));}
return result;}
function marquee(speed,interval){let keyframesRule;Array.prototype.some.call(document.styleSheets[0].cssRules,rule=>{if(rule.type===7&&rule.name==='marquee'){keyframesRule=rule;return true;}
return false;})
document.body.addEventListener('focus',evt=>{if(evt.target.classList.contains('list-item')){let box=evt.target.querySelector('bdi.primary');if(!box){return;}
box.classList.remove('animate-marquee');let oLen=box.scrollWidth;if(box.offsetWidth<oLen){box.dataset.text=box.textContent;box.classList.add('animate-marquee');let dis=box.scrollWidth-oLen;let time=dis/speed;let duration=time+interval;let completePercent=(time/duration).toFixed(4)*100+'%';let recoveryPercent=(time/duration+0.0001).toFixed(4)*100+'%';box.style['animation-duration']=duration+'s';keyframesRule.deleteRule(keyframesRule.cssRules[2].keyText);keyframesRule.deleteRule(keyframesRule.cssRules[1].keyText);keyframesRule.appendRule(`${completePercent} {text-indent: -${dis}px}`);keyframesRule.appendRule(`${recoveryPercent} {text-indent: 0}`);}}},true);}
function playByDongle(ctx){let source=ModeManager.currentMode===MODE_SEARCH_FROM_LIST||ModeManager.currentMode===MODE_SEARCH_FROM_SUBLIST?SearchView.dataSource:ctx.dataSource;if(ctx.source){source=ctx.source;}
let path,title;if(ModeManager.currentMode===MODE_PLAYER){path=ctx.playSongName;title=ctx.nameText.textContent;setTimeout(()=>{if(ModeManager.prevMode===MODE_SUBLIST_LIST){ModeManager.start(MODE_LIST);TabBar.activeTab=TabBar.tabList.indexOf(TAB_SONGS);}else{ModeManager.pop();}});}else{path=source[ctx.focusIndex].name;title=source[ctx.focusIndex].metadata.title;}
typeof PlayerView!=='undefined'&&PlayerView.playStatus==='PLAYING'&&PlayerView.pause();let activity=new window.MozActivity({name:'show',data:{type:'dongle/controller',mediaType:'audio',mediaList:[{path:path,title:title}]}});}
const dongleState={get isJioMediaCableInstalled(){return this._isJioMediaCableInstalled;},set isJioMediaCableInstalled(value){this._isJioMediaCableInstalled=!!value;const mode=ModeManager.currentMode;if(mode===MODE_LIST||mode===MODE_SEARCH_FROM_LIST){ListView.updateSoftKeys();}else if(mode===MODE_SUBLIST||mode===MODE_SUBLIST_LIST||mode===MODE_SEARCH_FROM_SUBLIST){SubListView.updateSoftKeys();}},get canPlayByDongle(){return this.isJioMediaCableInstalled&&this.isDongleConnected;},isDongleConnected:false,}
if(navigator.dongleManager){getJioMediaCable();watchMediaCableInstalled();}
function getJioMediaCable(){navigator.mozApps.mgmt.getAll().then((mozApps)=>{dongleState.isJioMediaCableInstalled=mozApps.some((mozApp)=>{return mozApp.installState==='installed'&&mozApp.manifest.name==='JioMediaCable';});});}
function watchMediaCableInstalled(){navigator.mozApps.mgmt.addEventListener('install',(event)=>{const mozApp=event.application;if(mozApp.installState==='installed'&&mozApp.manifest.activities&&Object.prototype.hasOwnProperty.call(mozApp.manifest.activities,'show')){getJioMediaCable();}});navigator.mozApps.mgmt.addEventListener('uninstall',getJioMediaCable);}