'use strict';function OperatorVariantHelper(iccId,iccCardIndex,listener,persistKey,checkNow){var errMsg=null;var iccManager=window.navigator.mozIccManager;if(!iccManager){errMsg='Expected mozIccManager to be present.';console.error(errMsg);throw new Error(errMsg);}
var settings=window.navigator.mozSettings;if(!settings){errMsg='Expected mozSettings to be present.';console.error(errMsg);throw new Error(errMsg);}
if((iccId==='0')||(iccCardIndex<0)){throw new Error('iccId and iccCardIndex arguments must have a value!');}
this._iccId=iccId;this._iccCardIndex=iccCardIndex;if(listener===undefined||typeof listener!=='function'){throw new Error('listener argument must be a function!');}
this._listener=listener;if(persistKey===undefined||typeof persistKey!=='string'){throw new Error('persistKey argument must be a string!');}
this._persistKey=persistKey;if(!!checkNow){this.customize();}}
OperatorVariantHelper.prototype={_listener:null,_addedListener:null,_iccCard:null,_iccSettings:{mcc:'',mnc:'',iccId:''},_persistKey:null,_disableAll:false,get ICCID_SETTINGS_KEY(){return'operatorvariant.iccId';},get MCC_SETTINGS_KEY(){return'operatorvariant.mcc';},get MNC_SETTINGS_KEY(){return'operatorvariant.mnc';},get MVNO_SETTINGS_KEY(){return'operatorvariant.mvno';},get OPERATOR_VARIANT_DISABLE_ALL_KEY(){return'operatorvariant.disableAll';},get settings(){return window.navigator.mozSettings;},getICCSettings:function(){var transaction=this.settings.createLock();var mccRequest=transaction.get(this.MCC_SETTINGS_KEY);mccRequest.onsuccess=(function(){var mccs=mccRequest.result[this.MCC_SETTINGS_KEY];if(!mccs){this._iccSettings.mcc='000';}else if(!Array.isArray(mccs)){this._iccSettings.mcc=mccs;}else if(!mccs[this._iccCardIndex]){this._iccSettings.mcc='000';}else{this._iccSettings.mcc=mccs[this._iccCardIndex];}
var mncRequest=transaction.get(this.MNC_SETTINGS_KEY);mncRequest.onsuccess=(function(){var mncs=mncRequest.result[this.MNC_SETTINGS_KEY];if(!mncs){this._iccSettings.mnc='00';}else if(!Array.isArray(mncs)){this._iccSettings.mnc=mncs;}else if(!mncs[this._iccCardIndex]){this._iccSettings.mnc='00';}else{this._iccSettings.mnc=mncs[this._iccCardIndex];}
var iccIdsRequest=transaction.get(this.ICCID_SETTINGS_KEY);iccIdsRequest.onsuccess=(function(){var iccIds=iccIdsRequest.result[this.ICCID_SETTINGS_KEY];this._iccSettings.iccId=iccIds&&iccIds[this._iccCardIndex];this.checkICCInfo();}).bind(this);}).bind(this);}).bind(this);},checkMvnoChange:function(){var iccCard=this._iccCard;return new Promise((resolve,reject)=>{var mvnoChange=false;var transaction=this.settings.createLock();var mvnoInfoRequest=transaction.get(this.MVNO_SETTINGS_KEY);mvnoInfoRequest.onsuccess=()=>{var mvnoInfos=mvnoInfoRequest.result[this.MVNO_SETTINGS_KEY];var allMatchPromise=[];var mvnoInfo=(mvnoInfos&&mvnoInfos[this._iccCardIndex])||[];for(var i=0;i<mvnoInfo.length;i++){var matchPromise=new Promise(function(_resolve,_reject){var matchInfo=mvnoInfo[i];var request=iccCard.matchMvno(matchInfo['mvnoType'],matchInfo['mvnoMatchData']);request.onsuccess=()=>{var match=request.result;if(match!==matchInfo['match']){mvnoChange=true;}
_resolve();};request.onerror=()=>{_resolve();};});allMatchPromise.push(matchPromise);}
Promise.all(allMatchPromise).then(()=>{resolve(mvnoChange);});};mvnoInfoRequest.onerror=()=>{resolve(true);};});},checkICCInfo:function(){var iccManager=window.navigator.mozIccManager;this._iccCard=iccManager.getIccById(this._iccId);if(!this._iccCard){return;}
if(!this._iccCard.iccInfo||this._iccCard.cardState!=='ready'){return;}
var mcc=this._iccCard.iccInfo.mcc||'000';var mnc=this._iccCard.iccInfo.mnc||'00';var plmnChanged=(mcc!==this._iccSettings.mcc||mnc!==this._iccSettings.mnc);var iccId=this._iccId;var iccidChanged=(iccId!==this._iccSettings.iccId);if(mcc==='000'){return;}
if(this._iccSettings.iccId===''){return;}
var _applyNewApn=()=>{if(this._addedListener){try{this._listener(mcc,mnc);}
catch(e){console.error('Listener threw an error!',e);}}};if(plmnChanged){_applyNewApn();}else{this.checkMvnoChange().then((changed)=>{if(changed){_applyNewApn();}else{var transaction=this.settings.createLock();var persistKeyGetRequest=transaction.get(this._persistKey);persistKeyGetRequest.onsuccess=(function persistKeyGetRequestCb(){if(!persistKeyGetRequest.result[this._persistKey]){_applyNewApn();}else if(iccidChanged){let settingsLock=window.navigator.mozSettings.createLock();let request=settingsLock.get('ril.data.apnSettings');request.onsuccess=(()=>{let result=request.result['ril.data.apnSettings'];if(!result||!Array.isArray(result)){result=[[],[]];}
settingsLock.set({'ril.data.apnSettings':result});});}}).bind(this);}})}
var transaction=this.settings.createLock();var mccRequest=transaction.get(this.MCC_SETTINGS_KEY);mccRequest.onsuccess=(function(){var mccs=mccRequest.result[this.MCC_SETTINGS_KEY];if(!mccs||!Array.isArray(mccs)){mccs=['000','000'];}
mccs[this._iccCardIndex]=mcc;var mccSettings={};mccSettings[this.MCC_SETTINGS_KEY]=mccs;transaction.set(mccSettings);var mncRequest=transaction.get(this.MNC_SETTINGS_KEY);mncRequest.onsuccess=(function(){var mncs=mncRequest.result[this.MNC_SETTINGS_KEY];if(!mncs||!Array.isArray(mncs)){mncs=['00','00'];}
mncs[this._iccCardIndex]=mnc;var mncSettings={};mncSettings[this.MNC_SETTINGS_KEY]=mncs;transaction.set(mncSettings);var iccIdsRequest=transaction.get(this.ICCID_SETTINGS_KEY);iccIdsRequest.onsuccess=(function(){var iccIds=iccIdsRequest.result[this.ICCID_SETTINGS_KEY];if(!iccIds||!Array.isArray(iccIds)){iccIds=[null,null];}
iccIds[this._iccCardIndex]=iccId;var iccIdSettings={};iccIdSettings[this.ICCID_SETTINGS_KEY]=iccIds;transaction.set(iccIdSettings);this._iccSettings.mcc=mcc;this._iccSettings.mnc=mnc;this._iccSettings.iccId=iccId;}).bind(this);}).bind(this);}).bind(this);},applied:function(){var transaction=this.settings.createLock();var item={};item[this._persistKey]=true;var opVariantReq=transaction.set(item);if(opVariantReq===undefined){return;}
opVariantReq.onerror=(function(event){console.error('Failed to set',this._persistKey,'to true.','Customizations may run again!');}).bind(this);},revert:function(){var transaction=this.settings.createLock();var item={};item[this._persistKey]=false;var opVariantReq=transaction.set(item);if(opVariantReq===undefined){return;}
opVariantReq.onerror=(function(event){console.error('Failed to set',this._persistKey,'to false.','Customizations will not be able to be applied again.');}).bind(this);},customize:function(){this.getICCSettings();},listen:function(listenForChange){if(listenForChange===undefined){listenForChange=true;}
if(listenForChange){this._addedListener=this.customize.bind(this);var iccManager=window.navigator.mozIccManager;this._iccCard=iccManager.getIccById(this._iccId);if(this._iccCard){this._iccCard.addEventListener('iccinfochange',this._addedListener);this._iccCard.addEventListener('cardstatechange',this._addedListener);}else{iccManager.oniccdetected=(function iccDetectedHandler(evt){if(this._iccId!==evt.iccId){return;}
this._iccCard=iccManager.getIccById(this._iccId);this._iccCard.addEventListener('iccinfochange',this._addedListener);this._iccCard.addEventListener('cardstatechange',this._addedListener);}).bind(this);}
return;}
if(this._addedListener){var iccManager=window.navigator.mozIccManager;this._iccCard=iccManager.getIccById(this._iccId);if(this._iccCard){this._iccCard.removeEventListener('iccinfochange',this._addedListener);this._iccCard.removeEventListener('cardstatechange',this._addedListener);}
this._addedListener=null;}}};