'use strict';function BufferLoader(context,urlList,callback){this.context=context;this.urlList=urlList;this.onload=callback;this.bufferList=[];this.loadCount=0;}
BufferLoader.prototype.loadBuffer=function(url,index){let request=new XMLHttpRequest();request.open('GET',url,true);request.responseType='arraybuffer';request.onload=()=>{this.context.decodeAudioData(request.response,(buffer)=>{if(!buffer){alert(`error decoding file data: ${url}`);return;}
this.bufferList[index]=buffer;if(++this.loadCount===this.urlList.length){this.onload(this.bufferList);}});};request.onerror=()=>{alert('BufferLoader: XHR error');};request.send();};BufferLoader.prototype.load=function(){for(let i=0;i<this.urlList.length;++i){this.loadBuffer(this.urlList[i],i);}};class Rings{constructor(){this.DEBUG=false;this.name='Rings';this.forbidden_mute=false;this.sound_enable=true;this.vibrate_enable=true;this.volume=0;this.volumeLevel=15;this.audioOneFrequency=853;this.audioTwoFrequency=960;this.audioFrequencyPeriodic=11;this.vibrateFrequencyMagnification=500;this.telephony=window.navigator.mozTelephony;this.ATTENTION_PATTERN=[4,1,2,1,2,1,4,1,2,1,2];this.sound_sources='../sounds/notifier_bells.opus';this.sound_sources_tw='../resources/sounds/alert_message.opus';this.cmas_specifically_ring_key=false;this.cmas_sound_key='audio.volume.notification';this.cmas_vibrate_key='vibration.enabled';this.cmas_deputy_sound_key='cmas.volume.enable';this.cmas_deputy_vibrate_key='cmas.vibrate.enable';this.operatorName='ST';this.sound_sources_IT='../resources/sounds/R_ETWS.ogg';this.isNeedResetToneVolume=false;this.setNormalSound=false;this.notification_sound='../resources/sounds/New Message_MA.ogg';this.vibrateInterval;}
debug(s){if(this.DEBUG){console.log(`-*- CMAS ${this.name} -*- ${s}`);}}
getAttentionCurveWave(){let result=[];let currentValue=this.volume||1;var patternArray=this.getAttentionPattern(this.audioFrequencyPeriodic);patternArray.forEach((duration)=>{for(let i=0;i<duration;i++){result.push(currentValue);}
currentValue=this.volume-currentValue;});return new Float32Array(result);}
getAttentionPattern(dur){var pattern=this.ATTENTION_PATTERN;switch(dur){case 30:pattern=[4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,1];break;case 10.5:pattern=[4,1,2,1,2,1,4,1,2,1,2];break;case 5:pattern=[4,1,2,1,2];break;case 200:pattern=[4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1];break;case 180:pattern=[4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2,1,4,1,2,1,2];break;default:pattern=this.ATTENTION_PATTERN;break;}
return pattern;}
ringingRemind(bSingleSound=false){this.debug("Enter ringingRemind message");if(this.sound_enable){if(bSingleSound){this.playSingleSound();if(this.vibrate_enable){this.vibrate();}}else{if(this.setNormalSound){this.playNotificationSound();navigator.vibrate([200,200,200,200]);}else{this.playSoundAndVibrate();}}}else if(this.vibrate_enable){this.vibrate();}}
ringTone(synchronousVibrateAndBell){const audioChannelName=this.forbidden_mute?'publicnotification':'notification';this.audioCtx=new AudioContext(audioChannelName);this.audioCtx.onstatechange=((event)=>{if(synchronousVibrateAndBell&&'running'===event.target.state){this.vibrate();}});this.o1=this.audioCtx.createOscillator();this.o2=this.audioCtx.createOscillator();this.gainNode=this.audioCtx.createGain();let time=this.audioCtx.currentTime;this.o1.type='sine';this.o2.type='sine';this.o1.frequency.value=this.audioOneFrequency;this.o2.frequency.value=this.audioTwoFrequency;this.o1.start();this.o2.start();this.o1.stop(time+this.audioFrequencyPeriodic);this.o2.stop(time+this.audioFrequencyPeriodic);let wave=this.getAttentionCurveWave();this.gainNode.gain.setValueCurveAtTime(wave,time,this.audioFrequencyPeriodic);this.o1.connect(this.gainNode);this.o2.connect(this.gainNode);this.gainNode.connect(this.audioCtx.destination);}
vibrate(){let patternArray=this.getAttentionPattern(this.audioFrequencyPeriodic);var pattern=patternArray.map((value)=>{return(value*this.vibrateFrequencyMagnification);});if(this.audioFrequencyPeriodic>30){this.startPeristentVibrate(pattern);}else{navigator.vibrate(pattern);}}
clearVibrateInterval(){if(this.vibrateInterval){clearInterval(this.vibrateInterval);}
navigator.vibrate(0);}
startPeristentVibrate(pattern){let count=0;let max=Math.round(this.audioFrequencyPeriodic/60)-1;navigator.vibrate(pattern);const interval=pattern.reduce((a,b)=>a+b);this.vibrateInterval=setInterval(()=>{if(count>=max){this.clearVibrateInterval();return;}
navigator.vibrate(pattern);count=count+1;},interval);}
getVolumeEnable(){return Utils.getSettingsValue(this.cmas_sound_key).then((volume)=>{this.volume=volume/this.volumeLevel;if(!this.cmas_specifically_ring_key){return Promise.resolve(volume);}
return Utils.getSettingsValue(this.cmas_deputy_sound_key).then((deputy_volume)=>{if(volume&&deputy_volume){return Promise.resolve(deputy_volume);}else{return Promise.resolve(false);}});});}
getVibrateEnable(){return Utils.getSettingsValue(this.cmas_vibrate_key).then((vibrate)=>{if(!this.cmas_specifically_ring_key){return Promise.resolve(vibrate);}
return Utils.getSettingsValue(this.cmas_deputy_vibrate_key).then((deputy_vibrate)=>{if(vibrate&&deputy_vibrate){return Promise.resolve(deputy_vibrate);}else{return Promise.resolve(false);}});});}
playSingleSound(){let finishedLoading=(bufferList)=>{this.source.buffer=bufferList[0];this.source.loop=true;this.source.connect(this.gainNode);this.gainNode.connect(this.audioCtx.destination);this.source.start();};const audioChannelName=this.forbidden_mute?'publicnotification':'notification';this.audioCtx=new AudioContext(audioChannelName);this.source=this.audioCtx.createBufferSource();this.gainNode=this.audioCtx.createGain();let bufferLoader=new BufferLoader(this.audioCtx,[this.sound_sources],finishedLoading);bufferLoader.load();}
stopSingleSound(){if(this.source&&this.gainNode&&this.audioCtx){this.source.stop();this.source.disconnect(this.gainNode);this.gainNode.disconnect(this.audioCtx.destination);if(this.source&&this.source.loop){this.source.loop=false;}
this.debug("Enter stopSingleSound this.isNeedResetToneVolume is "+this.isNeedResetToneVolume);if(this.isNeedResetToneVolume){this.isNeedResetToneVolume=false;Utils.setSettingsValue('audio.volume.notification',0);}}}
playSoundAndVibrate(){let finishedLoading=(bufferList)=>{this.source.buffer=bufferList[0];this.source.loop=true;this.source.connect(this.gainNode);this.gainNode.connect(this.audioCtx.destination);this.source.start(0,0,this.audioFrequencyPeriodic);};const audioChannelName=this.forbidden_mute?'publicnotification':'notification';this.audioCtx=new AudioContext(audioChannelName);this.audioCtx.onstatechange=((event)=>{if('running'===event.target.state){if(this.vibrate_enable){this.vibrate();}}});this.source=this.audioCtx.createBufferSource();this.gainNode=this.audioCtx.createGain();let bufferLoader=new BufferLoader(this.audioCtx,[this.sound_sources_IT],finishedLoading);bufferLoader.load();}
playNotificationSound(){var ringtonePlayer=new Audio();ringtonePlayer.mozAudioChannelType='notification';ringtonePlayer.loop=false;ringtonePlayer.src=this.notification_sound;ringtonePlayer.load();ringtonePlayer.play();}
startSoundAndVibrate(messageId){this.debug("Enter startSoundAndVibrate message id is "+messageId);this.stopSoundAndVibrate();return Promise.all([this.getVolumeEnable(),this.getVibrateEnable()]).then((results)=>{this.sound_enable=this.forbidden_mute?true:results[0];this.vibrate_enable=results[1];this.debug("startSoundAndVibrate sound enable from setting is "+this.sound_enable);this.debug("startSoundAndVibrate vibrate enable from setting is "+this.vibrate_enable);navigator.customization.getValue("def.operator.name").then((operator)=>{var isForceVibrateRing=this.isForceVibrateSound(operator,messageId);this.debug("isForceVibrateRing "+isForceVibrateRing);if(!!isForceVibrateRing){if(!this.sound_enable){this.isNeedResetToneVolume=true;Utils.setSettingsValue('audio.volume.notification',10);}
this.sound_enable=true;this.vibrate_enable=true;}
this.controlWakeLock();if(true===navigator.mozAudioChannelManager.headphones){this.ringingRemind(true);}else{this.checkTelephonyState();}
this.handleDeviceStateChange();});});}
stopSoundAndVibrate(){this.stopSingleSound();this.clearVibrateInterval();if(this.o1&&this.o2&&this.gainNode&&this.audioCtx){this.o1.stop(this.audioCtx.currentTime);this.o2.stop(this.audioCtx.currentTime);this.gainNode.disconnect(this.audioCtx.destination);this.o1=null;this.o2=null;this.gainNode=null;this.audioCtx=null;}}
checkTelephonyState(){if(this.telephony&&((this.telephony.calls&&this.telephony.calls.length>0)||(this.telephony.conferenceGroup&&this.telephony.conferenceGroup.calls&&this.telephony.conferenceGroup.calls.length>0))){this.debug('device current is telephony calls');let bVOLTE=false;if(this.telephony.calls.length>0){this.telephony.oncallschanged=()=>{if(0===this.telephony.calls.length){this.ringingRemind();}};bVOLTE='Normal'!==this.telephony.calls[0].voiceQuality;}
if(this.telephony.conferenceGroup.calls.length>0){this.telephony.conferenceGroup.oncallschanged=()=>{if(0===this.telephony.conferenceGroup.calls.length){this.ringingRemind();}};bVOLTE='Normal'!==this.telephony.conferenceGroup.calls[0].voiceQuality;}
if(bVOLTE){this.debug('device current is VoLTE telephony calls state');this.ringingRemind(true);}else{this.debug('device current is not VoLTE telephony calls state');}}else{this.debug('device current is not telephony calls');this.handleCallsChanged();this.ringingRemind();}}
handleCallsChanged(){this.telephony.addEventListener('callschanged',(event)=>{if('callschanged'!==event.type){return;}
this.telephony.calls.forEach((call)=>{this.debug(`handleCallsChanged state : ${call.state}`);if('incoming'===call.state){this.stopSoundAndVibrate();}});});}
handleDeviceStateChange(){if(navigator.mozAudioChannelManager){navigator.mozAudioChannelManager.onheadphoneschange=()=>{this.ringingRemind(navigator.mozAudioChannelManager.headphones);};}}
controlWakeLock(){Utils.setWakeLock();const delayTime=this.audioFrequencyPeriodic*1000;setTimeout(()=>{if(this.source&&this.source.loop){this.source.loop=false;}
Utils.clearWakeLock();},delayTime);}
isForceVibrateSound(operator,messageId){if(messageId===null||messageId===undefined){return false;}
var messageId=parseInt(messageId);this.debug("messageId "+messageId+"operator "+operator);switch(operator){case'UAE':if(Utils.GSM_PRESIDENTIAL_ALERTS.indexOf(messageId)!==-1||Utils.GSM_EXTREME_THREAT_ALERTS.indexOf(messageId)!==-1||Utils.GSM_SEVERE_THREAT_ALERTS.indexOf(messageId)!==-1||Utils.GSM_CHILD_ABDUCTION_EMERGENCY_ALERTS.indexOf(messageId)!==-1){this.audioFrequencyPeriodic=10.5;return true;}else{return false;}
break;case'NL':if(Utils.CHANNEL_FOR_NL.indexOf(messageId)!==-1){return true;}else{return false;}
break;case'IT':case'LT':if(Utils.GSM_PRESIDENTIAL_ALERTS.indexOf(messageId)!==-1){return true;}else{return false;}
break;case'Pe':if(Utils.CMAS_EMEGENCY_ALERT_PE.indexOf(messageId)!==-1){return true;}else{return false;}
break;case'OM':if(Utils.CMAS_PRESIDENTIAL_ALERTS_RO.indexOf(messageId)!==-1){this.audioFrequencyPeriodic=30;return true;}else if(Utils.CMAS_EXTREME_ALERTS_RO.indexOf(messageId)!==-1||Utils.CMAS_EXERCISE_ALERTS_RO.indexOf(messageId)!==-1){this.audioFrequencyPeriodic=10.5;return true;}else{return false;}
break;case'KSA':if(Utils.GSM_PRESIDENTIAL_ALERTS.indexOf(messageId)!==-1){this.audioFrequencyPeriodic=30;return true;}else if(Utils.GSM_EXTREME_THREAT_ALERTS.indexOf(messageId)!==-1||Utils.GSM_SEVERE_THREAT_ALERTS.indexOf(messageId)!==-1||Utils.GSM_EXERCISE_ALERTS.indexOf(messageId)!==-1){this.audioFrequencyPeriodic=10.5;return true;}else{this.audioFrequencyPeriodic=10.5;return false;}
break;case'UK':if(Utils.GSM_EXTREME_THREAT_ALERTS.indexOf(messageId)!==-1||Utils.GSM_SEVERE_THREAT_ALERTS.indexOf(messageId)!==-1||Utils.GSM_PRESIDENTIAL_ALERTS.indexOf(messageId)!==-1){return true;}else{return false;}
break;case'cl':if(Utils.GSM_PRESIDENTIAL_ALERTS.indexOf(messageId)!==-1){this.setNormalSound=false;this.audioFrequencyPeriodic=200;return true;}else if(Utils.GSM_RMT_TEST_ALERTS.indexOf(messageId)!==-1){this.setNormalSound=true;return false;}else{return false;}
break;case'EU':if(Utils.GSM_PRESIDENTIAL_ALERTS.indexOf(messageId)!==-1){this.setNormalSound=false;this.audioFrequencyPeriodic=180;return true;}else{this.setNormalSound=true;return false;}
break;default:return false;break;}}}