'use strict';(function(exports){var pref='identity.fxaccounts.reset-password.url';var fxaSettingsHelper=SettingsHelper(pref);var fxaURL;fxaSettingsHelper.get(function on_fxa_get_settings(url){fxaURL=url;});var resetPWDURLKey='antitheft.apiServerUrl';var resetPWDURLSettingsHelper=SettingsHelper(resetPWDURLKey);var resetPWDURL;resetPWDURLSettingsHelper.get(function(url){resetPWDURL=url;});function _setAccountDetails(response){if(response&&response.user&&(response.user.email||response.user.phoneNumber)){FxaModuleManager.setParam('done',true);FxaModuleManager.setParam('verified',response.user.verified);}}
function _ensureFxaClient(callback){window.parent.LazyLoader.load('../js/fxa_client.js',function(){callback&&callback();});}
var FxModuleServerRequest={requestVerificationOtp:function(phoneNumber,onsuccess,onerror){_ensureFxaClient(function(){NavigationMap.currentActivatedLength=1;window.parent.FxAccountsClient.requestVerificationOtp(phoneNumber,onsuccess,onerror);});},checkEmail:function fxmsr_checkEmail(email,onsuccess,onerror){_ensureFxaClient(function(){NavigationMap.currentActivatedLength=1;window.parent.FxAccountsClient.queryAccount(email,onsuccess,onerror);});},signIn:function fxmsr_signIn(email,password,onsuccess,onerror){function successHandler(response){_setAccountDetails(response);var authenticated=(response&&response.user&&response.user.verified)||false;onsuccess&&onsuccess({authenticated:authenticated});}
function errorHandler(response){onerror&&onerror(response);}
NavigationMap.currentActivatedLength=1;_ensureFxaClient(function signIn(){window.parent.FxAccountsClient.signIn(email,password,successHandler,errorHandler);});},signInWithOTP:function(phoneNumber,password,onsuccess,onerror){function successHandler(response){_setAccountDetails(response);var authenticated=(response&&response.user&&response.user.verified)||false;onsuccess&&onsuccess({authenticated:authenticated});}
function errorHandler(response){onerror&&onerror(response);}
NavigationMap.currentActivatedLength=1;_ensureFxaClient(()=>{window.parent.FxAccountsClient.signInWithOTP(phoneNumber,password,successHandler,errorHandler);});},signUp:function fxmsr_signUp(email,password,info,onsuccess,onerror){function successHandler(response){_setAccountDetails(response);onsuccess&&onsuccess(response);}
NavigationMap.currentActivatedLength=1;_ensureFxaClient(function signUp(){window.parent.FxAccountsClient.signUp(email,password,info,successHandler,onerror);});},requestPasswordReset:function fxmsr_requestPasswordReset(email,onsuccess,onerror){var url=email?fxaURL+'?email='+email:fxaURL;var activity=new MozActivity({name:'view',data:{type:'url',url:url}});activity.onsuccess=function on_reset_success(){onsuccess&&onsuccess();FxaModuleManager.close();};activity.onerror=function on_reset_error(err){console.error(err);onerror&&onerror(err);};},resetPassword:function fxmsr_resetpassword(email,onsuccess,onerror){if(!navigator.onLine){onerror&&onerror({error:'OFFLINE'});return;}
var api='/accounts';var url=resetPWDURL+api;var params={"login":email,"op":"password_reset_req","cdm":"email"}
var xhr=new XMLHttpRequest({mozSystem:true});xhr.open("PUT",url);xhr.timeout=30000;xhr.setRequestHeader('Content-Type','application/json');xhr.onload=function fmdr_xhr_onload(){if(xhr.status>=200&&xhr.status<300){onsuccess&&onsuccess();}else if(xhr.status==404){onerror&&onerror({error:'ACCOUNT_NOT_FOUND'});}};xhr.onerror=function fmd_xhr_onerror(){onerror&&onerror({error:'UNKNOWN'});};xhr.ontimeout=function fmd_xhr_ontimeout(){xhr.onerror();};xhr.send(JSON.stringify(params));},changePassword:function fxmsr_changePassword(oldPassword,newPassword,onsuccess,onerror){function successHandler(response){_setAccountDetails(response);onsuccess&&onsuccess(response);}
NavigationMap.currentActivatedLength=1;_ensureFxaClient(function changePassword(){window.parent.FxAccountsClient.changePassword(oldPassword,newPassword,successHandler,onerror);});}};exports.FxModuleServerRequest=FxModuleServerRequest;}(window));