
(function(exports){var GLOBAL_MIN_YEAR=1900;var GLOBAL_MAX_YEAR=2099;SpinDataInstanceId='spin-data-instance';var DateRange=(function DateRange(min,max){var _minYear=min.getFullYear();var _maxYear=max.getFullYear();var _minMonth=min.getMonth();var _maxMonth=max.getMonth();var _minDate=min.getDate();var _maxDate=max.getDate();return{get min(){return min;},get max(){return max;},get minYear(){return _minYear;},get maxYear(){return _maxYear;},get minMonth(){return _minMonth;},get maxMonth(){return _maxMonth;},get minDate(){return _minDate;},get maxDate(){return _maxDate;}};});var _dateRange=new DateRange(new Date(GLOBAL_MIN_YEAR,0,1),new Date(GLOBAL_MAX_YEAR,11,31));function getYearText(){var yearText=[];var dateTimeFormat=navigator.mozL10n.DateTimeFormat();for(var i=GLOBAL_MIN_YEAR;i<=GLOBAL_MAX_YEAR;i++){var date=new Date(i,0,1);yearText.push(dateTimeFormat.localeFormat(date,'%Y'));}
return yearText;}
function getYearSelectedDisplayedText(){return this._values[this._selected-GLOBAL_MIN_YEAR];}
function updateYearUI(){var len=this._values.length;this._label.textContent=this.getSelectedDisplayedText();this._upIndicator.textContent=this._selected===this._low?'':this._values[(this._selected-1-GLOBAL_MIN_YEAR+len)%len];this._downIndicator.textContent=this._selected===this._upper?'':this._values[(this._selected+1-GLOBAL_MIN_YEAR)%len];};function getMonthText(){var monthText=[];var date=new Date(1972,2,2);var dateTimeFormat=navigator.mozL10n.DateTimeFormat();monthText.push('0');for(var i=0;i<12;i++){date.setMonth(i);monthText.push(dateTimeFormat.localeFormat(date,'%b'));}
return monthText;}
function getDateText(){var dateText=[];var date=new Date(1970,0,1);var dateTimeFormat=navigator.mozL10n.DateTimeFormat();dateText.push('0');for(var i=1;i<=31;i++){date.setDate(i);dateText.push(dateTimeFormat.localeFormat(date,'%d'));}
return dateText;}
function getDaysInMonth(year,month){var date=new Date(year,month,0);return date.getDate();}
function getDateComponentOrder(){var format=navigator.mozL10n.get('dateTimeFormat_%x');var order='';var tokens=format.match(/(%E.|%O.|%.)/g);if(tokens){tokens.forEach(function(token){switch(token){case'%Y':case'%y':case'%Oy':case'Ey':case'EY':order+='Y';break;case'%B':case'%b':case'%m':case'%Om':order+='M';break;case'%d':case'%e':case'%Od':case'%Oe':order+='D';break;}});}
if(order.length!=3)
order='DMY';return order;}
function createDataPickContainer(className){var container=document.createElement('div');container.classList.add(className);return container;}
function InitNavProperty(nodes,cb){NavigationPropHelper.addHorzNavProperty(nodes,SpinDataInstanceId,cb);return nodes[0];}
if(exports.SpinDatePicker)
return;function SpinDatePicker(element,minDate,maxDate){this.element=element;this.focusedPicker=null;this.yearPicker=null;this.monthPicker=null;this.datePicker=null;this.oldFocus=null;this.bFront=false;var pickerContainer=element.querySelector('.picker-container');var yearPickerContainer=createDataPickContainer('value-picker-year');var monthPickerContainer=createDataPickContainer('value-picker-month');var datePickerContainer=createDataPickContainer('value-picker-date');this.focusChangedHandler=(function spd_focusChanged(detail){if(!this.front)
return;if(detail.status==='focusedChanged'){var picker=this.findFocusedNodeParent(detail.new_focus);if(picker){this.focusedPicker.unfocused();this.focusedPicker.active(false);this.focusedPicker=picker;this.focusedPicker.focused();this.focusedPicker.active();}}}).bind(this);this.front=function(){NavigationPropHelper.active(SpinDataInstanceId);this.bFront=true;this.focusedPicker&&this.focusedPicker.active();};this.back=function(){NavigationPropHelper.active(SpinDataInstanceId,false);this.bFront=false;this.focusedPicker&&this.focusedPicker.active(false);};this.valueSelectorHideHander=(function spd_valueSelectorHide(){this.bFront=false;if(this.focusedPicker){this.focusedPicker.unfocused();this.focusedPicker.active(false);}
window.removeEventListener('value-selector-hidden',this.valueSelectorHideHander);window.removeEventListener('keydown',this.keydownHandler);window.removeEventListener('mozbrowserbeforekeydown',this.keydownHandler);window.removeEventListener('screenchange',this.screenchangeHandler);while(pickerContainer.firstChild){pickerContainer.removeChild(pickerContainer.firstChild);}}).bind(this);this.findFocusedNodeParent=(function spd_findParent(focusedNode){switch(focusedNode.parentNode.className){case'value-picker-year':return this.yearPicker;break;case'value-picker-month':return this.monthPicker;break;case'value-picker-date':return this.datePicker;break;}}).bind(this);this.keydownHandler=(function spd_keydownInternal(evt){if(!this.bFront)
return;switch(evt.key){case'Accept':case'Enter':evt.preventDefault();this.focusedPicker.autoCorrection();window.dispatchEvent(new CustomEvent('spin_date_save_req'));break;case'SoftLeft':case'BrowserBack':case'Backspace':evt.preventDefault();this.focusedPicker.autoCorrection();window.dispatchEvent(new CustomEvent('spin_date_cancel_req'));break;case'ArrowUp':case'ArrowDown':evt.preventDefault();break;}}).bind(this);this.screenchangeHandler=(function spd_screenchangeHandler(evt){}).bind(this);var updateCurrentValue=(function spd_updateCurrentValue(){var selectedYear=this.yearPicker.getSelectedIndex();var selectedMonth=this.monthPicker.getSelectedIndex()-1;var selectedDate=this.datePicker.getSelectedIndex();this._value=new Date(selectedYear,selectedMonth,selectedDate);}).bind(this);var updatePickersRange=(function spd_updatePickersRange(){var selectedYear=this.yearPicker.getSelectedIndex();var selectedMonth=this.monthPicker.getSelectedIndex()-1;var minMonth=1;var maxMonth=12;var minDate=1;var maxDate=31;if(selectedYear===_dateRange.minYear){minMonth=_dateRange.minMonth+1;if(selectedMonth===_dateRange.minMonth)
minDate=_dateRange.minDate;}
if(selectedYear===_dateRange.maxYear){maxMonth=_dateRange.maxMonth+1;if(selectedMonth===_dateRange.maxMonth)
maxDate=_dateRange.maxDate;}
var days=getDaysInMonth(this.yearPicker.getSelectedIndex(),this.monthPicker.getSelectedIndex());minDate=Math.min(minDate,days);maxDate=Math.min(maxDate,days);this.datePicker.setRange(minDate,maxDate);this.monthPicker.setRange(minMonth,maxMonth);}).bind(this);var onvaluechangeInternal=(function spd_onvaluechangeInternal(newDateValue){this.yearPicker.setSelectedIndex(newDateValue.getFullYear());this.monthPicker.setSelectedIndex(newDateValue.getMonth()+1);this.datePicker.setSelectedIndex(newDateValue.getDate());updatePickersRange.apply(this);updateCurrentValue.apply(this);}).bind(this);var onSelectedYearChanged=function spd_onSelectedYearChanged(selectedYear){updatePickersRange.apply(this);updateCurrentValue.apply(this);};var onSelectedMonthChanged=function spd_onSelectedMonthChanged(selectedMonth){updatePickersRange.apply(this);updateCurrentValue.apply(this);};var onSelectedDateChanged=function spd_onSelectedDateChanged(selectedDate){updateCurrentValue.apply(this);};var unitClassName='picker-unit';var yearUnitStyle={valueDisplayedText:getYearText(),className:unitClassName};if(this.yearPicker)
this.yearPicker.uninit();this.yearPicker=new ValuePickerNt(yearPickerContainer,yearUnitStyle);this.yearPicker.getSelectedDisplayedText=getYearSelectedDisplayedText.bind(this.yearPicker);this.yearPicker.updateUI=updateYearUI.bind(this.yearPicker);this.yearPicker.onselectedindexchange=onSelectedYearChanged.bind(this);var monthUnitStyle={valueDisplayedText:getMonthText(),className:unitClassName};if(this.monthPicker)
this.monthPicker.uninit();this.monthPicker=new ValuePickerNt(monthPickerContainer,monthUnitStyle);this.monthPicker.onselectedindexchange=onSelectedMonthChanged.bind(this);var dateUnitStyle={valueDisplayedText:getDateText(),className:unitClassName};if(this.datePicker)
this.datePicker.uninit();this.datePicker=new ValuePickerNt(datePickerContainer,dateUnitStyle);this.datePicker.onselectedindexchange=onSelectedDateChanged.bind(this);var dateComponentOrder=getDateComponentOrder();switch(dateComponentOrder){case'YMD':pickerContainer.appendChild(yearPickerContainer);pickerContainer.appendChild(monthPickerContainer);pickerContainer.appendChild(datePickerContainer);break;case'DMY':pickerContainer.appendChild(datePickerContainer);pickerContainer.appendChild(monthPickerContainer);pickerContainer.appendChild(yearPickerContainer);break;case'MDY':pickerContainer.appendChild(monthPickerContainer);pickerContainer.appendChild(datePickerContainer);pickerContainer.appendChild(yearPickerContainer);break;default:pickerContainer.appendChild(datePickerContainer);pickerContainer.appendChild(monthPickerContainer);pickerContainer.appendChild(yearPickerContainer);break;}
this.onvaluechangeInternal=onvaluechangeInternal.bind(this);}
SpinDatePicker.prototype={_value:null,get value(){return this._value;},set value(value){var old=this._value;if(old!==value){this._value=value;this.onvaluechangeInternal(value);}},get year(){return this._value.getFullYear();},get month(){return this._value.getMonth();},get date(){return this._value.getDate();},handleEvent:function vs_handleEvent(evt){switch(evt.type){case'mousedown':evt.preventDefault();break;}},setRange:function vs_setRange(minDate,maxDate){if(!minDate)
minDate=new Date(GLOBAL_MIN_YEAR,0,1);if(!maxDate)
maxDate=new Date(GLOBAL_MAX_YEAR,11,31);_dateRange=new DateRange(minDate,maxDate);this.yearPicker.setRange(minDate.getFullYear(),maxDate.getFullYear());},uninit:function(){if(this.yearPicker)
this.yearPicker.uninit();if(this.monthPicker)
this.monthPicker.uninit();if(this.datePicker)
this.datePicker.uninit();this.pickerElements.forEach((function pickerElements_forEach(picker){picker.removeEventListener('mousedown',this);}).bind(this));},focused:function(){var old_focused=document.querySelectorAll(".focus");if(old_focused.length>0){old_focused[0].classList.remove('focus');}
this.bFront=true;this.oldFocus=old_focused[0];var firstNode=InitNavProperty(this.element.querySelector('.picker-container').querySelectorAll('label'),this.focusChangedHandler);NavigationPropHelper.setFocus(firstNode);this.focusedPicker=this.findFocusedNodeParent(firstNode);this.focusedPicker.focused();this.focusedPicker.active();window.addEventListener('value-selector-hidden',this.valueSelectorHideHander);if(document.activeElement.getAttribute('mozbrowser')){window.addEventListener('keydown',this.keydownHandler);}else{window.addEventListener('mozbrowserbeforekeydown',this.keydownHandler);}
window.addEventListener('screenchange',this.screenchangeHandler);},setTitle:function(title){document.getElementById('date-title').textContent=title?title:navigator.mozL10n.get('select-date');},onvaluechangeInternal:function(date){}};exports.SpinDatePicker=SpinDatePicker;})(window);