
ValuePickerNt=(function(){function _ValuePickerNt(container,unitStyle){this._container=container;this._values=unitStyle.valueDisplayedText;this._className=unitStyle.className;this._selected=0;this._low=0;this._upper=this._values.length;this._label=null;this._upIndicator=null;this._downIndicator=null;this.inputValue='';this.autoCorrectHandler=null;this.AUTOCORRECT_TIME=3000;this.init();}
function keydown(evt){switch(evt.key){case'0':case'1':case'2':case'3':case'4':case'5':case'6':case'7':case'8':case'9':evt.preventDefault();this.inputChange(evt.key);break;case"ArrowUp":this.autoCorrection();this._selected--;if(this._selected<this._low){this._selected=this._upper;}
this.onselectedindexchange(this._selected);this.updateUI();break;case"ArrowDown":this.autoCorrection();this._selected++;if(this._selected>this._upper){this._selected=this._low;}
this.onselectedindexchange(this._selected);this.updateUI();break;}}
_ValuePickerNt.prototype.init=function(){var len=this._values.length;this._upIndicator=document.createElement('div');this._upIndicator.className="focus-indicator";this._upIndicator.classList.add("up");this._upIndicator.textContent=this._values[(this._selected-1+len)%len];this._container.appendChild(this._upIndicator);this._label=document.createElement('label');this._label.className=this._className;this._label.textContent=this._values[this._selected];this._container.appendChild(this._label);this._downIndicator=document.createElement('div');this._downIndicator.className="focus-indicator";this._downIndicator.classList.add('down');this._downIndicator.textContent=this._values[(this._selected+1)%len];this._container.appendChild(this._downIndicator);this.keydownHandler=keydown.bind(this);};_ValuePickerNt.prototype.getSelectedIndex=function(){return this._selected;};_ValuePickerNt.prototype.getSelectedDisplayedText=function(){return this._values[this._selected];};_ValuePickerNt.prototype.setSelectedIndex=function(index){if(this._selected!==index){this._selected=index;this.updateUI();}};_ValuePickerNt.prototype.setRange=function(low,upper){if(low!==null){this._low=low;}
if(upper!==null){this._upper=upper;}
if(this._selected<low){this.setSelectedIndex(low);this.onselectedindexchange(this._selected);}else if(this._selected>upper){this.setSelectedIndex(upper);this.onselectedindexchange(this._selected);}else{this.updateUI();}};_ValuePickerNt.prototype.focused=function(){this._downIndicator.classList.add('selected');this._upIndicator.classList.add('selected');};_ValuePickerNt.prototype.unfocused=function(){this._downIndicator.classList.remove('selected');this._upIndicator.classList.remove('selected');this.autoCorrection();};_ValuePickerNt.prototype.active=function(bActived){if(arguments[0]===undefined){bActived=true;}
if(bActived){if(document.activeElement.getAttribute('mozbrowser')){window.addEventListener('keydown',this.keydownHandler);}else{window.addEventListener('mozbrowserbeforekeydown',this.keydownHandler);}}else{window.removeEventListener('keydown',this.keydownHandler);window.removeEventListener('mozbrowserbeforekeydown',this.keydownHandler);}};_ValuePickerNt.prototype.updateUI=function(){var len=this._values.length;this._label.textContent=this.getSelectedDisplayedText();this._upIndicator.textContent=this._selected===this._low?'':this._values[(this._selected-1+len)%len];this._downIndicator.textContent=this._selected===this._upper?'':this._values[(this._selected+1)%len];};_ValuePickerNt.prototype.startAutoCorrectTimeout=function(){this.clearAutoCorrectTimeout();this.autoCorrectHandler=window.setTimeout(()=>{this.autoCorrection();},this.AUTOCORRECT_TIME);};_ValuePickerNt.prototype.clearAutoCorrectTimeout=function(){if(this.autoCorrectHandler){window.clearTimeout(this.autoCorrectHandler);this.autoCorrectHandler=null;}};_ValuePickerNt.prototype.validDataCheck=function(){let validData;if(this.inputValue){let number=parseInt(this._label.textContent);if(number<this._low||number>this._upper){this._label.classList.add('invalid');number=Math.max(number,this._low);number=Math.min(number,this._upper);validData=number;}else{this._label.classList.remove('invalid');validData=number;}}
return validData;};_ValuePickerNt.prototype.autoCorrection=function(){if(this.inputValue){let validData=this.validDataCheck();this._selected=validData;this.updateUI();this.onselectedindexchange();}
this._label.classList.remove('invalid');this.inputValue='';};_ValuePickerNt.prototype.inputChange=function(key){if(this.inputValue.length<(this._upper+'').length){this.inputValue=this.inputValue+''+key;}else{this.inputValue=''+key;}
this._label.textContent=this.inputValue;this.validDataCheck();this.startAutoCorrectTimeout();};_ValuePickerNt.prototype.onselectedindexchange=function(index){};return _ValuePickerNt;}());