'use strict';let lowMemory=false;let CONFIG_MAX_IMAGE_PIXEL_SIZE=5*1024*1024;let LOW_MAX_IMAGE_PIXEL_SIZE_NO_JPEG=1431136;const CONFIG_REQUIRED_EXIF_PREVIEW_WIDTH=0;const CONFIG_REQUIRED_EXIF_PREVIEW_HEIGHT=0;const DM_WALLPAPER_KEY='dm.wallpaper.image';const NavigationMap='undefined';(()=>{navigator.getFeature('hardware.memory').then((memOnDevice)=>{if(memOnDevice===256){lowMemory=true;CONFIG_MAX_IMAGE_PIXEL_SIZE=2*1024*1024;}});})();window.onload=function(){navigator.mozSetMessageHandler('activity',function handler(activityRequest){let activityName=activityRequest.source.name;if(activityName!=='setwallpaper'){return;}
createFrame();SoftkeyHelper.init(parames,cancelShare);openImage(activityRequest);});let activity;let blob;let frame;function createFrame(){if(frame){return;}
frame=new MediaFrame(document.getElementById('frame'),false,CONFIG_MAX_IMAGE_PIXEL_SIZE);if(lowMemory){frame.image.setAttribute('animationMode','dontanim');}
if(CONFIG_REQUIRED_EXIF_PREVIEW_WIDTH){frame.setMinimumPreviewSize(CONFIG_REQUIRED_EXIF_PREVIEW_WIDTH,CONFIG_REQUIRED_EXIF_PREVIEW_HEIGHT);}
window.addEventListener('resize',frame.resize.bind(frame));frame.onerror=function invalid(){displayError('imageinvalid');};}
function openImage(request){activity=request;blob=request.source.data.blobs[0];getImageSize(blob,success,function error(){displayError('imageinvalid');});function success(metadata){let pixels=metadata.width*metadata.height;let maxImageSize=CONFIG_MAX_IMAGE_PIXEL_SIZE;if(metadata.type!=='jpeg'&&lowMemory){maxImageSize=LOW_MAX_IMAGE_PIXEL_SIZE_NO_JPEG;}
let filesizelimit=2*maxImageSize;if(pixels>maxImageSize||blob.size>filesizelimit){displayError('imagetoobig');return;}
if(!metadata.preview||pixels<512*1024){setTimeout(function(){frame.displayImage(blob,metadata.width,metadata.height,null,metadata.rotation,metadata.mirrored);},10);}else{parseJPEGMetadata(blob.slice(metadata.preview.start,metadata.preview.end,'image/jpeg'),function success(previewmetadata){metadata.preview.width=previewmetadata.width;metadata.preview.height=previewmetadata.height;frame.displayImage(blob,metadata.width,metadata.height,metadata.preview,metadata.rotation,metadata.mirrored);},function error(){frame.displayImage(blob,metadata.width,metadata.height,null,metadata.rotation,metadata.mirrored);});}}}
function displayError(msgid){showToaster(msgid);activity.postError('cancelled');activity=null;}
function showToaster(id){const options={messageL10nId:id};Toaster.showToast(options);}
function downResolusion(){return new Promise((resolve)=>{getImageSize(blob,(metadata)=>{let imagesize=metadata.width*metadata.height;let scale=(window.innerWidth*window.devicePixelRatio*window.innerHeight*window.devicePixelRatio)/imagesize;let sampleSize=Downsample.areaNoMoreThan(scale);let url=URL.createObjectURL(blob);url=url+sampleSize;let canvas=document.createElement('canvas');let screenWidth=document.body.clientWidth*window.devicePixelRatio;let screenHeight=document.body.clientHeight*window.devicePixelRatio;canvas.width=screenWidth;canvas.height=screenHeight;let img=new Image();img.src=url;img.onload=()=>{let actualWidth=img.width;let actualHeight=img.height;let widthScale=screenWidth/actualWidth;let heightScale=screenHeight/actualHeight;let scale=Math.max(widthScale,heightScale);let cropWidth=Math.round(screenWidth/scale);let cropHeight=Math.round(screenHeight/scale);let cropLeft=Math.floor((actualWidth-cropWidth)/2);let cropTop=Math.floor((actualHeight-cropHeight)/2);let cvs=document.createElement('canvas');cvs.width=screenWidth;cvs.height=screenHeight;let context=cvs.getContext('2d');context.drawImage(img,cropLeft,cropTop,cropWidth,cropHeight,0,0,screenWidth,screenHeight);cvs.toBlob((newBlob)=>{URL.revokeObjectURL(img.src);resolve(newBlob);},'image/jpeg');};});});}
function setWallpaper(){downResolusion(blob).then(newBlob=>{const settingsHandle=navigator.mozSettings;const lock=settingsHandle.createLock();lock.get(DM_WALLPAPER_KEY).then((value)=>{if(value[DM_WALLPAPER_KEY]){showDialog();}else{const request=settingsHandle.createLock().set({'wallpaper.image':newBlob});request.onsuccess=()=>{showToaster('kai-wallpaper-set');activity.postResult('shared');endShare();};request.onerror=()=>{console.warn('error setting wallpaper.image:',request.error);activity.postError('could not set wallpaper: '+request.error);endShare();};}});if(lock.forceClose){lock.forceClose();}});}
function cancelShare(){activity.postError('cancelled');endShare();}
function endShare(){SoftkeyHelper.hide();activity=null;}
function showDialog(){const dialogConfig={title:{id:'dialog-title-action-disabled',args:{}},body:{id:'dialog-body-action-disabled',args:{}},accept:{l10nId:'dialog-button-ok',priority:2,callback:()=>{activity.postError('could not set wallpaper');}}};const dialog=new ConfirmDialogHelper(dialogConfig);dialog.show(document.getElementById('app-dialog'));}
var parames={header:{l10nId:'message'},items:[{name:'Cancel',l10nId:'cancel',priority:1,method:cancelShare},{name:'Set',l10nId:'set-wallpaper',priority:3,method:setWallpaper},]};};